### ISSUE TITLE
Workspace too large to index

### ISSUE THREAD

**Issue by sarink** [castwide/solargraph#109]
It seems like my `include` is being ignored. Even with the following `.solargraph.yml` file:
```
---
include:
- "config/application.rb"
```
I get the message "workspace too large to index, found 5132 files, max is 5000" 🤔 what am I missing?

My project is pretty small, presumably the `vendor` directory is not being ignored (although I see from here https://github.com/castwide/solargraph/blob/71471bd52b650da97ce723c66ed2d5d42fe5502c/lib/solargraph/workspace/config.rb#L22 that `vendor/**/*` is one of the default exclusions)

**Comment by castwide** [comment]
What editor are you using?

Is the .solargraph.yml file in the root directory of the project? Are you running a multi-root workspace?

I'm not sure what else could be going wrong. Given that `include` setting, the workspace should consist of a single file.

**Comment by sarink** [comment]
I'm using VSCode. The root directory of the _repository_ is one level up, but all the ruby code, and the .solargraph.yml file, exist inside the `backend` directory (which is at the root).

How can I tell solargraph the root is the `backend` directory? Is VSCode somehow telling it otherwise?

**Comment by castwide** [comment]
If you open `repo_root` as the workspace, that's where Solargraph looks for .solargraph.yml.

I expect to support multi-root workspaces in a future version, which would allow for setups like that one. For now, I can think of two solutions: either 1) open `backend` and `frontend` in separate VSCode windows; or 2) move .solargraph.yml up to the root directory.

**Comment by castwide** [comment]
Related issue: #114

**Comment by castwide** [comment]
Support for multi-root workspaces is released in v0.30.0 (#114). This gives you the ability to create a workspace and add `backend` and `frontend` as workspace folders. Solargraph will check each folder for a `.solargraph.yml` file and map them accordingly.

One possible issue: The folder containing your code-workspace file is treated as a workspace folder, so Solargraph will still try to map it. You can disable it by adding a .solargraph.yml file that includes nothing:

```
include: []
```
