### ISSUE TITLE
Go to definition not working correctly for namespace-prefixed symbols

### ISSUE THREAD

**Issue by whitebyte** [castwide/solargraph#111]
This works as expected and goes to a right definition
```ruby
MyService.process!(data)
```

This goes to some random file that happened to have "somenamespace" in it's name
```ruby
Somenamespace::MyService.process!(data)
```

Maybe somewhat related to https://github.com/castwide/solargraph/issues/107

**Comment by castwide** [comment]
One possibility: are you selecting go to definition with the cursor over `Somenamespace`? The server returns definitions for the current symbol, even if the symbol is part of a longer signature. Selecting go to definition over `process!` should take you to the method definition.

**Comment by whitebyte** [comment]
None of these scenarios work properly. When I go-to on a namespace part, it brings me to some random file. If I go-to on a method name, it just stays on the same string, in the same file. It goes to the correct definition for classes without namespace prefixes

**Comment by castwide** [comment]
At least part of this issue (and #107) might be specific to Neovim. A similar issue was reported in #102. I haven't done a lot of testing in Neovim yet, but it's on my radar.
