### ISSUE TITLE
Wrong class name

### ISSUE THREAD

**Issue by matugm** [castwide/solargraph#112]
Hi,
thanks for all your work on this gem!

I found an issue when hovering over a class name which shares a suffix with a built-in Ruby class.

**Example**:

```ruby
class Space
end

Space.new
```

Solagraph says this is the `ObjectSpace` class & shows me the documentation for that.

**Another example**:

```ruby
class VM
end

VM.new
```

This says `RubyVM `& `VM` right under it, no documentation unless I hover over `new`.

Using solagraph v0.29.3 with vscode.

Thank you.

**Comment by castwide** [comment]
Confirmed. I found a quick fix that appears to resolve the issue. Barring unforeseen bugs, I'll include it in the next patch release.

**Comment by castwide** [comment]
Released v0.29.4.
