### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by PanisSupraOmnia** [castwide/solargraph#117]
I at least would greatly appreciate it if this project had a [changelog](https://keepachangelog.com). The way it's currently being done with tag messages is definitely better than a lot of projects, but having an actual CHANGELOG.md would be a great benefit, especially to a project like this for which documenting changes to the API are important.

I'm not yet familiar with this codebase, but I can probably take some time to pull together a PR if it's wanted.

**Comment by castwide** [comment]
Works for me. If you want to make a PR, I'll add it to the repo and keep it up to date with releases.

**Comment by castwide** [comment]
CHANGELOG.md has been added to the repo.
