### ISSUE TITLE
Autocomplete on blocks

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#123]
Let's say we have an `User` model which allows us to use `&block`
```
    u = User.new
    u.# <- autocomplete works as expected.
```

Like this one:
```
    User.new do |m|
      m.# <-no auto-complete...
      # @type m [User]
      m.# <-no auto-complete... But is it possible to implement?
    end
```

Is it possible to implement such feature? I explicitly assigned `User` to `m`. However, we must able to assign another type based on this data (like in each.) 

Illustration:

![first](https://user-images.githubusercontent.com/1711576/50492065-87822880-0a26-11e9-979c-e47932897ad7.gif)

**Comment by castwide** [comment]
There are two ways you can accomplish that. The first, which I recommend, is the `@yieldparam` tag. You can apply it to the method definition, and any block you pass to the method will pass the type to the parameter. Example:

```ruby
class User
  # @yieldparam [User]
  def initialize
    yield self if block_given?
  end
end

User.new do |m|
  m. # <- recognized as User
end
```

(Side note: you should also be able to use `@yieldparam [self]`, but for some reason it didn't work for me. I'll have to look into that.)

If you can't or don't want to tag the method for some reason, your other option is to apply a `@param` tag to the block itself:

```ruby
class User; end

# @param [User]
User.new do |m|
  m. # <- recognized as User
end
```

That particular use of `@param` is nonstandard in YARD, but it shouldn't hurt anything. It's attached to an internal implementation detail, so generated YARD documentation should ignore it.

This page has very comprehensive documentation for the various tags: https://www.rubydoc.info/gems/yard/file/docs/Tags.md

**Comment by gencer** [comment]
BTW, I do generate `Sequel` (_db_) Helpers using `Rakefile`. I also confirm that first option does not work as expected. I will use first option for my models and second option for gems.
