### ISSUE TITLE
Uninitialized constant Solargraph::Shell::CodeMap

### ISSUE THREAD

**Issue by kputnam** [castwide/solargraph#126]
When running `solargraph suggest test.rb --line 0 --column 10`, it fails because `CodeMap` is not defined. I couldn't find any definition for a class named CodeMap.

https://github.com/castwide/solargraph/blob/ff62143b003b2e92105ade6496bfbc41eb56be1f/lib/solargraph/shell.rb#L66

**Comment by castwide** [comment]
The `solargraph suggest` command has been flagged for deprecation for a long time. It used to be an alternative to the old web API for client integration, but I abandoned both in favor of the [language server protocol](https://microsoft.github.io/language-server-protocol/specification).

What's your use case? I might be able to help you script something that fits your needs if you're trying to analyze code without using a language server. You can also find some examples of how to use the library directly in [EXAMPLES.md](https://github.com/castwide/solargraph/blob/master/EXAMPLES.md).

**Comment by kputnam** [comment]
I don't have a use case in mind, but I was troubleshooting an issue with neovim and came across the `suggest` command. I saw that it was deprecated, but didn't know if it was supposed to work (and then maybe my issue with neovim was a bigger issue), or if it was only a vestige of an older feature.
