### ISSUE TITLE
Failed to start solargraph in both VSCode and Atom`

### ISSUE THREAD

**Issue by foreverqihe** [castwide/solargraph#133]
Hi,

 Tested on 0.30.2 and latest atom and vs code. The error is:

[NoMethodError] undefined method `parameters' for #<Solargraph::Pin::Namespace:0x00000010e44610>

Regards,
Elf

**Comment by castwide** [comment]
Do you get a stack trace or any other messages in the developer console?

**Comment by foreverqihe** [comment]
There was a warning:
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.7-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
undefined method `parameters' for #<Solargraph::Pin::Namespace:0x00000010e44610>

Does it explain something?

**Comment by foreverqihe** [comment]
I tried to fall back. And 0.26.1 seems working. 0.27.4 doesn't . I didn't test the minor versions in between.

**Comment by foreverqihe** [comment]
Sorry, 0.27.1

**Comment by castwide** [comment]
Thanks. It looks like the problem stems from a `@!method` directive somewhere in your code. I was able to reproduce it with the following example:

```
class Foo
  # @!method bar(
end
```

The mapper shouldn't choke on it, regardless of whether the method definition is valid. I'll fix it in the next update.

**Comment by foreverqihe** [comment]
Thank you very much for prompt fix!

**Comment by castwide** [comment]
The fix is published in gem v0.31.0.
