### ISSUE TITLE
Any way to donate?

### ISSUE THREAD

**Issue by hackhowtofaq** [castwide/solargraph#138]
I am using this gem from day 1.

You have made tremendous job to bring it in the current state!

Please add a donate button somewhere, I really want to buy you a beer ! ;)

**Comment by castwide** [comment]
Thanks, I appreciate the consideration. I've been looking into options and will post an update when I know more.

**Comment by castwide** [comment]
The [README](https://github.com/castwide/solargraph/blob/master/README.md) now includes links to sponsor via [Patreon](https://www.patreon.com/castwide) and contribute one-time donations via [PayPal](https://www.paypal.me/castwide).
