### ISSUE TITLE
Variables not showing up in functions/blocks ?

### ISSUE THREAD

**Issue by ctsstc** [castwide/solargraph#149]
## Issue

I'm not getting variable completion inside of function blocks for some reason.
Right now I'm in VSCode using the Solargraph extension and it's the only extension I have installed.

```ruby
nums = '1,2,3'
nums. # auto completion works here
```

```ruby
def test
  nums = '1,2,3'
  nums. # auto completion does not work here it does not find nums
end
```

## Video Example

Here's a video example of what I'm experiencing
https://ctsstc.tinytake.com/sf/MzI2MTIyM185NzY4NDYz

That was an odd one because it was having some issues even showing up properly at the top level; maybe there was some lag going on there? Then I copied it into the block and ironically this time it worked when it normally doesn't but I think it was falsely looking to work because it was lagging and providing auto completion for when it was top level outside of the function block. I think a lot of the shenanigans you saw in the video must have been some lag between the library and VSCode.

**Comment by ctsstc** [comment]
I'm now just wondering if this was a syntax issue in another file and lag when I tried to reproduce it... Hrmmm

**Comment by castwide** [comment]
That could very well be. Syntax errors can have strange effects on completion suggestions, especially when they result in an unclosed namespace or method.

**Comment by ctsstc** [comment]
I'll double check tonight and then close this out most likely. Thanks for checking in @castwide.

**Comment by ctsstc** [comment]
Seemed to be VSC extension lag and a syntax error :)
