### ISSUE TITLE
Updates to core documentation

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#155]
The latest versions of the core documentation introduce a few components that were previously missing, including a few File singleton methods. You can download the latest documentation for your current Ruby version with the executable:

```
$ solargraph download-core
```

To determine whether your documentation is current, you can test for some of the previously missing methods in any editor that uses the Solargraph language server:

```
File. #         <- Completion suggestions should include `exist?`
require 'pathname'
Pathname.new. # <- Completion suggestions should include `join`
```

**Comment by gencer** [comment]
@castwide for `Pathname`, `join` or `as_join`? Because I have `exist?` in File, but _no join in Pathname._

**Comment by castwide** [comment]
It's an instance method, so it should show up as `Pathname.new.join`.

**Comment by gencer** [comment]
Nope. Pathname does not have `join`. Tried dozen times.

```
$ solargraph download-core
```

![nienbobot](https://user-images.githubusercontent.com/1711576/52555668-6a00f680-2dfb-11e9-92ff-7758d68e8a2c.gif)

Dirs in my user folder:

```
.solargraph/cache/2.5.3
.solargraph/cache/2.2.2
```

**Comment by castwide** [comment]
I suspect that's an unrelated bug in how the server synchronizes updates. I'm going to release a fix for it in version 0.31.3 later today.

Does it work if you start `Pathname.new` on a new line at the end of the file?

**Comment by gencer** [comment]
You mean like this:

![image](https://user-images.githubusercontent.com/1711576/52556520-da107c00-2dfd-11e9-83a2-e2fdca12dc26.png)

Nope. :(

**Comment by castwide** [comment]
Hmm. Do you have `require 'pathname'` in your code? I should have mentioned that earlier. I'll update the OP with it.

If it still doesn't work, we'll see if updating to version 0.31.3 fixes it and go from there.

**Comment by gencer** [comment]
It did worked. However, shouldn't it `core`? I mean File is also core feature and autocompletes. Why not `pathname`?

![image](https://user-images.githubusercontent.com/1711576/52557235-dd0c6c00-2dff-11e9-9bf4-f2ff36b5f863.png)

**Comment by castwide** [comment]
Ah, good.

`Pathname` is part of the stdlib. It's distributed with the Ruby core, but you need to `require 'pathname'` to import it into your code. Similar to `fileutils` and `date`. Example in irb:

```
irb(main):001:0> Pathname.new('/test')
Traceback (most recent call last):
        2: from C:/Rubies/Ruby253-x64/bin/irb.cmd:19:in `<main>'
        1: from (irb):1
NameError (uninitialized constant Pathname)
irb(main):002:0> require 'pathname'
=> true
irb(main):003:0> Pathname.new('/test')
=> #<Pathname:/test>
```

`File` is part of the Ruby core itself.

**Comment by gencer** [comment]
Now everything makes sense. Thank you for the clarification.

**Comment by connorshea** [comment]
Yup, works for me in VSCode. It does seem like suggestions need >10 seconds to load up before they can be used, though that may be caused by other extensions or something else I’m doing. Or that’s expected behavior because of how VSCode works.

**Comment by castwide** [comment]
@connorshea Yeah, that's probably normal. It usually takes a couple seconds for VS Code to activate the extension, and then a couple more to initialize the server. The latter can vary depending on the size of your project, e.g., a workspace with 50k lines of code might take a while.
