### ISSUE TITLE
Is it possible to replace YARD with something else?

### ISSUE THREAD

**Issue by FallenAngel97** [castwide/solargraph#156]
Hello, I'm trying to enable autocompletion for my project in VIM and VSCode. Your extension work great, thanks, but yard is blaming `gtk3` gem for some methods: https://github.com/lsegal/yard/issues/1222 
Can I use something else to enable autocompletion?

**Comment by castwide** [comment]
Sorry, no.

Based on the log in the other issue, autocompletion should still work for everything except gtk3. If autocompletion doesn't work at all, there might be a problem somewhere else.

**Comment by FallenAngel97** [comment]
Well, Ok than. 
So, if it is bot possible to switch, then I'll close this issue and willl hope that yard maintainer will fix that.
Thanks :)
