### ISSUE TITLE
Reference tab don't interpret object type

### ISSUE THREAD

**Issue by hima2nd** [castwide/solargraph#163]
VSCode : Ruby Solargraph Version 0.19.3
Solargraph Version 0.31.3

`(see #method)` and `@param (see #method)` don't interpret argument object type in define block.
`(see #method)` don't interpret return value object type.

Here's example code:
```
class Test
  # @param [String] var test_var
  # @return [String] test_return
  def method(var)
    var
  end

  # (see Test#method)
  def ref_method(var)
    # Solargraph has no interpret type of "var"
    var
  end

  # @param (see Test#method)
  # @return [String] test_return
  def ref_param_method(var)
    # Solargraph has no interpret type of "var" 
    var
  end

  # @param [String] var test_var
  # @return (see Test#method)
  def ref_return_method(var)
    var
  end
end

# Solargraph has no interpret type of "ref_method" 
Test.new.ref_method
```

**Comment by castwide** [comment]
Support for `@param (see)` is on the roadmap. It's a little trickier than `@return` but very possible.

**Comment by castwide** [comment]
The issue with `ref_method` is a little different. The `see` reference needs to be in a `@return` tag:

```ruby
class Test
  # @param [String] var test_var
  # @return [String] test_return
  def method
  end

  # @return (see Test#method)
  def ref_method
  end
end

Test.new.ref_method. # <- String instance methods
```

I noted, however, that although the completion request recognizes that `ref_method` returns a `String`, the hover request does not. We should be able to resolve the type in the hover request as well.

I'm not sure what to do about `(see)` outside of tags. The YARD reference seems to say that it belongs inside either a `@return` or a `@param`. Solargraph might be able to fall back to a `@see` tag in cases where `@return` and `@param` are not otherwise defined.

**Comment by hima2nd** [comment]
Sorry, my english is so bad

I understood about `@param(see)`. I expect it.

 I confirmed `(see)` in this document
https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md#Reference_Tags

I'm asking "ref_method" to interpret the object type like "method".

**Comment by castwide** [comment]
Thanks for the link. I had checked the [Tags Overview](https://www.rubydoc.info/gems/yard/file/docs/Tags.md) and didn't see any mention of that syntax. I'll look into it.

**Comment by castwide** [comment]
Support for top-level `(see #method)` references is in the master branch. (Return types only. Param types are still pending.)

**Comment by hima2nd** [comment]
Thanks for the quick update. it's incredibly useful.
Keep up the good work!

**Comment by castwide** [comment]
`(see #method)` return type support is released in v0.32.0. I hope to add support for param types in v0.33.

**Comment by castwide** [comment]
Gem 0.33.2 supports (see) references in `@param` tags and top-level comments.

**Comment by castwide** [comment]
Support for (see) references should be complete now. If there are still any outstanding issues, please feel free to open a new issue.
