### ISSUE TITLE
demo now not working

### ISSUE THREAD

**Issue by rezzovskij** [castwide/solargraph#165]
http://solargraph.org/demo

**Comment by castwide** [comment]
Do you mean it's *not* working? If so, can you tell me what you tried that didn't work?

Incidentally, the Solargraph version in the demo is way behind the current release. I'll work on getting it updated.

**Comment by rezzovskij** [comment]
not working - "Instructions: Enter some Ruby code and press ctrl+space to see a list of suggestions"

**Comment by gencer** [comment]
It works here.

```
Foo. <# Ctrl+Space here gives intellisense  popup.
```

**Comment by rezzovskij** [comment]
> It works here.
> 
> ```
> Foo. <# Ctrl+Space here gives intellisense  popup.
> ```

unfortunately ctrl + space not working

**Comment by castwide** [comment]
The online demo has been updated to use gem 0.33.2. `ctrl+space` works in my tests.
