### ISSUE TITLE
Autocomplete does not initiated when ! used at start

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#166]
When we put negative mark at start, Autocomplete does not work.

For example;

```ruby
if tes #=> test shows up.

if !te #=> no autocomplete
```

See below GIF:

![notation](https://user-images.githubusercontent.com/1711576/54479116-c6a46680-482a-11e9-9280-518a65612803.gif)

**Comment by castwide** [comment]
Confirmed. This appears to be a simple bug in word detection. I should be able to fix it for the next release.

**Comment by castwide** [comment]
Fixed in the master branch.

**Comment by castwide** [comment]
Released in v0.32.0.
