### ISSUE TITLE
Logo licensing

### ISSUE THREAD

**Issue by PyvesB** [castwide/solargraph#174]
Hello there,

I've recently been working on an Eclipse plugin to integrate Solargraph within the IDE. I'm thinking about open-sourcing the work I've done so far and sharing the plugin on the Eclipse marketplace. I want to create some sort of simple logo that incorporates visual elements from both the Eclipse logo and the Solargraph logo ([this one](http://castwide.com/assets/solargraph-9a5ea85304a1693ba6a875fcc54e7fc9cee894ebce9178eb502cedfb7520b8ee.png)).

Are there any particular license restrictions on the aforementioned Solargraph logo?

Thanks in advance for your response!

Cheers,

Pyves

**Comment by castwide** [comment]
Thanks for the consideration. I think it's reasonable to license the Solargraph logo under [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/), so you have permission to share and adapt it as long as you provide attribution. Any other questions or concerns, just let me know.

**Comment by PyvesB** [comment]
Thank you for your response! I'll keep that it mind, for now I've still got a fair bit of work to make things run smoothly. Will give you a shout when things are ready.
