### ISSUE TITLE
YARD macro in 'class << self' block is defined not in class method but in instance method

### ISSUE THREAD

**Issue by hima2nd** [castwide/solargraph#176]
VSCode : Ruby Solargraph Version 0.19.5
Solargraph Version 0.32.0

Here's example code:

```
class C
  class << self
    # @!attribute [rw] hoge
    # @!parse
    #   def huga(v); end
    # @!method hogehoge(v)
  end
end

C.new.  # <- intellisense hoge, hoge=, huga, hogehoge
```

**Comment by castwide** [comment]
Confirmed. This one is a little tricky, but an upcoming change to the way the mapper handles closures might help.

**Comment by castwide** [comment]
This bug is fixed in the `closure` branch. I expect to release the fix in version 0.33.0. More information: #186

**Comment by castwide** [comment]
Fixed in gem v0.33.0.

**Comment by castwide** [comment]
Version 0.33.1 fixes an additional issue with multiple directives in the same comment block.

**Comment by minkir014** [comment]
Close this issue.

**Comment by hima2nd** [comment]
Thanks!
