### ISSUE TITLE
GemNotFoundException when installed in a local folder

### ISSUE THREAD

**Issue by PyvesB** [castwide/solargraph#177]
Hello,

I'm trying to install Solargraph in a local folder by using the following command:
`gem install solargraph -i .`

Unfortunately, things don't seem to be wired up correctly when I try running the Solargraph executable in the `bin` subfolder. On a Windows operating system:
```
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)
```

On a Fedora system, similar problem:
```
/usr/share/rubygems/rubygems.rb:241:in `bin_path': can't find gem solargraph (>= 0.a) (Gem::GemNotFoundException)
    from bin/solargraph:22:in `<main>'
```

Thanks in advance for your help!

Cheers,

Pyves

**Comment by castwide** [comment]
I don't know if it's supposed to work that way. I tried `gem install opal -i .` and running the opal executable gave me the same error.

**Comment by PyvesB** [comment]
After some further digging, I think you're right, it's probably not supposed to work that way. I was getting confused by the fact that the full option name is `install-dir`. But the `gem install` command help states the following about `-i`:
> Gem repository directory to get installed gems

I'm still unsure what the purpose of this flag actually is if it installs gems that aren't usable.

By using the `gem install solargraph -n .`, I do get a good compromise: working binaries are put into the current local folder, even though the gem itself is installed in the usual place.

Thanks for your time, closing as there's nothing wrong with Solargraph! 😉
