### ISSUE TITLE
wrong bundler version

### ISSUE THREAD

**Issue by dbg1995** [castwide/solargraph#178]
Hello.
when run `gem install solargraph `
My console:
```
Fetching: bundler-2.0.1.gem (100%)
Successfully installed bundler-2.0.1
Fetching: solargraph-0.32.1.gem (100%)
Successfully installed solargraph-0.32.1
Parsing documentation for bundler-2.0.1
Installing ri documentation for bundler-2.0.1
Parsing documentation for solargraph-0.32.1
Installing ri documentation for solargraph-0.32.1
Done installing documentation for bundler, solargraph after 8 seconds
2 gems installed
```  
It has installed installed bundler-2.0.1.
But i using bundler 1.17.1 at this workspace.  so when run `solargraph -v `is a failure.

I do not want to update the bundler version at this workspace. I don't know what else to do, can you help me?

**Comment by unirt** [comment]
I had the same problem after upgrading solargraph to v0.32.1, and solved by downgrading to v0.31.3.
```sh
gem uninstall solargraph
gem install solargraph -v 0.31.3
```

**Comment by dbg1995** [comment]
@unirt  thank you for your help. it worked.
I added `gem "solargraph"` to `gemfile`. After i run `bundle install` and `git checkout -f`.  It has installed ` solargraph -v 0.31.3`
I have discovered  solargraph (= 0.32.1)  is depends on bundler (>= 1.17.2)

**Comment by bk322** [comment]
I updated to bundler 2.0.1, RubyGems 3.0.0, and solargraph 0.32.1 -- but lsp-rename in Emacs still doesn't work. I'm on ruby-2.5.5. Where do I look for a solution?

**Comment by bk322** [comment]
Made it work by switching to bundler 2+, RubyGems 3+:

```bash
source ~/.rvm/scripts/rvm
source ~/.profile

version=2.5.5
rvm install ruby-$version

rvm install ruby-$version
rvm use ruby-$version --default
gem update --system
gem install bundler

find . -name .rvmrc | while read path; do
  cd `dirname $path`
    sed -E "s/ruby-.+/ruby-$version/" -i .rvmrc
    echo "\n" | cd .
    gem install bundler
    bundle update --bundler
    bundle update
  cd -
done
```
