### ISSUE TITLE
Required path could not be resolved with ruby-libvirt

### ISSUE THREAD

**Issue by towo** [castwide/solargraph#179]
When using the `ruby-libvirt` gem, which is required as `libvirt`, solargraph complains that 

```
[Solargraph] [W] Required path libvirt could not be resolved.
```

I'm assuming the reason here is that the file is `/usr/lib/ruby/gems/2.6.0/gems/ruby-libvirt-0.7.0/lib/libvirt.rb`.

**Comment by castwide** [comment]
One simple possibility is missing YARD documentation. Try running `yard gems` to generate and install the yardocs.

Please let me know if you still experience problems. I'm currently unable to install `ruby-libvirt` on my workstation, but I can try with a different machine later.
