### ISSUE TITLE
Unable to run Solargraph: no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by eightbitraptor** [castwide/solargraph#18]
Hi. I'm having some problems using Solargraph. Every time I run anything related to Solargraph from the CLI I'm seeing the above error. First up my Ruby version, solargraph version and yard version is as follows:

I am managing my ruby versions with `chruby` and `ruby-install`

```
[mattvh@hitomi] ~ % ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
[mattvh@hitomi] ~ % gem list | grep solargraph
solargraph (0.15.1)
[mattvh@hitomi] ~ % gem list | grep yard
yard (0.9.12)
```

## Expected Behaviour

When I run `solargraph list-cores` I should see a list of the available documentation versions

## Actual Behaviour

```
[mattvh@hitomi] ~ % solargraph list-cores
/home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map/core_docs.rb:29:in `join': no implicit conversion of nil into String (TypeError)
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map/core_docs.rb:29:in `valid?'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map/core_docs.rb:73:in `yard_stdlib_file'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map.rb:8:in `<class:YardMap>'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map.rb:4:in `<module:Solargraph>'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph/yard_map.rb:3:in `<top (required)>'
        from /home/mattvh/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mattvh/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/lib/solargraph.rb:23:in `<top (required)>'
        from /home/mattvh/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mattvh/.rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/mattvh/.gem/ruby/2.4.2/gems/solargraph-0.15.1/bin/solargraph:3:in `<top (required)>'
        from /home/mattvh/.gem/ruby/2.4.2/bin/solargraph:23:in `load'
        from /home/mattvh/.gem/ruby/2.4.2/bin/solargraph:23:in `<main>'
```

I followed the stack trace through and notice that this bug is stemming from line 8 in `yard_map.rb` that is being run when `YardMap` is autoloaded: `@@stdlib_yardoc = CoreDocs.yard_stdlib_file`

The `yard_stdlib_file` method is erroring when it gets to the `valid?` check because at this point `ver` is `nil` and attempting to `File.join` when one of the arguments is nil fails.

`ver` is nil in this case because this is the first time I've run Solargraph, and my cache directory doesn't exist yet and therefore contains no files.

I notice that the `require_minimum` method is designed to detect this, mkdir the directory and install the minimum documentation, but this is never getting run, because the above call to `yard_stdlib_file` happens when `yard_map.rb` is autoloaded, which happens sooner in the process than the call to `require_minimum` in `lib/solargraph.rb`

Am I doing something wrong or does this sound like a bug?

**Comment by eightbitraptor** [comment]
I don't want to submit this as a PR because I don't think it's the correct solution (and feels a little bit gross) however this quick hack in my gem directory allows me to install and list cores, and start the solargraph server.

I changed `yard_map.rb#8` from 

```
 @@stdlib_yardoc = CoreDocs.yard_stdlib_file
```

to 

```
@@stdlib_yardoc = if !Dir.exist?(CoreDocs.cache_dir) || Dir.empty?(CoreDocs.cache_dir)
  ""
else
  CoreDocs.yard_stdlib_file
end
```

Maybe this will be useful?

**Comment by castwide** [comment]
Good catch. That's close to what I'd recommend. The gem ships with documentation for 2.2.2, so YardMap should be able to find it instead of reverting to an empty string.

This is liable to affect a lot of new users, so I'll fast-track this change in version 0.15.2.

**Comment by castwide** [comment]
Gem 0.15.2 is pushed.

**Comment by eightbitraptor** [comment]
That's fixed it for me! Thanks for the super quick turnaround ❤️ 

```
[mattvh@hitomi] ~ % gem install solargraph --pre
Fetching: solargraph-0.15.2.gem (100%)
Successfully installed solargraph-0.15.2
Building YARD (yri) index for solargraph-0.15.2...
Done installing documentation for solargraph after 0 seconds
1 gem installed
[mattvh@hitomi] ~ % solargraph --version
0.15.2
[mattvh@hitomi] ~ % rm -rf ~/solargraph/cache
[mattvh@hitomi] ~ % solargraph list-cores
2.2.2
[mattvh@hitomi] ~ % solargraph server
[2017-12-05 14:03:40] INFO  WEBrick 1.3.1
[2017-12-05 14:03:40] INFO  ruby 2.4.2 (2017-09-14) [x86_64-linux]
== Sinatra (v2.0.0) has taken the stage on 7657 for development with backup from WEBrick
[2017-12-05 14:03:40] INFO  WEBrick::HTTPServer#start: pid=10646 port=7657
^C== Sinatra has ended his set (crowd applauds)
[2017-12-05 14:03:41] INFO  going to shutdown ...
[2017-12-05 14:03:41] INFO  WEBrick::HTTPServer#start done.
```
