### ISSUE TITLE
Misleading error message when trying to download non existant core file

### ISSUE THREAD

**Issue by erazor-de** [castwide/solargraph#184]
When one tries to download a non existing core file like

    solargraph download-core 2.5.5

The resulting error message is

    .gem/ruby/gems/solargraph-0.32.3/lib/solargraph/yard_map/core_docs.rb:146:in `initialize': not in gzip format (Zlib::GzipFile::Error)

which is misleading and might be improved with a hint at available cores.

**Comment by castwide** [comment]
You can get a list of available cores by running `solargraph available-cores`. If you run `solargraph download-core` without specifying a version, it'll download the closest match to whatever version you're currently running.

Nonetheless, I agree the error message for non-existent cores should be clearer. I'll fix it in an upcoming version.

**Comment by castwide** [comment]
The error message is updated in gem 0.33.0.

```
$ solargraph download-core 2.5.5
Downloading docs for 2.5.5...
ERROR: Version 2.5.5 is not available from https://solargraph.org/download
Run `solargraph available-cores` for a list.
```
