### ISSUE TITLE
problem with install command

### ISSUE THREAD

**Issue by minkir014** [castwide/solargraph#189]
I am on Windows 7 Ultimate. I typed the command `gem install solograph` and it showed this error

![er](https://user-images.githubusercontent.com/42807112/58875772-b6cf4c80-86cc-11e9-8dbc-e3bd35ee58ab.jpeg)

**Comment by castwide** [comment]
The gem name is wrong. `gem install solargraph`

**Comment by minkir014** [comment]
It still shows the same error.

![er](https://user-images.githubusercontent.com/42807112/58879510-20078d80-86d6-11e9-9ba9-e0413483e02a.jpeg)

**Comment by castwide** [comment]
Can you install any other gems? Since you got the same error with solograph, I suspect it's a problem with your local system. Solograph doesn't exist, so it should have given you a "Could not find a valid gem" error.

**Comment by minkir014** [comment]
It seems that the problem isn't with your gem or vs code extension. It's with Ruby itself because I can't install other gems. I'll try to uninstall Ruby and install it again. Thanks for help.
