### ISSUE TITLE
Suggests private methods when not accessible

### ISSUE THREAD

**Issue by AndyBay** [castwide/solargraph#19]
Solargraph currently suggests `private_class_method` methods when they are not accessible.
The function is correctly suggested inside the `self.access_function` method, but it should not be suggested when calling the module itself as below.

Also the documentation part of the suggestions look odd here, though I believe that would be a `vscode-solargraph` issue. The Python extension for example shows no "extended documentation view" in examples like these which could be a solution. Although I must say that I sometimes get confused by that "solution" as I expect an "extended documentation view" and start wondering if there is a problem with the extension until I click `ctrl+space` and see it's intended.

![private_class_method_suggestion](https://user-images.githubusercontent.com/1170184/33608431-c345423c-d9c4-11e7-85c6-761362deb1a0.png)

**Comment by castwide** [comment]
The `private_class_method` limitation is a known issue. Right now the only supported visibility modifiers are `public`, `private`, and `protected`. Support for `private_class_method` and `private_constant` are on the wish list.

I have a feeling VS Code is bugging out when it encounters empty documentation for a recognized code path. I'll look into it.

**Comment by castwide** [comment]
I made a separate issue for the blank documentation bug: https://github.com/castwide/vscode-solargraph/issues/18

**Comment by castwide** [comment]
Support for `private_class_method` is in the master branch. `private_constant` is still pending.

**Comment by castwide** [comment]
Support for `private_constant` is in the master branch.

**Comment by castwide** [comment]
Published in gem v0.15.3.

**Comment by castwide** [comment]
Gem v.0.15.4 fixes some visibility issues for private constants and class methods.
