### ISSUE TITLE
No autocomplete methods inside `class << self` via comments

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#190]
```
require_relative './base'

Mail::Action::Base.pro # <= auto complete works
Mail::Action::Base.process # <= auto complete works

# @type [Mail::Action::Base]
anothervar = param
anothervar.proc # <= autocomplete not works
# or such as
# @param [Mail::Action::Base]
anothervar.each do |p|
  p.proc # <= autocomplete not works
end
```

I'm using `closure` branch which is super-awesome and it is autocomplete in lightning speed.

![2](https://user-images.githubusercontent.com/1711576/59209577-4fc20400-8bb4-11e9-8d7a-bf9cf5be84f0.gif)

Could be related to #176.

Sample: [sample.zip](https://github.com/castwide/solargraph/files/3272869/sample.zip)

**Comment by gencer** [comment]
I see that `closure` merged into `master`. Tested on master and still have the same issue.

**Comment by castwide** [comment]
Your `@type` and `@param` tags declare the type as an instance of `Mail::Action::Base`, so autocomplete suggests instance methods instead of class methods.

If the value is actually supposed to be a reference to the class, you can make the tag `Class<Mail::Action::Base>`:

```ruby
# @type [Class<Mail::Action::Base>]
anothervar = param
anothervar.proc # <= autocomplete works
# or such as
# @param [Class<Mail::Action::Base>]
anothervar.each do |p|
  p.proc # <= autocomplete works
end
```

**Comment by gencer** [comment]
Oh. Got it! Sorry for my mistake. Thank you for the reply.
