### ISSUE TITLE
Request textDocument/foldingRange failed  on each open file in vscode on OSX

### ISSUE THREAD

**Issue by njyrbecker** [castwide/solargraph#193]
Seeing this message pop up in console each time I open a file in vscode.  Either via option-p, or via find in files + click to open, etc.

Request textDocument/foldingRange failed.
  Message: [Solargraph::FileNotFoundError] Host could not find file:///path/to/file

I can confirm that the file URIs it spits out in the errors are actually valid; I can copy them to chrome and open them with chrome without altering them.

solargraph version 0.33.1

.solargraph.yml:
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
plugins: []
require_paths: []
max_files: 0

OSX version: 10.14.5
VSCode: 1.34.0

**Comment by castwide** [comment]
Are the files you're trying to open outside of the workspace or in an excluded directory like `test`?

Do you get any error messages or a stack trace in the developer console (Help -> Toggle Developer Tools)?

**Comment by njyrbecker** [comment]
Going to close this out, as a second restart of vscode made it go away.  It started after updating the gem and telling vscode to restart the solargraph server, persisted through one restart of vscode, but when I restarted a second time, it went away., and now does not seem to reproduce.

To answer the questions, the files were within the workplace, and  not in an excluded directory.
