### ISSUE TITLE
Global configuration support

### ISSUE THREAD

**Issue by taylorthurlow** [castwide/solargraph#197]
Is there any chance we could get support for a global config at `~/.config/solargraph/config.yml` or something similar? Overridden by the project configuration obviously.

**Comment by castwide** [comment]
Good idea. I'll add it to the roadmap.

I might not get to this for a while, so if anyone wants to submit a PR, just let me know and I'll assign it. I don't expect it to be too difficult, but my plate is crazy full.

**Comment by castwide** [comment]
This is released in v0.35.0. The default location for the global config is `~/.config/solargraph/config.yml`, and it can be changed with the `SOLARGRAPH_GLOBAL_CONFIG` environment variable.

**Comment by nomasprime** [comment]
@castwide great, thanks.

Does this merge with existing defaults or do we need to specify defaults? Personally I'd prefer merge but if not, where do we find the existing defaults?

**Comment by nomasprime** [comment]
@castwide great, thanks.

Looks like defaults overwrite built-in defaults. What's the best way of finding out existing defaults, is it [this](https://solargraph.org/guides/configuration)?

**Comment by castwide** [comment]
@nomasprime Yes, when you use `solargraph config` to generate the file, it starts with everything set to the built-in defaults.
