### ISSUE TITLE
external gem names

### ISSUE THREAD

**Issue by guskovd** [castwide/solargraph#20]
Solargraph does not work correctly if the library name does not match the gem name.

for example, in my test.rb:
```ruby
require 'kitchen'
Ki
```
in my Gemfile:
```ruby
source 'http://rubygems.org'

gem 'test-kitchen'
gem 'solargraph'
```

when i call:
```bash
solargraph suggest test.rb --line 1 --column 1
```
getting an error:
```bash
Required path not found: kitchen
```

**Comment by castwide** [comment]
In the latest version of the master branch, paths that resolve to any file inside a gem should add the corresponding YARD documentation to the YardMap.

**Comment by guskovd** [comment]
In my case, it works correctly. Awesome!
