### ISSUE TITLE
Tab-completing a symbol drops the colon prefix

### ISSUE THREAD

**Issue by taylorthurlow** [castwide/solargraph#200]
Consider this short code example:

~~~ruby
something = {}
something[:key] = "some value"
~~~

In a new line, typing `something[:k` will begin auto-suggest like so:

![Screen Shot 2019-06-21 at 8 46 55 PM](https://user-images.githubusercontent.com/761640/59959123-ebc9f600-9465-11e9-828b-a119cb7f286d.png)

Accepting this auto-complete, in my case with TAB, produces this:

~~~ruby
something = {}
something[:key] = "some value"

something[key]
~~~

Notice the lack of a colon in `[key]` - I expect `[:key]`.

**Comment by castwide** [comment]
What editor are you using?

**Comment by taylorthurlow** [comment]
Wow sorry I left that out. Solargraph 0.33.2 and the latest stable release of Sublime Text 3. I'm using the LSP package which is preconfigured for solargraph.

**Comment by castwide** [comment]
Thanks. This might be specific to Sublime Text. I wasn't able to reproduce it in VS Code or Atom.

**Comment by taylorthurlow** [comment]
Alright I'll do some investigating.

**Comment by taylorthurlow** [comment]
I've determined that the issue is related to LSP. I've opened [an issue](https://github.com/tomv564/LSP/issues/623) and a [pull request](https://github.com/tomv564/LSP/pull/624) which fixes the issue.
