### ISSUE TITLE
standard library requires

### ISSUE THREAD

**Issue by guskovd** [castwide/solargraph#21]
in my test_date.rb:
```ruby
require 'date'
D
```

when i call
```bash
solargraph suggest test_date.rb --line 1 --column 1
```
getting:
```
Required path not found: date
{"status":"ok","suggestions":[{"label":"Data","kind":"Class","insert":"Data","detail":"Data","path":"Data","location":null,"arguments":[],"params":[],"return_type":"Class<Data>","has_doc":true},{"label":"Dir","kind":"Class","insert":"Di
r","detail":"Dir","path":"Dir","location":null,"arguments":[],"params":[],"return_type":"Class<Dir>","has_doc":true}]}
```
I expect to see DateTime in json, but there it is not

**Comment by castwide** [comment]
Standard library support is a work in progress. It's a priority, but it's not an easy problem to solve without impacting accuracy, performance, or both.

**Comment by castwide** [comment]
Gem version 0.21 includes some significant improvements to stdlib library support. `require 'date'` exposes the Date and DateTime classes as expected.

**Comment by guskovd** [comment]
awesome!

**Comment by castwide** [comment]
Requires from the standard library should mostly work now. There's a known issue with `json` reported in #72. If anyone runs into other problems, please open a new issue.
