### ISSUE TITLE
ignore folder solargraph

### ISSUE THREAD

**Issue by tvallois** [castwide/solargraph#213]
Hi,

I don't know if it's an issue related to Atom or Solargraph directly but i've a folder in my rails app called client where i would like to ignore from solargraph point of view. I've added this configuration in my solargraph.yml but still there are a lot of operations on it which make solargraph unable.

My .solargraph.yml : 
```yml
include:
- "**/*.rb"
exclude:
- client/**/*
```

Message from atom : Ruby (Ruby Solargraph) stderr [DEBUG] {"jsonrpc"=>"2.0", "method"=>"workspace/didChangeWatchedFiles", "params"=>{"changes"=>[{"uri"=>"file:///home/tvallois/web/client/node_modules/eslint/node_modules/lodash/fp/set.js", "type"=>1}, {"uri"=>"file:///home/tvallois/web/client/node_modules/eslint/node_modules/lodash/fp/set.js", "type"=>2}, ...}

**Comment by tvallois** [comment]
Seems to be an Atom issue. More info here https://github.com/atom/atom-languageclient/issues/232

**Comment by castwide** [comment]
I think so, yes. The language client is responsible for monitoring the filesystem. The configuration can only tell the server to ignore the changes after the message has already been sent.

According to that issue, I might be able to filter the watched files in the extension. I'll look into it.

Also related: https://github.com/castwide/atom-solargraph/issues/15

**Comment by tvallois** [comment]
I can make the PR if you want. Seems to be an easy fix.

**Comment by castwide** [comment]
Thanks, I'd appreciate it. Once it's done, I'll also publish a new version ASAP. The Atom extension is overdue for an update.
