### ISSUE TITLE
invalid typecheck for unused arguments

### ISSUE THREAD

**Issue by lifeiscontent** [castwide/solargraph#215]
given the following code:

```
class Types::Date < Types::BaseScalar
  description 'ISO 8601 Date'

  # Coerces the value to a Date.
  #
  # @param value [String]
  # @param _ctx [GraphQL::Query::Context::FieldResolutionContext]
  # @raise [GraphQL::CoercionError] invalid Date
  # @return [Date]
  def self.coerce_input(value, _ctx)
    date = Date.parse(value)
    return date if date.is_a?(Date)

    raise GraphQL::CoercionError, "#{value.inspect} is not a valid Date"
  end

  # Coerces the value to a String.
  #
  # @param value [Date]
  # @param _ctx [GraphQL::Query::Context::FieldResolutionContext]
  # @return [String]
  def self.coerce_result(value, _ctx)
    value.iso8601
  end
end
```

I've tried to type the `_ctx` param however solargraph is still saying _ctx is not typed.

**Comment by castwide** [comment]
It worked for me in VS Code:

![image](https://user-images.githubusercontent.com/3704922/62310391-6a4b8780-b457-11e9-9ecb-71455f9ec386.png)

A couple things to note:

1. Typing `_` alone did not trigger autocomplete.
2. Do you have YARD documentation for graphql? If not (or you're not sure), you can generate it by running `yard gems`.

**Comment by lifeiscontent** [comment]
Oh, good point. I’ll try it tomorrow and report back. Thanks @castwide 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lifeiscontent** [comment]
@castwide just did what you suggested. It works. Thank you!
