### ISSUE TITLE
Missing Documentation Methods?

### ISSUE THREAD

**Issue by jcat4** [castwide/solargraph#216]
Hello!

I don't know if I'm just using this wrong, but the docs aren't pulling some methods that I know exist on some classes... An example is Array.sum. I don't see it in the Solargraph docs (pulled through VS Code extension), but I've definitely used sum on arrays, and other sites such as [this one ](https://ruby-doc.org/core-2.4.1/Array.html#method-i-sum)confirm its existence. I've already done a `solargraph download-core`, and nothing changed.

Am I just not using this correctly? 😅

**Comment by castwide** [comment]
What version of Ruby are you running? `Array#sum` was introduced in 2.4.

I confirmed I could see it using 2.5.3:

![image](https://user-images.githubusercontent.com/3704922/62336789-f4b7d980-b49f-11e9-8f52-fb5cb9db2b2e.png)

**Comment by jcat4** [comment]
Quick again 😯Terminal shows 2.6, but idk if that's what VS Code is using ☹️ I'm fairly new to this. The settings command path for ruby hasn't been touched, it's just "ruby", soooo I'd _imagine_ it's just using 2.6 like the terminal.

**Comment by castwide** [comment]
You caught me at my desk :)

If you're using VS Code, you can check by running "Solargraph: Get environment info" from the command palette. It'll tell you the Ruby version it's running and the core documentation version, among other things.

If you're using rvm or rbenv, Solargraph should use it to select the configured Ruby version. In that case, the version in the integrated terminal might be different. (At one point, the terminal would also start with the managed version. It still works for me on MacOS, but stopped working on CentOS. Weird.)

**Comment by jcat4** [comment]
**System**

- Platform: x86_64-darwin18
- Shell: /bin/zsh
- Ruby Version: 2.6.2
- RuboCop Version: 0.67.2

**Solargraph**

- Solargraph Version: 0.35.1
- Core Documentation Version: 2.6.1
- Core Cache Directory: /Users/joey/.solargraph/cache
- Parser Target Version: 26
- Using Bundler: false

Looks like it's not using rvm, and is indeed using 2.6.2 :/

**Comment by jcat4** [comment]
I restart vs code and it worked. Idk what is wrong with me or my machine.
