### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#219]
Ruby Language Server sections shows:

```
[Error - 02:26:17] Connection to server is erroring. Shutting down server.
```

and `ruby.exe` hangs on task manager. Loading indicator in VSCode keep going but server is not up anymore so no intellisense. I've opened diagnostics and set it to `debug` but don't see any message other than above...

This behavior happens immediately I open VSCode and solargraph extension gets activated.

**Comment by gencer** [comment]
Yup. Found the root issue. VPN. I've a VPN installed and VSCode is excluded. Ruby starts on VPN-network and VSCode starts on local network. Do the math :)

Solved by excluding ruby.exe

**Comment by castwide** [comment]
It might be a problem with using the socket transport over TCP/IP. You can try setting `solargraph.transport` to `stdio`. (`socket` is the default because it historically had better performance, but I think they're a lot closer to even now.)

**Comment by gencer** [comment]
Thanks, Fred. It worked!

Closing.
