### ISSUE TITLE
jump to definition api

### ISSUE THREAD

**Issue by guskovd** [castwide/solargraph#22]
Are there any plans to release api to go to the definition?

Similarly to how it is done in the python project jedi:
https://github.com/davidhalter/jedi

**Comment by castwide** [comment]
Yes. Coincidentally, I was researching this feature in the past few days. I hope to support class/module/method definitions, variable assignments, and some externals (i.e., definitions from scripts outside the current workspace).

**Comment by castwide** [comment]
There's a new `go-to-def` branch that has experimental support for this feature. The server provides a POST /define endpoint that takes the same parameters as POST /suggest. If the line/column position points to a method call, it responds with matching method suggestions. If it points to a variable, it responds with matching variable assignments. Suggestions have a `location` property that points to the definition in the form of `/path/to/file:line:column`, e.g., `/project/app.rb:10:2`.

This feature's likely to change before release, but I hope to include it in gem version 0.17.0. Suggestions and feedback are always welcome.

**Comment by castwide** [comment]
This feature is definitely going into version 0.17.0, so I merged it into the master branch.

**Comment by castwide** [comment]
Published version 0.17.0. The repo contains partial documentation for the web API endpoints: https://github.com/castwide/solargraph/blob/master/SERVER.md

**Comment by guskovd** [comment]
It does not work for me

in my source.rb
```ruby
require 'solargraph'
Solargraph
```
in test_define.rb
```ruby
require 'rest-client'

puts RestClient.post(
  'http://localhost:7657/define',
  'text': File.read('./source.rb'),
  'filename': File.expand_path('./source.rb'),
  'line': '1',
  'column': '0'
)
```
ruby ruby test_define.rb```bash

```

It does not work for me

in my source.rb
```ruby
require 'solargraph'
Solargraph
```
in test_define.rb
```ruby
require 'rest-client'

puts RestClient.post(
  'http://localhost:7657/define',
  'text': File.read('./source.rb'),
  'filename': File.expand_path('./source.rb'),
  'line': '1',
  'column': '0'
)
```

```bash
ruby test_define.rb
```
output
```bash
{"status":"ok","suggestions":[{"label":"Solargraph","kind":"Module","insert":"Solargraph","detail":"Solargraph","path":"Solargraph","location":null,"arguments":[],"params":[],"return_type":null,"has_doc":false}]}
```

**Comment by castwide** [comment]
@guskovd This version only works with files in the current workspace. It also needs to `prepare` the workspace before it can locate the other files.

All files in the same directory:

```ruby
#foo.rb
class Foo
end
```

```ruby
# source.rb
Foo
```

```ruby
# test_define.rb
require 'rest-client'

puts RestClient.post(
  'http://localhost:7657/prepare',
  'workspace': File.expand_path('.')
)

# Wait a moment after the first prepare. Subsequent requests should not need to wait.
sleep(1)

puts RestClient.post(
  'http://localhost:7657/define',
  'text': File.read('./source.rb'),
  'filename': File.expand_path('./source.rb'),
  'line': '0',
  'column': '0',
  'workspace': File.expand_path('.')
)
```

output:
```
{"status":"ok","suggestions":[{"label":"Foo","kind":"Class","insert":"Foo","detail":"","path":"Foo","location":"/path/to/define-test/foo.rb:0:0","arguments":[],"params":[],"return_type":"Class<Foo>","has_doc":false}]}
```

Support for locating files from required gems is on the roadmap. The line number and the path relative to the gem are available through YARD, but Solargraph needs to resolve the absolute path.

**Comment by guskovd** [comment]
thanks, it seems like it works
But sleep ... Maybe the server will only respond when the workspace is ready?

**Comment by castwide** [comment]
Historically it made sense for `/prepare` to return immediately because it could take a while on large workspaces. The [rails](https://github.com/rails/rails) project, for example, took 30 to 45 seconds. Waiting for it to finish could impact performance on the editor making use of it. This way, instead of freezing the UI, `/suggest` or `/define` respond with incomplete results while the workspace is still being prepared.

I'm open to discussing other solutions, though. Preparation time might not be as much of an issue now, given more efficient ApiMap processes; or there might be other ways to mitigate it. Either way it's worth investigating.

**Comment by castwide** [comment]
The latest version in the master branch has the first version of symbol definition in required gems.

**Comment by adityaU** [comment]
Can I require Gems from Gemfile for this feature?

**Comment by castwide** [comment]
@adityaU Yes, with some caveats.

Solargraph requires YARD documentation for external gems. You can generate it by running `yard gems`.

The required gems need to be accessible from the process that runs the server. (The server doesn't need to load them, but it needs to be able to find them.) In most scenarios, if the gem is installed on the system, you should be able to get results for it in the language server.
