### ISSUE TITLE
No signature being returned from solargraph

### ISSUE THREAD

**Issue by sethen** [castwide/solargraph#220]
I am using coc-solargraph in vim and trying to get signature help when typing out a method.  Solargraph for whatever reason is not returning any signatures.  Here's a screenshot:

![Screenshot from 2019-08-10 23-36-08](https://user-images.githubusercontent.com/1493530/62829252-b751fb00-bbc7-11e9-9f03-3a56717c0394.png)

Currently using RVM on Ruby 2.6.0 and Solargraph 0.35.2.  It looks like it's passing the correct thing to Solargraph here.  Any thoughts?

**Comment by castwide** [comment]
The problem might be that the parenthesis isn't closed. Try entering this:

```ruby
[].assoc()
```

Then move the cursor inside the parentheses and trigger signature help.

If that works, I might be able to make the server detect and "repair" unclosed parentheses. There are already similar repairs to make the parser ignore syntax errors that can occur during active editing.

**Comment by sethen** [comment]
That was indeed the issue as I figured out.  I need to install `coc-pairs` for it to work correctly.  It closed the parens and moved the cursor to the center triggering the signature help.

Thanks for the reply!

**Comment by nomasprime** [comment]
@castwide repairing unclosed would be great. Currently can't get signature help without an autoclose plug-in.
