### ISSUE TITLE
can't infer of pathname.join

### ISSUE THREAD

**Issue by SolaWing** [castwide/solargraph#226]
demo:

```
require 'pathname'

a = Pathname.new
b = a.join('xxx')
b. # <-- no tip here
```

already upgrade to newest master

**Comment by castwide** [comment]
The `Pathname#join` return type isn't defined in the source code. That's a common problem with stdlib methods. I'm working on a mechanism to fill some of those gaps. A similar mechanism already exists for the Ruby core; for example, Solargraph inserts the `String` return type for `File.dirname`.

**Comment by castwide** [comment]
The `master` branch includes support for improving stdlib coverage with overrides. The current version enhances `Pathname` to provide return types for `Pathname#join` and several other methods.

I expect to include this feature in the next release.

**Comment by castwide** [comment]
Releasec in v0.38.3.
