### ISSUE TITLE
0.37.2 broke documentation highlighting

### ISSUE THREAD

**Issue by AlanWarren** [castwide/solargraph#227]
Hello,

I see the commit for 0.37.2 https://github.com/castwide/solargraph/commit/d633cb2c900ef855230a6bfd5360b3239cb431b4  removed markdown conversion for the documentation. 

This breaks the documentation highlighting for vim/neovim, as there's no longer any descriptive delimiter for when code starts / stops.  

example output. 
```json
"documentation": {
    "kind": "markdown",
    "value": "[ActiveModel::Validations#errors](solargraph:/document?query=ActiveModel::Validations%23errors)\n\nReturns the +Errors+ object that holds all information about attribute\nerror messages.\n\n    class Person\n      include ActiveModel::Validations\n\n    attr_accessor :name\n    validates_presence_of :name\n    end\n\n    person = Person.new\n    person.valid? # => false\n    person.errors # => #<ActiveModel::Errors:0x007fe603816640 @messages={name:[\"can't be blank\"]}>"
}
```
And the following shows the lack of highlighting. 
![Screen Shot 2019-09-11 at 12 07 38 PM](https://user-images.githubusercontent.com/294606/64789655-658bf000-d53a-11e9-8e52-6231ce93e8cf.png)

Screenshot of 0.37.1's documentation in a floating window
![Screen Shot 2019-09-11 at 11 39 30 AM](https://user-images.githubusercontent.com/294606/64789699-78062980-d53a-11e9-8e1b-2775d9e9a161.png)

Is it possible to get a descriptive code block, or the previous markdown bactic's back again?  

Thanks

**Comment by castwide** [comment]
Markdown conversion is coming back. Examples like the one you provided are why it's a little tricky. It's common for code blocks in Ruby documentation to be formatted with two-space indentation, which is not conventional in Markdown. I had to modify documentation rendering to identify the non-standard code blocks and convert them into Markdown while retaining the correct formatting for the rest of the text.

The new conversion routine is currently in the `master` branch.

**Comment by AlanWarren** [comment]
Thanks, I'm testing out master.  Code blocks are highlighted as ruby syntax again, so it's looking much better. 

The only thing I'm noticing is a few <tt> and <em> tags.   

Closing this ticket, since the noted issue is resolved.
