### ISSUE TITLE
Multiple vim will start multiple solargraphs

### ISSUE THREAD

**Issue by yantene** [castwide/solargraph#229]
I use solargraph through LanguageClient-neovim.

When I open Ruby files in the same project with multiple vim, multiple solargraphs will start.
It uses a lot of memory.
I only need one solargraph process.

Is there a solution?

**Comment by ismk** [comment]
Is there any update to this? ☝️

**Comment by castwide** [comment]
This is almost certainly an issue with the client, but if there are any ways that the server can be more helpful, please feel free to start a new issue.
