### ISSUE TITLE
Add to the documentation information about plug-ins for editors

### ISSUE THREAD

**Issue by guskovd** [castwide/solargraph#23]
For Vim users found this:
https://github.com/hackhowtofaq/vim-solargraph

I'm an emacs user, but after seeing how it's done in Vim, I wrote my plug-in easily. 
https://github.com/guskovd/emacs-solargraph
Implemented basic support for solargraph. I already use it myself!

The solargraph project is really wonderful. I would like users of various text editors to know more about it.

On the one hand, I ask to PR myself. But on the other hand, if someone, after looking at my code, decides to do better, I will be only happy.

**Comment by castwide** [comment]
Awesome, thanks for sharing. I'll be happy to add a list of plug-ins to the README. More documentation for the server API, etc. is also on the roadmap. Assistance is always appreciated.
