### ISSUE TITLE
Integrate with static analysis tools(Reek, rails_best_practices)

### ISSUE THREAD

**Issue by dansdantas** [castwide/solargraph#230]
I don't know if this is the right place to ask but, is there any way to use Reek as a reporter? 

I tried to  configure simply like rubocop but i got a error(Diagnostics reporter reek does not exist).

I don't even know if reek should be a reporter or if i am doing something wrong. I'd like to integrate with other static analysis tools. Is that a thing?

**Comment by castwide** [comment]
Solargraph doesn't have a Reek reporter, but it should be possible to make one. It probably wouldn't be very different from the RuboCop reporter.

I'm working on a plugin architecture for extended features. A Reek reporter seems like a good thing to implement as a plugin.

**Comment by dansdantas** [comment]
That's awesome to hear it. Waiting forward!

**Comment by Morozzzko** [comment]
Oh, a plugin would be nice though. What's the progress with this? I'd like to have a reek reporter and would gladly contribute to that. I can wait for a plugin system if it comes within the next couple of months, though.

**Comment by castwide** [comment]
@Morozzzko As mentioned in #307, a plugin system is being introduced in v0.39.0. The current iteration is in the `v0.39` branch.

**Comment by castwide** [comment]
Plugin support is released in gem v0.39.0, along with the first version of the [solargraph-reek plugin](https://github.com/castwide/solargraph-reek).

More information about plugins: https://solargraph.org/guides/plugins
