### ISSUE TITLE
Add support for standardrb

### ISSUE THREAD

**Issue by mikehale** [castwide/solargraph#235]
[Standardrb](https://github.com/testdouble/standard) is essentially RuboCop configured out of the box. This is useful for teams that do not want to spend time fiddling with rubocop config files.

**Comment by castwide** [comment]
We should be able to implement a Standardrb reporter as an extension, as I mentioned in a similar issue regarding support for Reek (#230). I'll look into it.

**Comment by bekicot** [comment]
You can use 
https://github.com/bekicot/solargraph-standardrb

**Comment by castwide** [comment]
Closing this issue as a working version of solargraph-standardrb is released. You can refer to #307 for progress on custom formatters in plugins.
