### ISSUE TITLE
Rubocop not found

### ISSUE THREAD

**Issue by PyvesB** [castwide/solargraph#237]
Hello, hello!

When running the formatter within Eclipse, I'm consistently seeing the following error (both on Windows and macOS):
````
[WARN] Error processing request: [Errno::ENOENT] No such file or directory - rubocop -a -f fi -s XXX
````
The associated stacktrace point to the following line of code:
https://github.com/castwide/solargraph/blob/7e4ba6a43364ddfd5752956ab18f57b34db8d79c/lib/solargraph/language_server/message/text_document/formatting.rb#L16

Basically Rubocop is called by executing a command in a shell.

This is problematic for two different reasons in my use case:
* even though Rubocop is a dependency of Solargraph, my Eclipse plugin installs all executables in a local folder owned by the plugin (see #177). This avoids adding executables to the user's path as a side-effect of installing the plugin and allows things to be nicely cleaned up when the plugin in uninstalled. Consequently, if the user had not previously installed Rubocop, it will not be available globally.
* even if Rubocop was installed by the user independently of Solargraph, it will likely not be available in the IDE's environement. For example, macOS users often manage their path through their _.profile_, _.bash_profile_ or _.bashrc_, and that's where all gems are added to the PATH. When Eclipse is launched as a standard macOS application, it doesn't pick up any of the values in these files and doesn't know about any gems (apart from Solargraph, which my plugin has installed locally and controls).

To sum things up: I don't think Solargraph should assume that the `rubocop` command is available in the environment it's running in.

Could Solargraph integrate with the Rubocop API rather than executing shell commands?

Alternatively, an approach which would cover my second point is to execute the Rubocop command in a login shell ([this post](https://unix.stackexchange.com/a/46856) is quite helpful in explaining some of these concepts) so that it picks up the user's environment properly. On Windows, this would be
`"cmd.exe /c 'rubocop -a -f fi -s #{Shellwords.escape(filename)}'"`. On macOS/Linux, `"/bin/bash -c -l 'rubocop -a -f fi -s #{Shellwords.escape(filename)}'"` does the trick. I'm happy to contribute this workaround if you don't think the Rubocop API is a viable alternative.

What are your thoughts?

Cheers,

Pyves

**Comment by castwide** [comment]
It should be possible to use the RuboCop API for the formatting command. The [RuboCop diagnostics reporter](https://github.com/castwide/solargraph/blob/master/lib/solargraph/diagnostics/rubocop.rb) already works that way.

Your alternative workaround is also possible. The [solargraph-utils](https://github.com/castwide/solargraph-utils) package uses a similar mechanism to detect the correct Ruby environment on systems using a version manager (e.g., rvm or rbenv).

Between the two, I would prefer to use the API. I think it would be faster and less fragile.

I'll look further into this, but given my current workload, I can't provide an ETA yet. Please feel free to submit a PR if you feel like this is something you could tackle.

**Comment by PyvesB** [comment]
The linked pull request was merged and formatting works as expected in version 0.38.0, therefore closing this issue!
