### ISSUE TITLE
Return type during type inference is incorrect

### ISSUE THREAD

**Issue by hpapaxen** [castwide/solargraph#240]
Hello, I'm running into an issue where the type returned from `indent` in wiki_helper.rb:30 returns `Redmine::CoreExtensions::String` instead of `String`. Example code is in [issue.zip](https://github.com/castwide/solargraph/files/3778711/issue.zip). Any help would be appreciated. Thanks.

**Comment by castwide** [comment]
Confirmed. It's a trivial problem with how type inference works for literal values. I'll have it fixed in the next release.

**Comment by hpapaxen** [comment]
Awesome thanks!

**Comment by castwide** [comment]
Version 0.38.0 fully qualifies types for literal values.

**Comment by castwide** [comment]
This should be fixed in 0.38.0. If the problem persists, please let me know.
