### ISSUE TITLE
Solargraph not supporting rubocop version prior to 0.52

### ISSUE THREAD

**Issue by kaymach** [castwide/solargraph#241]
Hello. My problem is probably odd. I've scoured the internet trying to find a workaround for this to no avail.

I need to use version 0.46.0 of rubocop in order to go through schooling, but solargraph requires >0.52.0. I don't want to have to go about switching gem versions with rbenv. My ideal setup is to have solargraph use the latest rubocop version for dependency sake whenever I launch vscode and to keep using rubocop .46 everywhere else in the IDE environment without having to think about it, even while vscode is still open.

Is this possible?

**Comment by castwide** [comment]
I'm afraid it's not practical to reduce the minimum RuboCop dependency. The diagnosis and formatting capabilities depend on features that either changed significantly or did not exist in 0.46.0.
