### ISSUE TITLE
Install problem on Mac: Suggestion

### ISSUE THREAD

**Issue by jgclark** [castwide/solargraph#248]
(Edited)
I'm sorry this is probably really basic, but I couldn't get the first step of installation to work.
`gem install solargraph` gives errors:
```
ERROR:  Error installing solargraph:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20191126-8244-132ryat.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.
```

More googling around and trying other things means I've now fixed it. But for the benefit of others, could you improve the documentation, adding that (for macOS) `xcode-select --install` is required? Then the slightly unhelpful error message shouldn't become a problem. Thanks.

**Comment by castwide** [comment]
Documenting this issue is a good idea. It isn't specific to Solargraph, but it comes up often enough to have a FAQ entry, at least.

Related: https://github.com/castwide/vscode-solargraph/issues/78

**Comment by kirichkov** [comment]
Actually, after upgrading to Mojave, `xcode-select --install` didn't help. Apparently Apple stopped shipping (some of) the C header files for ruby, and split them in a separate package. To resolve this you'd also need to install them:

```bash
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

On Catalina I presume (not confirmed) you'd need:

```bash
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.pkg
```

**Comment by castwide** [comment]
Documented in the [troubleshooting FAQ](https://solargraph.org/guides/troubleshooting) with brief instructions and a link back to GitHub.
