### ISSUE TITLE
How are newline and comment characters handled?

### ISSUE THREAD

**Issue by patilarpith** [castwide/solargraph#25]
Eg: 

These are the params I'm testing with:
```
text=## Some comments \n## Some more comments \nreq&line=2&column=2
```

Response I see is invalid offset

**Comment by castwide** [comment]
Those params look valid. How are you sending the request?

**Comment by patilarpith** [comment]
@castwide I was trying it out from chrome REST client
<img width="694" alt="screen shot 2018-02-13 at 1 17 29 pm" src="https://user-images.githubusercontent.com/1260939/36138691-6557d968-10c0-11e8-92cd-8191a44ce619.png">

**Comment by castwide** [comment]
I'm not familiar with that tool, but it looks like the payload isn't encoded properly. I was able to get a successful response using YARC!, with Content-Type `application/x-www-form-urlencoded` and the following payload:

```
text=## Some comments%0A## Some more comment%0Areq&line=2&column=2
```

Note that newlines are encoded as `%0A` instead of `\n`.

**Comment by patilarpith** [comment]
Thank you. 
Encountered something different. I guess dot followed by newline is causing an issue.  Empty array in returned.
Eg: 
```
text=## Anything you type or change here will be seen by the other person in real time.%0Arequi&line=1&column=5
```
Removing the period from the comment makes it work fine

**Comment by castwide** [comment]
Confirmed. I'll have a fix for that in the next version.

**Comment by castwide** [comment]
Fixed in the master branch.

**Comment by patilarpith** [comment]
Confirmed its working on v0.17.2. Thank you
