### ISSUE TITLE
Auto-completion without require statements

### ISSUE THREAD

**Issue by taylorthurlow** [castwide/solargraph#250]
My current understanding of auto-completion is that Solargraph uses the require statements from the file being edited to determine which classes and libraries can be auto completed. This works fine, but libraries being used aren't necessarily always required in the file, in my case, for two reasons:

1) Most of my projects are using [`zeitwerk`](https://github.com/fxn/zeitwerk), which does code auto-loading - no need for require statements anywhere
2) Bundler require (`Bundler.require(:default, app_env)`)

Is this something I can fix with a setting? Is this restriction in place due to performance concerns?

Thanks!

**Comment by castwide** [comment]
I don't know about Zeitwerk, but if your code includes either `Bundler.require` or `require 'bundler/require'`, Solargraph should automatically add all of your bundled gems to the map.

If you want to map all your gems but don't actually want to run `Bundler.require` in your application, one workaround is to add a YARD `@!parse` directive:

```ruby
# @!parse Bundler.require
```

**Comment by taylorthurlow** [comment]
It must be related to where the `Bundler.require` statement is located. This particular project is a service with a ruby code binstub located at a path like `bin/my_application`. I guess the fact that there's no `.rb` extension is why this is happening. I'll check on that and report back. Thanks!

**Comment by jfedgar** [comment]
@taylorthurlow Did you ever come up with any solutions for Zeitwerk?

I'm having trouble getting it to give auto-completion for codes within my project.

I have tried adding a .solargraph.yml file and adding my project directories to the 'require_paths' to no avail.

**Comment by jfedgar** [comment]
Nevermind, ha.

It seems when you define a class this way:

```
class Foo::Bar
   # @param [String] param1
   def self.my_function(param1)
      #whatev
   end
end
```

Solargraph seems to have trouble with it (?).

When I changed it to:

```
module Foo
    class Bar
    end
end
```

It worked.

🤷 

Zeitwerk appears to work just fine with Solargraph (so far)

**Comment by taylorthurlow** [comment]
Yeah, if I'm not mistaken, Solargraph will have issues with implicitly defined modules. I'm not actually 100% sure though. 👍

**Comment by castwide** [comment]
Implicitly defined modules don't work, but compact namespaces work as long as each symbol is defined.

```ruby
module Foo; end

class Foo::Bar
  def self.my_method; end
end

Foo::Bar.my_method # works
```
