### ISSUE TITLE
Undefined return type

### ISSUE THREAD

**Issue by tcd** [castwide/solargraph#251]
So typecheck is saying that `Array<Hash<Symbol>>` (An array of hashes with symbol keys) isn't a valid type, but it does get parsed by Yard's [type parser gui](https://yardoc.org/types).

I'm guessing the issue has to do with the [`UniqueType`](https://github.com/castwide/solargraph/blob/b3191423cff51c9ea5ad052ce06cff3a08abb04b/lib/solargraph/complex_type/unique_type.rb#L8) class.
Is this just an expression that it doesn't parse properly or is it actually invalid?

```ruby
    # Read a TSV file and return its contents as an array of hashes.
    #
    # @param filepath [String] Path to the TSV file.
    # @return [Array<Hash<Symbol>>]
    def self.parse_tsv(filepath)
      return CSV.read(
        filepath,
        col_sep: "\t",
        headers: true,
        quote_char: "\x00",
        header_converters: :string,
      ).map(&:to_hash)
    end
```

![error message](https://user-images.githubusercontent.com/51792731/70812392-26657900-1d8d-11ea-898f-f6d9ee7450d2.png)

**Comment by castwide** [comment]
I'm not sure if that should be valid or not. Solargraph expects hashes to be annotated with a key/value pair, e.g., `Hash{String => Symbol}`. In your example, something like `Array<Hash{String => Symbol}>` works. In the case of `Hash<Symbol>`, I can't tell whether `Symbol` should refer to the type of the key, the value, or both.

**Comment by tcd** [comment]
I use `Hash<Symbol>` and `Hash<String>` pretty frequently to specify a specific key type when working outside of Rails and without `HashWithIndifferentAccess`. 
But I probably should be giving explicit value types (as in `Hash{Symbol => Object}`).

So I suppose this is a different question, but if `[Array<Hash{Symbol => Object}>]` is valid, would `[Array<Hash<Symbol, Object>>]` be too?

**Comment by castwide** [comment]
I would definitely prefer `Hash{Symbol => Object}` over `Hash<Symbol, Object>`. It's more explicit and follows the current YARD specification. I can't say for sure if the latter is even a valid alternative; we should probably get @lsegal's input on that.
