### ISSUE TITLE
Add SOLARGRAPH_CACHE to the Readme

### ISSUE THREAD

**Issue by quintrino** [castwide/solargraph#255]
Currently the code allows you to specific a custom location for the cache files (which I was looking to do for XDG ) but doesn't actually mention it anywhere in the readme. 

It would help people take advantage of it as a cool feature. I only stumbled across it while looking at where the gem actually specified the home directory for the cache file.

**Comment by castwide** [comment]
Good call. I added it to the README and specifically mentioned XDG, since that's what inspired the feature in the first place.
