### ISSUE TITLE
Is using the macro tag to dynamically define methods supported?

### ISSUE THREAD

**Issue by thornomad** [castwide/solargraph#256]
I see some references to using the `!@macro` tag in the source code, but I can't see to get it to do what I want when it comes to defining a `@method` on the fly.  Taking a look at a basic example [from the docs at Yard.](https://rubydoc.info/gems/yard/file/docs/Tags.md#macro)

```ruby
class Resource
  # Defines a new property
  # @param [String] name the property name
  # @param [Class] type the property's type
  # @!macro [attach] property
  #   @return [$2] the $1 property
  def self.property(name, type) end
end

class Post < Resource
  property :title, String
  property :view_count, Integer
end
```
When I test this, it seems to misinterpret the macro return for the class method `.property` ... instead of actually getting the method definition "Defines a new property" I am seeing the macro output:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/124717/71606919-edb5f580-2b29-11ea-8753-2ed770b5e6ef.png">

And the server can't find `#title` or `#view_count` information on a  Post instance ...

Not sure if it's just not supported at this time or I am doing something wrong.  Thanks!.

**Comment by castwide** [comment]
Support for `@!macro` is still a work in progress. In this particular case, Solargraph will interpret the the `@return` as the type of the `property` call itself:

```ruby
class Resource
  # Defines a new property
  # @param [String] name the property name
  # @param [Class] type the property's type
  # @!macro [attach] property
  #   @return [$2] the $1 property
  def self.property(name, type) end
end

class Post < Resource
  property(:title, String) # => String
  property(:view_count, Integer) # => Integer
end
```

This is a tricky one to resolve because there are instances where the current behavior is desirable, but it should probably use a different syntax.

In the meantime, the workaround is to use the `@!method` and `@!attribute` directives.

**Comment by thornomad** [comment]
Thanks to getting back to me so quickly.  I can imagine this is a tricky one.  I'd be curious to see how it is implemented, because based on the above Yard documentation I would expect:

```
post = Post.new
post.title # => String
post.view_count # => Integer
Post.property # => Defines a new property (...)
```
I can see how being able to dynamically deterimine the return type is useful in solargraph.  How does Yard parse it though when creating the documentation since, I assume, `.property` would get just one reference even though it is called twice?

What I am really trying to get to, though, is to be able to dynamically assign this kind of thing to methods created via `define_method` which is done a lot in the code base I am working on.  I have some class methods which create three or four related instance methods and would love to not have to write out all the `@!method` and `@!attribute` stuff.

Thanks again!

**Comment by castwide** [comment]
YARD executes the macro once for every `property` call. The generated docs match your expectations with one exception: it doesn't execute the macro for `Post.property`, only `property` from inside the class scope.

The `@!macro` directive can definitely get hairy, especially for anything more complicated than that `property` example. In cases where you need to document dynamic `@param` and `@return` types that can't be scraped from the call arguments, `@!method` and `@!attribute` might be your only option.

**Comment by thornomad** [comment]
Thanks for the input, will close this for now and keep an eye out on this work in progress.  Thanks.

**Comment by Caleb-T-Owens** [comment]
Hi! Has there been any improvement on this? I was trying it out today with no avail. Its causing my CurrentAttributes to be a little messy which is unfortunate
