### ISSUE TITLE
Remove irb from dependencies

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#258]
An update to the master branch removes `irb` from the runtime dependencies. It breaks jruby due to its `io-console` dependency. As far as I can tell, Solargraph doesn't use `irb` directly. I'm noting the change here in case it causes unexpected issues.

**Comment by kirichkov** [comment]
This should also resolve the issue I experienced:

While trying to update to 0.38.1 on ruby 2.3 (system ruby on macOS 10.14) I couldn't directly update, as irb tried to install latest, incompatible with ruby 2.3 version of reline and several other gems. The only solution was to manually install older dependencies, including irb 1.0.0 that would install on ruby 2.3

**Comment by castwide** [comment]
I was able to confirm that removing the irb dependency fixes gem installation on OSX (10.13) using the system Ruby (2.3). The change will be included in the next patch release.

**Comment by castwide** [comment]
Released in v0.38.2.

**Comment by kirichkov** [comment]
v0.38.2 Installs without issues on OS X 10.14 as well!
