### ISSUE TITLE
/suggest is relatively slow 

### ISSUE THREAD

**Issue by patilarpith** [castwide/solargraph#26]
I was trying to figure of why the completion requests takes roughly 700ms. Was thinking if HTTP POST has a lot of overhead and switching to a different transport method might bright down that value.

To my surprise CodeMap::suggest_at() itself takes roughly 450 ms. 

Wondering if there are ongoing efforts to bring that value down?

**Comment by castwide** [comment]
The upcoming support for language server protocol will include a stdio transport. Early tests are noticeably faster.

Improvements to CodeMap, ApiMap, and YardMap are an ongoing concern. Among the candidates to improve performance:
* Reduce the amount of source parsing and map processing required to handle individual requests
* Improve map caches
* Refresh maps in concurrent threads

**Comment by patilarpith** [comment]
@castwide Is there a project TODO list or a roadmap tracked somewhere?

**Comment by castwide** [comment]
@patilarpith There's a public project in Pivotal Tracker: https://www.pivotaltracker.com/n/projects/1970245

**Comment by castwide** [comment]
The switch to LSP and improvements to the internal maps should significantly improve the speed of completion results in the current gem.

**Comment by patilarpith** [comment]
Yes! I can see the change from sub 350-550ms completion response time to 120ms response time between (v0.17.3) vs (v0.21.1)

Closing this as the underlying issue is now resolved
