### ISSUE TITLE
api_map.rb requires optimization

### ISSUE THREAD

**Issue by jonnyboyC** [castwide/solargraph#261]
Hi! First off let me say awesome job to getting this project up and running! I personally have a language-server as my own side project and I know how much of an undertaking it can be!

I've know there is some consideration on replacing the parser with a more high performance implementation but do some profiling I've identified that on very large projects the bottleneck isn't parsing speed. I've been running [rbspy](https://rbspy.github.io/) against our companies main rails server project using `solargraph scan`. Solargraph identifies 12k files, so I would definitely say this is on the higher end use cases. 

Long story short rbspy identified [this chunk](https://github.com/castwide/solargraph/blob/master/lib/solargraph/api_map.rb#L105-L118) of `api_map.rb` as contributing something in the ballpark of 90% of the runtime, potentially more. Here is the same chunk of code below:

``` rb
unless bundle.workspace.require_paths.empty?
  reqs.delete_if do |r|
    result = false
    bundle.workspace.require_paths.each do |l|
      pn = Pathname.new(bundle.workspace.directory).join(l, "#{r}.rb")
      if new_map_hash.keys.include?(pn.to_s)
        local_path_hash[r] = pn.to_s
        result = true
        break
      end
    end
    result
  end
end
```

My understanding of what this chunk of code is trying to do is identify `require`s diff. I'm assuming the idea is to only process things that have changed since last time `catalog` was run. as I've tried to come up with a new algorithm to speed this up I believe I've identified a bug in this implementation. Specifically this line
```rb
pn = Pathname.new(bundle.workspace.directory).join(l, "#{r}.rb")
```

running `api_map_spec.rb` I've noticed that `bundle.workspace.directory` is the empty string causing the tests to pass. I've noticed in the general case this won't remove any reqs. Consider this example

```rb
# input
reqs = ['lib1', 'lib2]
new_map_hash = {
  'some/path/lib1.rb': # ...
  'some/other/path/lib3.rb': # ...
}
bundle.workspace.directory = 'some'
bundle.workspace.require_paths = [
  'some/path',
  'some/other/path',
]

# paths tested in the code snippet above
tested_paths = [
  'some/some/path/lib1.rb',
  'some/some/path/lib2.rb',
  'some/some/other/path/lib1.rb',
  'some/some/other/path/lib2.rb',
]

# output
req_final = ['lib1', 'lib2']
expected_req_final = ['lib2']
```

Is this the the correct expected behavior? I've got some ideas about speeding this up mostly using a trie but I want to make sure that I've got the correct behavior nailed down.

**Comment by castwide** [comment]
Good catch. Your expectation looks correct. Given the input in your example, I'd expect `reqs` to be `['lib2']`. (I assume 'some/some' in your tested paths indicates the require path appended to the workspace path.)

That code is a little hairy, so I'll provide some clarification. The `unless bundle...` snippet compares all the requires and required paths to the files mapped in the workspace. If it finds a match, there's no need to process the require any further; the file's code is already mapped. Any requires that don't match get passed to the YardMap, which tries to match it against any available gems and the stdlib. (Side note: for mapping purposes, `autoload` is treated about the same as `require`.)

It looks like you've found both a bug and a strong candidate for optimization. I'd be happy to accept a PR. Any questions, just let me know.

**Comment by jonnyboyC** [comment]
I elaborated a bit in the PR, but I'm having one test, in a file indirectly related to changes I made fail. The good news is there is definitely a very large speed up in bigger repo. But I would appreciated any help diagnosing the problem!

**Comment by castwide** [comment]
I ran a few tests on the require_paths issue. From what I've seen, the catalog process correctly filters requires that are part of the workspace.

If you're still experiencing the problem, can you give me an example project where it happens or the steps to reproduce it?
