### ISSUE TITLE
Could it support to the nokogiri >= 1.10?

### ISSUE THREAD

**Issue by goe13** [castwide/solargraph#263]
VSCode can't use it:

Failed to start Solargraph: Error: [LoadError] incompatible library version - /Users/eos/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle

[LoadError] incompatible library version - /Users/eos/.rvm/gems/ruby-2.6.3/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle

**Comment by castwide** [comment]
Could you try `gem install nokogiri` and tell me what happens? (I expect to update nokogiri in the near future, but I'm not sure if this error is directly related to the dependency. Solargraph should already work with 1.10. I'm using 1.10 myself on Windows.)

Possibly related: https://stackoverflow.com/questions/52514791/after-upgrading-to-macos-mojave-gem-update-is-failing#answer-52624622

**Comment by goe13** [comment]
It work well:
$ gem install nokogiri
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.7
Parsing documentation for nokogiri-1.10.7
Done installing documentation for nokogiri after 1 seconds
1 gem installed


I'm using the rvm installed **ruby2.6.3**.
I try to unstall the nokogiry `gem uninstall nokogiri`,But my vscode plugin also got error is:
`[LoadError] incompatible library version - /Users/eos/.rvm/rubies/ruby2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.bundle`

**Comment by goe13** [comment]
It work well:
```
$ gem install nokogiri
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.7
Parsing documentation for nokogiri-1.10.7
Done installing documentation for nokogiri after 1 seconds
1 gem installed
```

I'm using the rvm installed **ruby2.6.3**.
I try to uninstall the nokogiry gem uninstall nokogiri,But the vscode also got this error:
`[LoadError] incompatible library version - /Users/eos/.rvm/rubies/ruby2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.bundle`

**Comment by goe13** [comment]
It seems work well:
```
$ gem install nokogiri
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.7
Parsing documentation for nokogiri-1.10.7
Done installing documentation for nokogiri after 1 seconds
1 gem installed

```
I'm using the rvm installed **ruby2.6.3**.
I try `gem uninstall nokogiri`,But the VSCode also got error message:
```
[LoadError] incompatible library version - /Users/eos/.rvm/rubies/ruby2.6.3/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.bundle
```

After run `gem install nokogiri -v 1.9.1` also got the error message above.

**Comment by castwide** [comment]
I haven't been able to reproduce this problem. Currently I'm testing on MacOS 10.13.6 with Ruby 2.6.3, Solargraph 0.38.2, and Nokogiri 1.10.7.

It's possible that you need to install or update some external binary or developer headers, but I don't know beyond that.

This vscode-solargraph issue might also be relevant: https://github.com/castwide/vscode-solargraph/issues/103

**Comment by goe13** [comment]
> I haven't been able to reproduce this problem. Currently I'm testing on MacOS 10.13.6 with Ruby 2.6.3, Solargraph 0.38.2, and Nokogiri 1.10.7.
> 
> It's possible that you need to install or update some external binary or developer headers, but I don't know beyond that.
> 
> This vscode-solargraph issue might also be relevant: [castwide/vscode-solargraph#103](https://github.com/castwide/vscode-solargraph/issues/103)


Thank you ! Found the solution [Above](https://github.com/castwide/vscode-solargraph/issues/103#issuecomment-578688782)
