### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by valeth** [castwide/solargraph#27]
Solargraph tends to use a ridiculous amount of memory.

I noticed this while using it with the Visual Studio Code plugin and two editor instances open.
It got so bad that it ended up consuming so much memory that the OOM killer had to intervene.

![screenshot_20180218_001608](https://user-images.githubusercontent.com/3198362/36346595-43f6f82e-1441-11e8-876f-6a882b5cff93.png)
> Here it is using ~16% of my total memory per process.

Not sure if this is a problem with the server (probably), or the VSC plugin.

Might be worth noting that I'm using `rbenv` with multiple ruby versions (mainly 2.4.0, 2.41 and 2.5.0).

**Comment by castwide** [comment]
1) Do you have a very large folder open? Solargraph will map the entire folder as a unified workspace. This is useful if your root folder represents a single project, but less useful if you're using the open folder as a general file explorer, e.g., if you've opened your entire home directory. This can be especially problematic if you're using something like rbenv, as it will attempt to map every gem in every ruby version it finds.

We might be able to mitigate this issue by ignoring `.` directories by default. Opening your home directory might still result in a ridiculous amount of mapping effort, but at least it wouldn't try to map every gem in every configured ruby environment.

2) If you have a specific project open but it includes vendored gems, Solargraph will include them in the map by default. This can be mitigated with a .solargraph.yml file in the project root.

For comparison, when I open a checkout of the entire rails repo, the server uses just under 140MB.

Please feel free to share more details about your use case if you still have problems.

**Comment by castwide** [comment]
I opened issue #30 to discuss restraints on workspace map processing.

**Comment by castwide** [comment]
The latest versions of the gem and extension should fix some of the memory usage issues. I'm still working on solutions for mitigating very large workspaces.

**Comment by valeth** [comment]
Looks like one of the latest commits fixed this issue.
Will close this for now.

**Comment by bowmanmike** [comment]
Not sure what I'm doing wrong here, but indexing a fresh checkout of `rails/rails` is using ~700mb of RAM. I've got a folder I use at work that has several related projects nested inside, and that easily uses multiple GB, and takes several minutes to index. I'm using a `.solargraph.yml` to exclude specs, tests, bundles, all that jazz. Any tips?

For rails, I'm using the default config generated by `solargraph config`, and I'm using `solargraph 0.23.5`

**Comment by castwide** [comment]
@bowmanmike I get high memory usage opening `rails/rails` as well. It improves slightly when I change the .solargraph.yml `include` to the following:

```
include:
- "**/lib/**/*.rb"
```

The default configuration fails to exclude the various components' tests because they're in subdirectories like `actioncable/test` instead of the root.

The support for multiple workspaces we're discussing in castwide/solargraph#78 could also help.

**Comment by bowmanmike** [comment]
Adding that rule seems to help somewhat, but it's still pretty high (~500mb). Anyways, thanks!
