### ISSUE TITLE
Some gems autocomplete appears incomplete

### ISSUE THREAD

**Issue by longspell** [castwide/solargraph#270]
I've installed the latest solargraph and I'm seeing language server suggestions on autocomplete, however some gems seem to be missing at least some suggestions.  I've completed a `yard gems` and then in my rb file (single script) I do a `require 'yaml'` then noticed in the autocomplete suggestions for `YAML.` are missing `dump` and `load`, which I expected from the example at the top of https://ruby-doc.org/stdlib-2.5.1/libdoc/yaml/rdoc/YAML.html.  Is there something different I need to do because this is part of stdlib?

Thanks

**Comment by castwide** [comment]
I just tested and confirmed. Most of the stdlib should just work out of the box, but some components are incompletely mapped. It looks like YAML is one of them.

From what I can tell, the `YAML` constant is an alias for `Psych`. YARD is able to detect the `YAML` constant, but doesn't associate the `Psych` class methods with it. The methods are visible if you reference `Psych` itself:

![image](https://user-images.githubusercontent.com/3704922/73189728-e2d38e00-40f2-11ea-9094-e5d56b707aec.png)

Solargraph has a mechanism for augmenting the core and stdlib maps. I should be able to use it to fix the `YAML` association.

**Comment by castwide** [comment]
The current release maps YAML to Psych for documentation.
