### ISSUE TITLE
bug: may no completion tip for @!method annotation

### ISSUE THREAD

**Issue by SolaWing** [castwide/solargraph#271]
```ruby
module A
  module Generator
    def aa
      # following line no generate! tip
      generate
    end
    # @!method generate!()
    #   generate the

    # has tip if uncomment the following line
    # def foo
    # end
  end
end
```

**Comment by castwide** [comment]
I get the `generate!` completion item with v0.38.5:

![image](https://user-images.githubusercontent.com/3704922/73990560-86a11300-4917-11ea-9c1a-6e49d5d1de79.png)

**Comment by SolaWing** [comment]
sorry，I use the v0.39 branch

**Comment by castwide** [comment]
Hmm, it works for me on the v0.39 branch too. I tested on Ruby 2.3.1 and 2.6.3.

* What version of Ruby are you using?
* What OS?
* VS Code or something else?

**Comment by SolaWing** [comment]
I tested on 3.18.5, it's not work. v0.39 branch is ok
ruby 2.7,mac os,vim, ycmd's language server

1. and observe the first completion is not ok.
2. delete this line, re-enter newline and completion is ok
3. after type some char, trigger completion is not ok.

here is the solargraph log:

[rubycompleter_stderrbfaqyey2.log](https://github.com/castwide/solargraph/files/4168806/rubycompleter_stderrbfaqyey2.log)
