### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by peterhoeg** [castwide/solargraph#274]
Opening a moderately sized rails project with multiple version of the same gems in the local environment causes solargraph to gobble up large amounts of memory (3.5GB).

The environment uses `direnv` to set up a local gem store so a multitude of versions exist. 

Ideally solargraph would use bundler to get the list of actual versions in use and only index those.

Version 0.38.0

Ref: https://github.com/castwide/solargraph/issues/27

**Comment by castwide** [comment]
> Ideally solargraph would use bundler to get the list of actual versions in use and only index those.

That's what it should be doing. I'm not sure if that's specific to `direnv`, but I'll look into it.

Updating to v0.38.5 might also make a difference.

The upcoming v0.39 should further reduce memory usage. More info: #268

**Comment by castwide** [comment]
One other thing: is your local gem store inside of your workspace? If so, you might want to add its directory to `exclude` in `.solargraph.yml` to make sure it's not getting mapped. More information: https://solargraph.org/guides/performance

**Comment by peterhoeg** [comment]
> One other thing: is your local gem store inside of your workspace? 

It is using `direnv`'s `layout ruby` functionality.

> If so, you might want to add its directory to exclude in .solargraph.yml 

I had changed things from excluding some directories to specifically only including the relevant directories and now it's only sometimes it eats up memory (right now it's about 700MB which is fine).

I'll add more details to this issue when it happens again. OK to leave it open?

**Comment by castwide** [comment]
Thanks for the followup. Yes, feel free to leave it open and let me know if the problem persists.

**Comment by castwide** [comment]
Version 0.39.0 includes some changes that should significantly reduce memory usage.

**Comment by castwide** [comment]
In my most recent tests opening rails/rails in VS Code, v0.38.6 uses ~1.2 GB of memory. v0.39.7 uses ~460 MB. Initialization time is also much faster (65s vs 26s).
