### ISSUE TITLE
Go to definition for required gems

### ISSUE THREAD

**Issue by longspell** [castwide/solargraph#276]
I'm using nvim.coc with coc-solargraph, it's great.

I'm struggling with go to definition for gem methods though, or even methods from the standard library.  If I `require 'json'` (regardless if I restart solargraph) I do get the documentation (via `show_documentation()` and when selecting methods from the autocomplete list) however if I try to go to definition, I get `Definition not found`.  I'm not sure if that's a configuration problem or coc issue, really just looking to confirm whether std lib methods and required gem methods should support going to definition.

I can't seem to get solargraph logs from coc using stdio, but got the following by running solargraph manually and pointing coc to the host:port:

```
[INFO] Server received textDocument/hover
[DEBUG] {"jsonrpc"=>"2.0", "id"=>1, "method"=>"textDocument/hover", "params"=>{"textDocument"=>{"uri"=>"file:///Users/longspell/rbtest/test.rb"}, "position"=>{"line"=>35, "character"=>13}}}
[INFO] Sending response to textDocument/hover
[DEBUG] Content-Length: 478

{"jsonrpc":"2.0","id":1,"result":{"contents":{"kind":"markdown","value":"[JSON.pretty\\_generate](solargraph:/document?query=JSON.pretty_generate)\n\n(obj, opts = nil)\n\nGenerate a JSON document from the Ruby data structure _obj_ and return it. The returned document is a prettier form of the document returned by\n\n# unparse.\n\nThe _opts_ argument can be used to configure the generator. See the generate method for a more detailed explanation.\n\n\n\nVisibility: public"}}}
[INFO] Server received textDocument/definition
[DEBUG] {"jsonrpc"=>"2.0", "id"=>2, "method"=>"textDocument/definition", "params"=>{"textDocument"=>{"uri"=>"file:///Users/longspell/rbtest/test.rb"}, "position"=>{"line"=>35, "character"=>12}}}
[INFO] Sending response to textDocument/definition
[DEBUG] Content-Length: 36

{"jsonrpc":"2.0","id":2,"result":[]}
```

Thanks

**Comment by castwide** [comment]
Go to definition currently doesn't work for the Ruby core and stdlib. It should work for other gems, including the [gemified standard library](https://stdgems.org/) if you're using it.

Support for core/stdlib is a possibility, but there are some performance and accuracy issues that need to be resolved.

**Comment by castwide** [comment]
I should also mention that you might need to run `yard gems` for gem documentation to work correctly. More information: https://solargraph.org/guides/yard

**Comment by longspell** [comment]
Thanks for the quick follow up.  Documentation is ok, it's only Go To Definition that fails.  I also get the methods suggested in autocomplete.  I've run `yard gems` before, but ran it again.  No change to Go To Definition.

**Comment by castwide** [comment]
If it's pulling `json` from the stdlib, Go To Definition won't work for it. Have you tried it with any external gems, e.g., just about anything in your Gemfile? You could even test it with Solargraph itself:

```ruby
require 'solargraph' # Go To Definition should work on the 'solargraph' string
Solargraph::ApiMap   # It should also work on either symbol in this namespace
```

I don't often use coc.nvim, but AFAIK it should include Solargraph's definition features by default.

**Comment by longspell** [comment]
Can confirm that works, I misunderstood your comment re: gemified standard library.  Thanks again.
