### ISSUE TITLE
Takes too long for solargraph server to be in ready state for large projects

### ISSUE THREAD

**Issue by praveendhawan** [castwide/solargraph#278]
Versions - 
NVIM v0.4.3
CoC - Latest version
OS - MacOs

I am working on a large project, and after I start Nvim it takes ~3 minutes to change the state of the solargraph server.

Logs 

```
2020-02-13T11:27:04.940 INFO (pid:4567) [services] - registered service "solargraph"
2020-02-13T11:30:10.955 INFO (pid:4567) [services] - Ruby Language Server state change: starting => running
2020-02-13T11:38:09.321 ERROR (pid:4567) [languages] - getDefinition timeout after 5s
2020-02-13T11:38:09.332 ERROR (pid:4567) [plugin] - Error: getDefinition timeout after 5s
```
If you see in the logs above it took solargraph ~3 minutes to change server state from starting to ready.

Also, the Get Definition and jumping takes too long and sometimes it times out.

Thanks in advance.

**Comment by castwide** [comment]
How large is your project (number of files, approx. LOC, number of gem dependencies)?

If you're not using the latest gem (v0.38.5), I highly recommend upgrading.

There are some additional performance improvements coming in v0.39.0 and currently being tracked in #268.

**Comment by praveendhawan** [comment]
@castwide If I remove all the views, assets, vendor files, spec files 
No. of FIles -  4851 (`tree -f -C -I 'node_*|doc*|tmp*|vendor*|spec*' ./ |  grep  files`)
Gem version - v0.38.5
No. of gem dependency - Bundle Output - 163 Gemfile dependencies, 380 gems installed
LOC -  123264 total (`git ls-files | grep -e "\.rb$" |  xargs wc -l`) This includes spec files as well

**Comment by castwide** [comment]
That's big enough to cause a long startup time, but I'm surprised that the queries are timing out after the code is already mapped.

I'll try a few benchmarks on larger codebases over the weekend. (If there's a repo I can access to test on the same codebase you're using, that might give me some more insight, but I understand if the source is closed/proprietary. I usually turn to rails/rails when I want to see how Solargraph handles 100K+ LOC.)

I'm still optimistic that v0.39.0 will help with performance, too.

**Comment by praveendhawan** [comment]
@castwide You can test it on https://github.com/solidusio/solidus or yeah rails also works.

**Comment by praveendhawan** [comment]
After v0.38.6 timeouts are no more, seems to me those were due to https://github.com/castwide/solargraph/issues/288
