### ISSUE TITLE
does it must be full path namespace to use autocompletion?

### ISSUE THREAD

**Issue by siumennel** [castwide/solargraph#28]
i want to confirm that does it must be full path namespace to use autocompletion?
 ` # @return [Array<MyModule::MyClass>] uiiiii `
=> i can get the intelligence autocompletion.
but 
 ` # @return [Array<MyClass>] uiiiii `
=> i can **not** get the intelligence autocompletion.
does it must be full path namespace to use autocompletion?
thanks a lot!

![with_namespace](https://user-images.githubusercontent.com/4219901/36833527-09b931c8-1d73-11e8-854a-a76184865f87.png)
![without_namspace](https://user-images.githubusercontent.com/4219901/36833538-12057d8c-1d73-11e8-9046-939fddb9b689.png)

**Comment by castwide** [comment]
Yes, you're correct. I hope to fix that limitation in an upcoming version. Solargraph should be able to resolve relative paths in `@return` tags based on the namespace where the tag is.

**Comment by siumennel** [comment]
Thank you for your reply. I know it may be difficult but  I think it will help us a lot if you can conque it. Waiting for your success!

**Comment by castwide** [comment]
This feature is pushed to the master branch. It'll be published in gem version 0.17.4.

**Comment by castwide** [comment]
Published in 0.17.4.
