### ISSUE TITLE
Allow rc versions of dependencies

### ISSUE THREAD

**Issue by svl7** [castwide/solargraph#286]
Currently gem won't be able to install solargraph on ruby 2.7.0 due to the dependency restriction `'nokogiri', '~> 1.9', '>= 1.9.1'`.
Since nokogiri only introduced support for 2.7.0 in [1.11.0.rc1 ](https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1), it will fail to install since solaraph doesn't allow rc version in the gemspec.

Demo:
```
gem install solargraph
ERROR:  Error installing solargraph:
        The last version of nokogiri (~> 1.9, >= 1.9.1) to support your Ruby & RubyGems was 1.10.8
```
1.10.8 won't solve the issue since it doesn't support ruby 2.7

```
gem list nokogiri

*** LOCAL GEMS ***

nokogiri (1.11.0.rc1)
```
Can't be used to the restriction in gemspec.

**Comment by castwide** [comment]
Just a heads up, there's a possible workaround for this issue in #317.

**Comment by phraemer** [comment]
Also could need this as I'm on Windows with Ruby 2.7.1 so the workaround doesn't help me, unfortunately.

**Comment by svl7** [comment]
@phraemer You can get it to work on Windows when you build nokogiri yourself. You'll need the MinGW environment (usually installed along ruby when using the ruby installer on windows), then run the following:
`ridk exec pacman -S mingw-w64-x86_64-libxslt` This gets the required dependencies.

`gem install nokogiri --platform=ruby -- --use-system-libraries` This will build and install nokogiri.

Afterwards you should be able to install solargraph directly, therefore it's not really a solargraph issue.
