### ISSUE TITLE
Intellisense for Functions is not working 

### ISSUE THREAD

**Issue by csanthoshi** [castwide/solargraph#29]
**Environment**:
- vscode-ruby version: 0.16.0
- VS Code version: 1.16.1
- Ruby-Solargraph: 0.12.0

**Description**:
My Ruby Project Structure contains Page Object files in which I will be writing function Definitions inside Modules. So for each function definitions I will be writing the Function Description in Yaardoc format. The issue here is previously when I tried to use the definitions in my test case I used to get the Description/quick info of the methods and also all the definitions inside module as suggestions.

But, since one month I am not getting any function suggestions or the description of the functions. I explored if there are any issues filed and the reasons for it but unfortunately I could not figure it out.

Can someone please help me out the reason for this.

Sample Function: ProjectName/PageObjects/Hello.rb
```
module ModuleName

      # funName: Description of the Function

      # @param [String] param1

      # @param [String] param2

         def funName(param1,param2)

             begin

                  # My function definition here

             end

         end 

  end
```

FYI:
I tried to create a .solargraph.yml file and it contains
```
include:
  - ./**/*.rb
exclude:
  - spec/**/*
  - test/**/*
```
Can someone help me out the reason for this issue.

Thanks! in advance.

**Comment by castwide** [comment]
What OS are you using?

What version of the solargraph gem? (Latest is 0.17.3)

Are there any error messages in the console? (Help -> Toggle Developer Tools)

Can you show an example of code where you expect a suggestion for funName but don't receive it?

I tested your sample code with a class that includes ModuleName and was able to get suggestions for it.

Test code:

```ruby
module ModuleName

  # funName: Description of the Function

  # @param [String] param1

  # @param [String] param2

     def funName(param1,param2)

         begin

              # My function definition here

         end

     end 

end

class ClassName
  
  include ModuleName

  def classMethod
    fun # <- I received funName in method suggestions here
  end
end
```

Screenshot:

![image](https://user-images.githubusercontent.com/3704922/36888554-f7225c46-1dc3-11e8-94ed-973e4929bd08.png)

**Comment by csanthoshi** [comment]
Hi @castwide Thanks for the quick reply

The OS I am using is Windows 7
Solargraph gem version is 0.12.0

Attached the screenshots of the function file, testfile with the error screenshot 

![image](https://user-images.githubusercontent.com/21240158/36889608-d174a5ee-1dc8-11e8-9d08-b2e5876eac81.png)

![image](https://user-images.githubusercontent.com/21240158/36889617-d777dfc4-1dc8-11e8-93ef-251a73c11b08.png)

![image](https://user-images.githubusercontent.com/21240158/36889622-dec43200-1dc8-11e8-91a5-da04a5326df5.png)


Please let me know if I miss something here.

**Comment by castwide** [comment]
In your second screenshot, you're calling `ModuleName.funName` like a singleton method, but it's defined as an instance method. Since Solargraph doesn't expect it to work that way, the method doesn't get suggested.

Here's a simplified example:

```ruby
module ModuleName
  def funName
    puts "Executed funName"
  end 
end

ModuleName.funName
```

If you run that code, you get an error:

```
$ ruby app.rb
./app.rb:7:in `<main>': undefined method `funName' for ModuleName:Module (NoMethodError)
$
```

Defining funName as a singleton method works:

```ruby
module ModuleName
  def self.funName
    puts "Executed funName"
  end 
end

ModuleName.funName
```

```
$ ruby app.rb
Executed funName
$
```

When funName is a singleton method, Solargraph gives you the expected suggestion:

![image](https://user-images.githubusercontent.com/3704922/36891132-7f3a32fc-1dce-11e8-8391-1eedbc45f661.png)

**Comment by csanthoshi** [comment]
@castwide Apologies for the Wrong screenshot and late response. The way I write the function is

![image](https://user-images.githubusercontent.com/21240158/36909681-b4a1b3c8-1e0c-11e8-9e56-680f9d2facd7.png)

And I will be requiring the file in my test.rb

![image](https://user-images.githubusercontent.com/21240158/36909768-f93c4fd4-1e0c-11e8-8718-fd8748b4f1b1.png)
 
I used to get the Info Icon next to function name and the description when I clicked on it before but since December it is not getting displayed.

Can you please check it once and please let me know if I am doing something wrong here.

Thanks!

**Comment by castwide** [comment]
@csanthoshi Thanks for clarifying. That code should definitely be able to detect ModuleName.funName as a singleton method.

One possible issue: Solargraph searches your workspace (i.e., whatever folder you open in VS Code) for .rb files to use for completion suggestions. If you don't have an open folder, the scripts get mapped individually, so Test.rb would not be able to show suggestions from ModuleName.rb. Solargraph can't detect the other file from the `require` call alone. It abstains from executing the code to avoid unwanted side effects, so it doesn't know the result of the `File.expand_path` expression.

If you open the project's root folder, Test.rb should be able to give you suggestions from ModuleName.rb. If that still doesn't work, please let me know and we'll investigate further.

**Comment by kopischke** [comment]
>Solargraph can't detect the other file from the `require` call alone. It abstains from executing the code to avoid unwanted side effects, so it doesn't know the result of the `File.expand_path` expression.

Apologies for jumping in, but while I think Solargraph is entirely right in not executing the code it parses (my beef with anything based on `rcode`), could a carefully curated (i.e. one limited to the `File` and `Pathname` modules) exception not be made for `require(_relative])` calls?

**Comment by castwide** [comment]
@kopischke It's definitely worth consideration. The more detail that can be derived from the code itself, the better.

Solargraph already checks `require` calls for external gems to query for YARD documentation. Right now it only supports literal strings, but it seems like a good starting point for further enhancements.

Any expressions that get evaluated would need to be curated down to whitelisted methods. `File.join` and `File.expand_path` are okay; `File.open` and `File.write` are not.

It's not trivial, and there will always be outlying scenarios, but if we can find a safe solution that satisfies common use cases, I'm open to the idea.

**Comment by kopischke** [comment]
@castwide:

>Any expressions that get evaluated would need to be curated down to whitelisted methods. `File.join` and `File.expand_path` are okay; `File.open` and `File.write` are not.

Ugh, yeah, I kinda forgot how Ruby interleaves file system traversal and file operations in `File`. Not the wisest of design decisions (as someone must have noticed before creating the `Pathname` module)…

**Comment by csanthoshi** [comment]
@castwide Yes, My Project root folder is open but still I am not getting any suggestions.

And one more thing I want to mention is that I am seeing this issue since December. Before December I am able to see the Info Icon and suggestion methods.

**Comment by castwide** [comment]
Are you getting any errors in the developer console? (Help -> Toggle Developer Tools)

**Comment by csanthoshi** [comment]
Yes I am getting console errors. Attached the screenshot of it.

![image](https://user-images.githubusercontent.com/21240158/37021035-04ce28f4-20ec-11e8-870e-58191918b4db.png)

**Comment by castwide** [comment]
`xmpfilter` is used by `rcodetools`. What happens when you disable the Ruby (vscode-ruby) extension?

**Comment by csanthoshi** [comment]
@castwide If I disable it I am not getting any console errors but I am not getting any suggestions.

**Comment by castwide** [comment]
Do you get suggestions for core Ruby methods? e.g., `[].` should suggest array methods.

**Comment by csanthoshi** [comment]
No, I am not getting any suggestions for this as well.

**Comment by castwide** [comment]
Ouch. I'm afraid I'm stumped.

One more thing you can check. The developer console should give you a log message `Solargraph extension activated.` When the server starts, it should log information about itself, e.g., `[2018-03-06 00:00:00] INFO WEBrick::HTTPServer@start: pid=99999 port=99999`. If either of those messages don't appear, the extension might be silently failing for some reason.

If the problem persists, I'll try to get access to a Windows 7 machine or VM so I can try to reproduce the error. At the moment, I'm only set up to test on Windows 10, MacOS Sierra, and a couple versions of Linux.

**Comment by csanthoshi** [comment]
I tried reloading the Solargraph extension but I guess that the Solargraph is not enabled. I attached screenshot of console errors when I reloaded the Solargraph.

![image](https://user-images.githubusercontent.com/21240158/37035465-a47f0e76-211a-11e8-9d8f-1f0a7408559e.png)


![image](https://user-images.githubusercontent.com/21240158/37035385-67cf7010-211a-11e8-9641-63d130bc11b1.png)

**Comment by castwide** [comment]
One more thing you can try is uninstalling both the Ruby and Solargraph extensions, then reinstalling the Ruby extension. At the moment, Solargraph is one of its extension dependencies, so it should get reinstalled automatically.

**Comment by csanthoshi** [comment]
I tried uninstalling solargarph many times but it did not resolved any issues but after uninstalling the Ruby and reinstalling it worked for me.

Thank you so much for the quick response and help.

Regards,
Santhoshi
