### ISSUE TITLE
Question - Does Solargraph supports code folding?

### ISSUE THREAD

**Issue by praveendhawan** [castwide/solargraph#291]
I am using [coc-solargraph](https://github.com/neoclide/coc-solargraph) and in the Readme, it says that you can enable code folding.  Even after calling the fold request I got an error. Here is the issue - https://github.com/neoclide/coc-solargraph/issues/20

**Comment by castwide** [comment]
Yes, it does. I can confirm that it's working and enabled by default in VS Code.

**Comment by praveendhawan** [comment]
@castwide I guess it can be closed. Thanks for the quick reply.
