### ISSUE TITLE
Detect wrong argument number

### ISSUE THREAD

**Issue by MicMicMon** [castwide/solargraph#294]
```ruby
def f
  'I return a string'
end

f(1)
```
does not raise an error, even though Solargraph knows `f` expects no argument.

Is there a way to have Solargraph (or some other part?) raise a lint error?

**Comment by castwide** [comment]
It's not possible in the current release, but the new type checker coming in version 0.39 is capable of detecting this type of argument error.

**Comment by MicMicMon** [comment]
That's awesome news thanks.
I'll close this issue for now then.
