### ISSUE TITLE
coc-solargraph documentation highlight

### ISSUE THREAD

**Issue by jpserra** [castwide/solargraph#295]
Hello! 

I've been trying to get syntax highlighting on the documentation that shows on the popup window when using coc-solargraph.

Here's an example picture: 
<img width="1260" alt="Screenshot 2020-03-24 at 00 26 45" src="https://user-images.githubusercontent.com/1921706/77375796-7974a200-6d66-11ea-90f9-2069073ae163.png">

I've check the language server logs and I did notice that the codeblocks were not surrounded by the usual backticks ``` that we normally see around them.

Any suggestions here? 

*EDIT*
a sample I got from the logs:
```
        "value": "[Class#allocate](solargraph:/document?query=Class%23allocate)\n\nAllocates space for a new object of _class_‘s class and does not call initialize on the new instance. The returned object must be an instance of _class_.\n\n    klass = Class.new do\n      def initialize(*args)\n        @initialized = true\n      end\n    \n      def initialized?\n        @initialized || false\n      end\n    end\n    \n    klass.allocate.initialized? #=> false\n\n\n\nVisibility: public"

```

**Comment by castwide** [comment]
Try indenting the code block with 2 or 4 spaces. Solargraph detects it since it's a common convention in Ruby core documentation.

```ruby
# Description of the method.
#
# Example:
#
#   Foo.bar(baz)
```

**Comment by jpserra** [comment]
The example I shared comes from rails documentation itself, and I can't get any syntax highlight on any ruby/rails documentation really.

I'm not trying to get my own documentation of a method to work in this particular issue.

**Comment by castwide** [comment]
Sorry, I missed that. I'm not able to test with coc-solargraph at the moment, but it works on VS Code:

![image](https://user-images.githubusercontent.com/3704922/77492892-0d527680-6e18-11ea-8ebc-b22d3289828a.png)

What version of Solargraph are you using? Current is 0.38.6.

**Comment by jpserra** [comment]
I'm running the latest version: 

```
❯ solargraph -v
0.38.6
```

**Comment by castwide** [comment]
I'm still not able to reproduce this problem. You might need to open an issue with coc-solargraph and see if it's on their end.

**Comment by jpserra** [comment]
So, in a desperate attempt to find where the issue was coming from, I decided to give NeoVim a try. 

Turns out it worked smoothly out of the box using the exact same `.vimrc` so I guess this ends up being an issue with `Coc + Vim` and nothing wrong from the solargraph side. 

Thank you for the support @castwide 🙏  I'll close the issue
