### ISSUE TITLE
Starting client failed - permission denied

### ISSUE THREAD

**Issue by scorpion35** [castwide/solargraph#298]
Works great when I install everything (Ruby, Bundler, GEMs, Solargraph etc.) with default settings. However, I am tasked to install Ruby into a custom location, and unable to figure out how to get Solargraph working. Without solargraph, my workflow is slowed down by a lot. Please help 🙏 🙇‍♂️

Here is what I have - 
Ruby version: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]`
(Installed Ruby via RBENV)

```ruby
gem info solargraph

*** LOCAL GEMS ***

solargraph (0.38.6)
    Author: Fred Snyder
    Homepage: http://solargraph.org
    License: MIT
    Installed at: /Users/panne/Documents/Work/.ruby2.7.0/local-gems

    A Ruby language server
```

Path:
`/Users/panne/Documents/Work/.ruby2.7.0/shims:/Users/panne/Documents/Work/.ruby2.7.0/local-gems/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools`

Error: 
```
[Error - 3:16:29 PM] Starting client failed
zsh:1: permission denied: /Users/panne/Documents/Work/.ruby2.7.0/shims
```

But I can confirm I have proper permissions as seen from the below screenshot - 
![image](https://user-images.githubusercontent.com/18679225/77953475-5af93400-729b-11ea-8c5a-3ba3f0a3f6de.png)

I use VSCode, and have installed `solargraph` extension as well, and added the following to my vscode settings - 
```
"solargraph.useBundler": true,
"solargraph.bundlerPath": "/Users/panne/Documents/Work/.ruby2.7.0/shims"
```

Does anyone know what is the issue? Also all the commands available from vscode's cmd palette fails. Here is one error - 
`Running the contributed command: 'solargraph.checkGemVersion' failed.`

**Comment by castwide** [comment]
`solargraph.bundlerPath` should be the absolute path to the executable file, e.g., `/Users/panne/Documents/Work/.ruby2.7.0/shims/bundle`.

**Comment by scorpion35** [comment]
> `solargraph.bundlerPath` should be the absolute path to the executable file, e.g., `/Users/panne/Documents/Work/.ruby2.7.0/shims/bundle`.

Thank you very much 🙇‍♂️. This fixed my issue, was thinking `bundle` would be automatically found since my custom `shims` folders is in the path. 

Is is possible to add this information to docs? Something like 
> Note: `solargraph.bundlerPath` should be an **absolute** path to bundler executable.

I am more than happy to submit a PR if you'd like, not sure where I should be submitting it. Should I submit in the [Solargraph](https://github.com/castwide/solargraph) repo or [VSCode Solargraph](https://github.com/castwide/vscode-solargraph) repo?

**Comment by castwide** [comment]
The best place is probably the [VSCode Solargraph](https://github.com/castwide/vscode-solargraph) repo. The description for `solargraph.bundlerPath` in `README.md` and `package.json` could both stand to be more explicit. If you submit a PR, I'll be happy to merge it.

**Comment by scorpion35** [comment]
Here it is - https://github.com/castwide/vscode-solargraph/pull/167. Thanks again for your help!
