### ISSUE TITLE
RFC: Requiring a .solargraph.yml file for workspace mapping

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#30]
When Solargraph is started with a workspace (e.g., by opening a folder in VS Code), its default configuration is to map all the .rb files in the folder. This seems like reasonable behavior when the workspace represents a unified project; if class `Foo` is defined in project/lib/foo.rb, you probably want suggestions from `Foo` to be available in project/app.rb.

This can be a problem, however, when the open folder isn't a single project. If you open your home directory, Solargraph shouldn't map everything in it.

The simplest solution seems to be requiring a .solargraph.yml in the workspace root. The default configuration can be created with `solargraph config` (or from the command palette in VS Code). If the file doesn't exist, the workspace doesn't get mapped.

I'm curious to know a) how many people experience problems with overzealous mapping, and b) if the config file requirement seems like a reasonable solution. Since it changes the default behavior, I hoped to get some feedback and/or alternative suggestions.

**Comment by castwide** [comment]
The correct behavior might be to require the workspace root to contain either .solargraph.yml or Gemfile. Otherwise the workspace does not get mapped.

**Comment by IevgenSobko** [comment]
I have tried to migrate from RubyMine to VSCode with ruby intergration.
But this solargraph thing eating to much memory. After opening project folder memory consumption jumps to 1.2 Gb. With some code inspection and opening different files I see it became 1.9 Gb. Is this correct behavior?

**Comment by castwide** [comment]
How large is your project folder? Opening the core Rails codebase hovers around 500MB for me.

That being said, the upcoming version of the gem performs better garbage collection and resolves some errors that caused runaway threads. I expect to publish it in the next few days.

**Comment by IevgenSobko** [comment]
Here I attached screenshot
![screenshot_20180409_233249](https://user-images.githubusercontent.com/14232100/38521537-a69afd6a-3c4e-11e8-8518-dfd2e61a5cd1.png)

**Comment by castwide** [comment]
Yeah, that's huge. Do the var and core folders contain Ruby files?

Make sure your solargraph gem is up to date. Current version is 0.18.2.

Another thing you can try is creating a .solargraph.yml and setting include and exclude filters. Run `solargraph config` to generate a default file. My recommendation would be to include only the folders you want to index, e.g.:

```
include:
- "utils/**/*.rb"
- "templates/**/*.rb
```

Include is a little more efficient than exclude. More info: http://solargraph.org/tips

If you still have problems, you can disable Solargraph by changing the `ruby.codeCompletion` and `ruby.intellisense` configuration settings in VSCode. Please let me know if you have any other questions. I'll post when the new gem is published.

**Comment by IevgenSobko** [comment]
I already have this file with following content
`---
include:
- "**/*.rb"
exclude:
- spec/**/*
- .git/**/*
- .logs/**/*
domains: []
required: []
plugins: []
`
AT first glance it should index only 27Mb of ruby files but in reality some gigabytes indexed. Can't understand what is taking so much space.

**Comment by douglascamata** [comment]
@IevgenSobko try excluding `.bundle/**/*`

**Comment by IevgenSobko** [comment]
@douglascamata No it doesn't help
![screenshot_20180515_085405](https://user-images.githubusercontent.com/14232100/40039078-a11825e4-581d-11e8-8438-41465b6c3ff8.png)

**Comment by IevgenSobko** [comment]
@castwide I have both   
```
"ruby.intellisense": false,
"ruby.codeCompletion": false 
```
in my user settings and also workspace settings but solargraph still starts.

**Comment by castwide** [comment]
@IevgenSobko Those configuration settings only affect the Ruby extension. The Solargraph extension has its own options. (There was a time when they shared some settings because Solargraph was one of Ruby's dependencies, but that's no longer the case.)

Solargraph has a `solargraph.completion` setting that can be set to `false`. More configuration options are listed in the [extension's README](https://github.com/castwide/vscode-solargraph).

In View -> Extensions, you also have the option of disabling Solargraph, either in all of VSCode or only in specific workspaces.

Couple other possible solutions:

* If you're using Ruby 2.5, the most recent version of the gem fixes a performance-related issue that might have affected you.
* Do you have any other folders that contain gem caches, such as `vendor`? Try excluding those as well.

**Comment by castwide** [comment]
I'm closing this issue, as the original question of workspace management is largely resolved. In the current gem, the server avoids mapping a workspace containing more than 5000 source files unless it's explicitly permitted in .solargraph.yml.
