### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by raldred** [castwide/solargraph#31]
solargraph is spending a lot of time on the CPU.
I think despite me excluding node_modules and JS it's still processing them according to lsof output.
https://www.dropbox.com/s/g9v6ntaa3tfez8r/Screenshot%202018-03-07%2011.23.34.png?dl=0

config is as follows, it's a Rails app and utilizers the rails webpacker gem for front end react.

```
---
include:
- "**/*.rb"
exclude:
- app/javascript/**/*
- spec/**/*
- test/**/*
- node_modules/**/**
domains: []
required: []
plugins: []
```

**Comment by castwide** [comment]
Solargraph intermittently scans the project directory for new files that need to be added to the map. I suspect that excluded directories like node_modules are getting scanned even though all of its entries are ultimately ignored.

I tried to reproduce the issue by comparing CPU usage on the Solargraph repo itself and a web app that uses both Ruby and Node. I didn't get usage as high as yours, but the difference was still dramatic: ~0.3% for the Solargraph repo and ~8.0% for the Ruby/Node app. The latter project even has significantly less Ruby in it.

There are a couple of ways we might be able to resolve the problem:

* If an entire directory is ignored, Solargraph shouldn't waste any time scanning its entries.
* Maybe the project scan itself is overkill. It might be practical to remove it altogether.

I'll try to have a solution for the next version update. If you have any thoughts or suggestions, please let me know.

**Comment by castwide** [comment]
One thing that might help. Can you give me a general idea of how large your project is? My Ruby/Node app contains about 28,000 files total, with 26,000 of them being in node_modules.

**Comment by raldred** [comment]
This a fairly moderately sized react app for the most park.
Based on a quick `find . -type f | wc -l` there's 46,748 files, 36,125 in node_modules (front end dev 🤣).

I have tried tweaking the config on the project (I'm using the vscode extension)
Now instead of including **/* then excluding certain things, I'm only including specific directories.

```
---
include:
- "app/**/*.rb"
- "lib/**/*.rb"
- "vendor/**/*.rb"
```

For the moment it seems ok.

**Comment by castwide** [comment]
Thanks, @raldred. That seems to align with my observations.

I'll still look into improving the process that scans the workspace. When I disabled it, CPU usage on the Ruby/Node app dropped from 8% to 1%. I'm leaning toward disabling it permanently since it's an expensive way to solve a problem that's probably rare in practice.

**Comment by raldred** [comment]
What's the aim on the workspace scans?
I wonder if using something like [rb-fsevent](https://github.com/thibaudgg/rb-fsevent) for OSX I'm sure other systems have similar filesystem events

**Comment by castwide** [comment]
The main purpose is to detect workspace changes that happen outside of the editor, such as moving a file with a terminal command or pulling changes from a git repo. It probably doesn't warrant scanning the workspace so aggressively.

If the scan stays, the least it should do is avoid excluded directories and run less frequently. That might be good enough.

Without the scan, users can still pick up external changes by restarting the server.

Something like rb-fsevent might help. Thanks for the tip.

**Comment by raldred** [comment]
Just wondered if you had a further thoughts on this or wanted to talk about a solution? 
I'm be happy to help implement.

**Comment by castwide** [comment]
Thanks. Right now I'm concentrating on how workspace changes get handled in the new version that uses the language server protocol. In that implementation, the client sends a notification when a workspace file has been created, changed, or deleted. It should completely eliminate the need for the server to poll for changes. It might still scan the workspace once to determine if the change should update the maps, but only when it receives the notification. This should be significantly more efficient across all platforms.

I have a tentative delivery date of April 2 for LSP in both the gem and the VSCode extension. The gem's current progress is on the `language-server` branch. I expect to push the workspace message handling sometime this week. If you have any thoughts on it, please let me know.

**Comment by castwide** [comment]
Gem 0.18.1 with support for the language server protocol is online. The latest version of the VSCode extension uses the new LSP socket transport instead of the web server. This should alleviate a significant amount of CPU usage. The server depends on the client to notify it of workspace updates, so it sits nearly idle when it's not in use. Map updates are much more efficient and require less file I/O.

**Comment by castwide** [comment]
Version 0.19.0 has a few more updates that could reduce CPU usage. The code maps are more efficient, which affects both memory and processing. It also fixes a few bugs that could cause lag while exceptions crawled up the stack.

**Comment by raldred** [comment]
Very nice updates. I'll check it out later.
