### ISSUE TITLE
Error after Ruby upgrade to 2.7.1

### ISSUE THREAD

**Issue by haslinger** [castwide/solargraph#310]
After updating to ruby-2.7.1 and installing the gem on Ubuntu 18.04, I see the the error message:
`Failed to start Solargraph: Error: [LoadError] cannot load such file -- irb/slex`
on Visual Code startup.

Seems related to: https://github.com/castwide/vscode-solargraph/issues/137
But I don't use the system's package manager, so all dependencies should be resolved already, as the irb 1.2.3 gem is installed.

`slex` has been removed in irb lately: https://github.com/ruby/irb/commit/a49ed9a5733372630d22d45005260552e8f877aa

... found a solution: **updating the yard gem fixes the issue**:
`gem update yard`

I'm not sure, if this should have some follow ups within solargraph. Feel free to close this issue, if not.

**Comment by castwide** [comment]
Thanks. I think this issue is specific to Ruby 2.7+ with YARD < 0.9.21. The upcoming release will update the YARD dependency.
