### ISSUE TITLE
Can't installing to solargraph, and deprecated error nokogiri requires Ruby version < 2.7.dev, >= 2.3.

### ISSUE THREAD

**Issue by SecretShangri-La** [castwide/solargraph#317]
This error is on Windows10 Home Edition. version was 10.0.18363.
I trying `gem install solargraph` but it not to do.

The error is below.
```
C:\Users\<any user>>gem install solargraph
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/command.rb:488: warning: deprecated Object#=~ is called on Class; it always returns nil
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/package.rb:429: warning: Using the last argument as keyword parameters is deprecated
ERROR:  Error installing solargraph:
        nokogiri requires Ruby version < 2.7.dev, >= 2.3.
```
I reference this page (written be Japanese) https://mebee.info/2020/03/02/post-6754/ but not  resolved.

I use Ruby is `2.7.dev` this error be telling to lower the version to 2.3, but reducing the version to 2.3 comes with a security risk

How can I resolve the error without downgrading the version?

**Comment by castwide** [comment]
I'm not able to test this at the moment, but the problem appears to be specific to Nokogiri and Ruby 2.7. More information: https://github.com/sparklemotion/nokogiri/issues/1961

**Comment by castwide** [comment]
One other thing to note. If you downgrade Ruby, you shouldn't have to go all the way back to 2.3. I'm currently using Nokogiri and Solargraph with Ruby 2.6 on Windows 10, and didn't have to use any workarounds.

**Comment by SecretShangri-La** [comment]
I tried this solution. Thanks solved the problem.
Thanks you @castwide
