### ISSUE TITLE
Is there a way to get which project/directory the solargraph is running for?

### ISSUE THREAD

**Issue by praveendhawan** [castwide/solargraph#319]
The reason I want to ask this is -
Let's say I am in the terminal, and in the root directory of the project and I open neovim and open the ruby file to start solargraph.
Now in another terminal, I go to the same project root directory and open neovim and ruby file which will start another server of solargraph.

Is there a configuration or way to start only one instance of solargraph per project?
If I am in a different project, it should start another instance of solargraph.

I am using neovim with coc.

Thanks in advance.

**Comment by castwide** [comment]
In the language server protocol, you typically run one language server for each editor process. You should be able to use a single Solargraph instance with multiple files by opening all the files in the same editor window. I know it's possible to open multiple files in a single neovim instance, but I don't know how coc handles the concept of workspaces. You might need to ask the coc maintainers for more information.

**Comment by praveendhawan** [comment]
ok thanks.
