### ISSUE TITLE
Was there a change with gem documentation inclusion (solargraph bundle)?

### ISSUE THREAD

**Issue by thornomad** [castwide/solargraph#320]
I'm trying to narrow this down and see what happened; but at some point documentation from bundled gems on my Rails project stopped showing up for me with solargraph.  I'm not sure exactly what version of the latest changes this happened.  I am ~not~ _now_ using 0.39.4.

Two things I noticed: 

- if I do `solagraph clear && solargraph bundle` I am no longer seeing it document all the gems like it used to.  it is just doing the rails specific ones (the ones listed in my `solargraph.yml` `require:` section).  However, I feel like I remember it always showing the output of for _each_ gem in the past.  Now it is stopping after a very short list of Rails stuff.

- I am able to get the gem documentation to work by adding the gem manually to the `require:` section in my `.solargraph.yml` file ... however, before I did _not_ need to this.

Wonder if anyone else noticed a change or perhaps something is fishy with my setup.

**Comment by castwide** [comment]
If you're using 0.39.0 or higher, I highly recommend updating to 0.39.4.

I'll look into this, but a couple other questions that might help:

* What version of Ruby are you using?
* In VS Code, do you get any error messages in the developer console (Help -> Toggle Developer Tools)?
* Does `soalrgraph scan -v` complete without errors?

**Comment by thornomad** [comment]
Thanks for the quick response: 

* I'm sorry that was a typo in my first post, I meant to say "I am **now** using 0.39.4" ... which is when I noticed the behavior change.

* I am using Ruby 2.7.1.  To add though: I have been on this version of Ruby for a couple months and this behavior started just recently.  It was working as expected before with 2.7.1.

* `solargraph scan -v` completes without errors

* I am using neovim; I don't see any errors in `CocInfo` or `CocOpenLog`.

By adding the gem names to `require` it _does_ work as intended.  Am using that as a workaround now.  Thanks again and let me know if you need more information.

**Comment by castwide** [comment]
Thanks for the information. I was able to confirm the problem with Ruby 2.7.1, Solargraph 0.39.4, and Rails 6.0.22. There's more than one issue that needs to be addressed here, but I should be able to get it working again shortly.

**Comment by castwide** [comment]
Fixed in 0.39.5. More information: #322

**Comment by thornomad** [comment]
Thank you!  0.39.5 seems to have fixed this!  Great work.
