### ISSUE TITLE
Feature request: configurable linters

### ISSUE THREAD

**Issue by longspell** [castwide/solargraph#321]
Feature request to include alternate linters or make linters pluggable/configurable.

I have just been copying `diagnostics/rubocop.rb` and `diagnostics/rubocop_helpers.rb` to `cookstyle.rb` and `cookstyle_helpers.rb` where I replace the rubocop requirement at the top with cookstyle and then change `class Rubycop < Base` to `class Cookstyle < Base` (similar changes in the helper file), and then add in `diagnostics.rb` an `autoload` for my Cookstyle and CookstyleHelper files along with a `register` at the bottom.  It works fine but each update to solargraph I have to re-apply the diff and copy over the cookstyle files.  Could you look at either officially adding cookstyle or make the linters pluggable/configurable?

Thanks!

**Comment by castwide** [comment]
Plugin support was introduced this week in version 0.39.0. There are already plugins to add diagnostics for Reek and Standardb. It sounds like your changes could easily be turned into a similar plugin for Cookstyle.

Issue: https://github.com/castwide/solargraph/issues/307
Guide: https://solargraph.org/guides/plugins
Reek plugin: https://github.com/castwide/solargraph-reek
Standardrb plugin: https://github.com/bekicot/solargraph-standardrb
