### ISSUE TITLE
Version 0.39.6

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#322]
The latest Solargraph release has some significant changes.

* Speed and memory usage continue to improve
* A problem with projects using Bundler.require has been fixed
* The gem documentation cache is more efficient
* Deprecation warnings in Ruby 2.7 are gone

I highly recommend resetting your cache by running these commands:

```
solargraph clear         # Delete the entire cache
solargraph download-core # Get the latest core documentation
```

You can also improve documentation in specific projects by going to the project root and running:

```
solargraph bundle
```

The `solargraph bundle` command is especially useful for Rails apps. It makes sure yardocs are available for all your gems, and also generates more complete yardocs for certain gems like `activerecord` that use RDoc syntax instead of YARD. For some projects, `solargraph bundle` won't need to do anything, but it doesn't hurt to run it.

The cache makes Solargraph start significantly faster, so you should only run `clear` if you think there's a problem with it. The `bundle` command is non-destructive by default, so it should be safe to run if you just want to make sure you have all the gem docs you need.

**Comment by arbox** [comment]
Since you recommend installing a fresh documentation for the latest core I'd like to ask you if it's really important that core documentation matches the Ruby runtime version.
`solargraph available-cores` doesn't show e.g. `2.6.6`.

Should we provide all cores?

**Comment by castwide** [comment]
It doesn't have to be an exact match, especially if the difference is only in the minor version. Nevertheless, I'll update the online docs later this week.

**Comment by arbox** [comment]
Is it sufficient to instruct Rubygems to generate Yard documentation on every install? Or do we need to run `solargraph bundle` after every `bundle install`?

**Comment by castwide** [comment]
RubyGems should automatically generate YARD documentation when you install the gem. If you want to make sure it's configured to do so, you can enable it with this:

```
yard config --gem-install-yri
```

It doesn't hurt to run `solargraph bundle` to make sure. By default, it'll skip gems that are already documented.
