### ISSUE TITLE
[discussion] development setup

### ISSUE THREAD

**Issue by metapraveen** [castwide/solargraph#324]
Thanks for this amazing gem and the vs-code client for it @castwide. This improves ruby tooling in the editor a lot. 

I am trying to play around with this gem so I can contribute to this gem.
Where can I see the errors/logs of this gem when I am using it with vs-code client?
What is a dev setup for this so I can see the request payload coming from vs-code client and response from this gem to it?

**Comment by castwide** [comment]
Thanks!

The easiest way to get logs with VS Code is probably to use the developer console (Help -> Toggle Developer Tools). You can set the log level with the `solargraph.logLevel` option in VS Code settings. The options are `warn`, `info`, and `debug`, with `debug` providing the most detail, include request and response payloads.

If you have any other questions, I'll do what I can to help.

**Comment by metapraveen** [comment]
That helped to see the both request/response payloads 👍 

But the changes I do to the gem code directly at the installed gem path `~/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/solargraph-0.39.7` does not reflect.
 
Is it possible to run the server in debug mode using byebug or similar, so complete request path can be followed?

**Comment by castwide** [comment]
After you edit the gem, you probably need to reload VS Code to pick up the changes.

I've never tried to run the server in debug mode, but one option that might work is to start `solargraph socket` with byebug and connect to it from VS Code by setting `solargraph.transport` to `external` and `solargraph.externalServer` to the correct host and port. Unfortunately, you may still need to restart the server and/or reload VS Code after you make changes.

**Comment by metapraveen** [comment]
That worked like a gem, thanks. 
<img width="869" alt="Screenshot 2020-05-10 at 4 01 39 PM" src="https://user-images.githubusercontent.com/2039089/81501240-9abe2d00-92d7-11ea-85f2-a9220ec4bf53.png">
