### ISSUE TITLE
Support for RSpec `let` definitions

### ISSUE THREAD

**Issue by clmay** [castwide/solargraph#325]
Hey folks,

Is there any way to get the go-to-definition feature working with variables bound RSpec's `let` construct?

Suppose I have:

```ruby
let(:endpoint) { MyAPI::Path::To::Endpoint }
let(:response) {endpoint.get(params)
```

If I click `get` and go-to-definition, it says no definition found. But, if instead I have:

```ruby
endpoint = MyAPI::Path::To::Endpoint
response = endpoint.get(params)
```

Then go-to-definition will work just fine. Thoughts?

**Comment by castwide** [comment]
Variables defined in RSpec's `let` construct aren't accessible to the code maps. Those kinds of DSL-specific conventions usually require special handling.

There's a `Convention` feature in Solargraph that's intended to help fill some of those gaps. The current RSpec convention, for example, is able to map RSpec methods like `expect` and `eq` if you're editing a `*_spec.rb` file. It might be possible to extend the convention to support `let` as well, but it's a little more complicated than simply exposing methods.

**Comment by clmay** [comment]
I using a 'convention' a matter of configuration, then? If so, where can I learn more?

**Comment by castwide** [comment]
The current RSpec convention: https://github.com/castwide/solargraph/blob/master/lib/solargraph/convention/rspec.rb

Conventions are undergoing an upgrade for version 0.40.0, which I expect to release in June. The API will change slightly and it will be possible to add custom conventions through [plugins](https://solargraph.org/guides/plugins). When it's ready, I'll also release a `solargraph-rails` plugin that will utilize the new convention features. I'm working on more documentation.

**Comment by chozandrias76** [comment]
@castwide is this covered in the latest versions of SG now? I'm trying to set up my existing project with the solargraph-rails plugin and finding that I need more work to support the rspec/rake DSLs. As you have advised in other threads, I'm not setting a global domain for all my files, but I would like to know what kind of domains I might need to use to get my expects, lets and describes working properly
![image](https://user-images.githubusercontent.com/2087677/152058063-b7501ad2-a440-4da9-a497-2b03def7a7b7.png)

**Comment by liarokapisv** [comment]
Any progress on this?

**Comment by lekemula** [comment]
@clmay Please see: https://github.com/castwide/solargraph/issues/683#issuecomment-2106296460

**Comment by clmay** [comment]
That's great new, thank you for following up @lekemula !
