### ISSUE TITLE
Performance on an uber-large codebase (>25k Ruby files)

### ISSUE THREAD

**Issue by dylanirlbeck** [castwide/solargraph#330]
So I've read through a few of the performance issues already raised in this repo, but as a newcomer to Ruby/Rails I wanted to ask directly if there's anything I can do to improve the startup time of solargraph for a codebase with >25k Ruby files. Starting up solargraph with `coc-solargraph` (neovim) takes at least 20-30 minutes, and sometimes I'm not sure if Solargraph is hanging or still in the process of completing. 

What surprises me (and perhaps someone can provide me some insight on the implementation) is that it appears there is no "Solargraph cache" that would ostensibly speed up this startup time, especially when there are no code changes since the last Solargraph run.

Thanks in advance!! It is much appreciated.

EDIT: I fixed a bug with solargraph initialization, but I was still getting the error `source solargraph timeout after 5000ms`. After trying Joel's solution, things seem to be working smoothly!

**Comment by joeltaylor** [comment]
@dylanirlbeck I also work in a fairly large Ruby/Rails project and was able to reduce the startup time significantly by limiting which files were being read in my `.solargraph.yml`. (My globs are a bit atypical because the project I work in uses Rails engines liberally.)

```
---
include:
  - "apps/**/*.rb"
exclude:
  - apps/**/db/**/*
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
```

**Comment by dylanirlbeck** [comment]
Wow, thanks @joeltaylor!! So far things are working beautifully.
