### ISSUE TITLE
Server dying with Bundler enabled

### ISSUE THREAD

**Issue by arbox** [castwide/solargraph#334]
I'm experimenting with Solargraph and Bundler and have just enabled `lsp-solargraph-use-bundler` setting in my Emacs LSP config which is supposed to set `solargraph.useBundler`.

Opening `Gemfile` of a fresh Rails project I get the following messages:
```
Command "bundle exec solargraph stdio" is present on the path.
Command "bundle exec solargraph stdio" is present on the path.
Found the following clients for /tmp/form_tester/Gemfile: (server-id ruby-ls, priority -1)
The following clients were selected based on priority: (server-id ruby-ls, priority -1)

Could not locate Gemfile or .bundle/ directory

Process ruby-ls stderr finished
```

Solargraph is bundled and available from the command line. I can start `bundle exec solargraph stdio` from my bash prompt without any troubles.

Any ideas where to dig into? :)

**Comment by castwide** [comment]
Are you opening the project's folder as a workspace in Emacs? In LSP, this should set either `rootUri` or `rootPath` in the `initialize` request. I don't know much about Emacs, so you might need to ask the LSP plugin's maintainers for more information.

**Comment by arbox** [comment]
@castwide ,
thank you for not identifying it as a Solargraph problem directly. I gives me the idea where to look into :) Thank you!
I'll report here what I found out.

**Comment by amake** [comment]
I had this problem as well in a project that is one level removed from the root of the repo.

Initially I had imported the project into lsp-mode from the top of the repo.

This fixed it for me:

0. Maybe close all buffers visiting files from your project (`M-x projectile-kill-buffers` if you use projectile)
1. Remove project from the workspace (`M-x lsp-workspace-folders-remove /path/to/repo/root`)
2. Visit a file in the project. You should be prompted to import the project to lsp; choose the `I` option and manually select the appropriate folder (like `/path/to/repo/root/project`)

**Comment by arbox** [comment]
@amake , thank you for the hint, it totally makes sense if LSP determines the root using Projectile look-up. In my case it is not correct since we don't use a monorepo with the described setup. I'll investigate it again.
