### ISSUE TITLE
Failed to generate documentation

### ISSUE THREAD

**Issue by diogoleitao** [castwide/solargraph#336]
When running `solargraph bundle` on my rails project, for every gem it gives this output:
```
Documenting <gem>
<gem> YARD documentation failed
```

Environment:
- Mac OS 10.15.5
- Ruby 2.6.5
- Rails 6.0.3.1
- Solagraph 0.39.8
- Gems installed locally under `vendor/gems` folder

If you need any other information, let me know.

**Comment by castwide** [comment]
Could the problem be file permissions? For example, if you installed the gems as root, you'll also need root privileges to generate the documentation.

**Comment by castwide** [comment]
Also, you might need to add solargraph to your Gemfile and run it as `bundle exec solargraph bundle`. Since you have vendored gems, running it without `bundle` might make it attempt to document gems in the system Ruby installation (which was what originally made me think of file permissions).

**Comment by diogoleitao** [comment]
I did not install the gems with root permissions, so I don't think that file permissions is the issue. However, solargraph is installed globally and the gems were installed locally, so it might be that. I'll give it a try with `bundle exec solargraph bundle`, and get back to you with the results.

**Comment by diogoleitao** [comment]
Adding `solargraph` to the project's Gemfile fixed the issue. Thanks for the tip!
