### ISSUE TITLE
Question: What does the update_errors reporter do? 

### ISSUE THREAD

**Issue by ccarse** [castwide/solargraph#338]
What does the update_errors reporter do?

**Comment by castwide** [comment]
The intention of update_errors is to report problems that get detected while the file is currently being edited. For example, if you start typing an `if` condition without an `end`, it'll report the `if` line as the last change you made before the parser caught a syntax error.

It's still dodgy right now and might wind up deprecated. I wouldn't recommend using it unless you're specifically trying to troubleshoot and debug it.

**Comment by ccarse** [comment]
Ty!
