### ISSUE TITLE
Easy way to treat DSL method as attr_accessor?

### ISSUE THREAD

**Issue by taylorthurlow** [castwide/solargraph#340]
Let's say I have this simple class:

```ruby
class Foo
  # @return [String] the bar string
  required :bar

  def baz
    puts bar
  end
end
```

Is there an easy way to tell Solargraph to treat the `required` DSL method the same as it treats `attr_accessor` (or `attr_reader`/`attr_writer`)?

**Comment by castwide** [comment]
One option is to use a `@!method` or `@!attribute` directive:

```ruby
class Foo
  # @!attribute [r] bar
  #   @return [String] the bar string
  required :bar
end
```

Another possibility for the future is to apply a [`@!macro`](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#macro) directive to the `required` method. Proper `@!macro` support is still in development.
