### ISSUE TITLE
solargraph.org is down

### ISSUE THREAD

**Issue by bry-guy** [castwide/solargraph#343]
Hi! I've been attempting to use some of the resources found at http://www.solargraph.org/, but it appears the website is down.

Additionally, I receive an error when attempting to download documentation:
```
>  solargraph download-core
...
~/.rbenv/versions/2.7.1/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to solargraph.org:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
```

Hopefully the server just needs a kick 😄

**Comment by castwide** [comment]
Kicking it worked for now 😄

There's an ongoing issue with the DNS server. I'm working on a long-term solution.

**Comment by bry-guy** [comment]
Thanks for the quick response!

**Comment by castwide** [comment]
DNS should be fixed now. If you still have problems connecting, please feel free to reply or open a new issue.
