### ISSUE TITLE
Help with duplicate items in textDocument/definition response

### ISSUE THREAD

**Issue by muirdm** [castwide/solargraph#344]
Hi

I've just started using solargraph on a ruby project and things are working except I'm getting duplicate items when trying to jump to class/method definitions (lexical variables seem to work without duplicates). Both items' range.start is correct, but one item has a zero length range, and the other has the entire range up to the class/method's `end`.

It doesn't reproduce in a simpler setup, so I'm sure it is something funny with my project or my client. The project is made up of multiple gems and multiple Rails apps (uses bundler). I'm using Emacs lsp-mode as my client. I was hoping you knew off the top of your head what might cause this, or be able to help me troubleshoot. My first thought was circular dependencies, but I'm not sure how to proceed with that hypothesis.

**Comment by castwide** [comment]
One possible cause is having vendored gems in your workspace. If that's the case, you can try adding the vendor directory to `exclude` in a `.solargraph.yml` configuration. More information: https://solargraph.org/guides/configuration

**Comment by muirdm** [comment]
There aren't any vendored gems. However, after restarting everything for an unrelated reason, I'm not getting duplicate results anymore. If it happens again I'll try to narrow things down. Thanks!

**Comment by adonovan** [comment]
I just had the same experience: many dozens of duplicates, no vendoring, cleared by a restart.
