### ISSUE TITLE
Difficulty with strict typing and `zip`

### ISSUE THREAD

**Issue by amake** [castwide/solargraph#353]
I am evaluating using strict type checking in a project, and encountered difficulty with inference and the `Array#zip`: It seems the type of the result can't be inferred, and the only way around it is to store to an intermediate variable with a `@type` annotation.

```ruby
def foobar_bad_1
  %w[a b c].zip([1, 2, 3])
end

# @return [Array<Array(String,Integer)>]
def foobar_bad_2
  %w[a b c].zip([1, 2, 3])
end

def foobar_bad_3
  # @type [Array<Array(String,Integer)>]
  %w[a b c].zip([1, 2, 3])
end

def foobar_good
  # @type [Array<Array(String,Integer)>]
  ret = %w[a b c].zip([1, 2, 3])
  ret
end
```

```
$ solargraph typecheck --level strict
/path/to/solargraph-test-zip.rb:1 - Untyped method #foobar_bad_1 could not be inferred
/path/to/solargraph-test-zip.rb:6 - #foobar_bad_2 return type could not be inferred
/path/to/solargraph-test-zip.rb:10 - Untyped method #foobar_bad_3 could not be inferred
3 problems found.
```

Is there any better way to handle this? I ask because _`zip` leading into some sort of list-oriented processing that is directly returned_ is a common idiom in my codebase and this could be painful to deal with.

**Comment by castwide** [comment]
There are some gaps in the core API documentation that can lead to false positives in strict type checking. The current work on [RBS for Ruby 3](https://developer.squareup.com/blog/the-state-of-ruby-3-typing/) might fix the problem, but in the meantime I've been fixing them by attrition in the [CoreFills](https://github.com/castwide/solargraph/blob/master/lib/solargraph/core_fills.rb) module.

I'll include a fill for `Array#zip` in the next patch release.

**Comment by castwide** [comment]
Released in 0.39.14.

**Comment by amake** [comment]
Thanks! That does seem to fix it.

Is there a good way to tell if a new CoreFill is needed?

**Comment by castwide** [comment]
> Is there a good way to tell if a new CoreFill is needed?

Not an easy way, but this is a quick and dirty script I wrote to analyze the core:

```ruby
require 'solargraph'

api_map = Solargraph::ApiMap.new
typed = []
untyped = []
api_map.pins
       .select { |pin| pin.is_a?(Solargraph::Pin::BaseMethod) }
       .each do |pin|
  if pin.typify(api_map).defined? || pin.probe(api_map).defined? || pin.docstring.has_tag?(:overload)
    typed.push pin
  else
    untyped.push pin
  end
end
puts untyped.map(&:path)
puts "#{typed.length} typed, #{untyped.length} untyped"
```

It reports 1910 typed and 185 untyped core methods. Those numbers aren't 100% perfect, though.

**Comment by amake** [comment]
Cool, thanks!
