### ISSUE TITLE
Installing the solargraph gem

### ISSUE THREAD

**Issue by zaeemnalla** [castwide/solargraph#355]
This is probably not an issue with solargraph but rather an issue with my ruby installation/setup (ruby noob here)

When attempting to install the gem I get the following:
```
$ sudo gem install solargraph
Password:
ERROR:  Error installing solargraph:
	rubocop requires Ruby version >= 2.4.0.
```

I've checked the following which may help for someone to provide suggestions:

- `$ ruby --version` shows `ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`
- `which ruby` shows `/Users/zaeem/.rbenv/shims/ruby`
- I tried installing ruby 2.5.7 with `ruby-build 2.5.7 ~/.runtimes/Ruby25x` (after seeing this command somewhere). In the `/Users/zaeen/.runtimes/` directory I've got the following installations

```
$ ll /Users/zaeem/.runtimes/
total 0
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 Ruby19
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 Ruby21x
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 Ruby23x
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 Ruby24x
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 Ruby25x
```

- Under `/Users/zaeem/.rbenv/versions` I've got the following though (don't really remember how I got these here - perhaps installed them with rbenv instead of ruby-build directly)
```
$ ll /Users/zaeem/.rbenv/versions
total 0
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 1.9.3-p484
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 2.1.8
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 2.3.7
drwxr-xr-x  7 zaeem  ANT\Domain Users  224 Dec 18  2019 2.4.4
```

I have `$HOME/.rbenv/shims` in my PATH too. I definitely have a version of ruby installed to satisfy solargraph (i.e. 2.4.4 and 2.5.x) but it seems like I need to point my system to one of those. Any ideas what I need to do?

**Comment by zaeemnalla** [comment]
Looks like I can use `rbenv global <version>` to change the version globally as per [these instructions](https://makandracards.com/makandra/21545-rbenv-how-to-switch-to-another-ruby-version-temporarily-per-project-or-globally) and then if I need a particular version for a particular project I can just set it locally with `rbenv local <version>`.

**Comment by arbox** [comment]
@zaeemnalla , you definitely have an Ruby version `>= 2.4.0`. But you're installing `solargraph` globally which causes the shell to look up a system ruby version.

**Comment by zaeemnalla** [comment]
Without sudo I was getting the following 

```
gem install solargraph
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
```

And checking the ownership of that directory shows that's owned by root and group ownership of wheel as expected

```
$ ll /Library/Ruby/Gems/
total 0
drwxr-xr-x  8 root  wheel  256 Feb 23  2019 2.3.0
```

I also ran the following to see why `ruby -v` is pointing to (or using) 2.3.7p456 and I saw that it's using the one probably pre-installed with the system (it says set by `/Users/zaeen/.rbenv/version` even though I don't have such a file)

```
$ rbenv versions
* system (set by /Users/zaeen/.rbenv/version)
  1.9.3-p484
  2.1.8
  2.3.7
  2.4.4
```

```
$ rbenv global
system
```

Anyway switching to 2.4.4 globally with `rbenv global 2.4.4` unblocked me
