### ISSUE TITLE
Solargraph extension for VSCode fails to start and wants strange permissions

### ISSUE THREAD

**Issue by jakehawken** [castwide/solargraph#356]
When opening a single ruby file (I don't have any ruby projects, as I just use it for scripting), Solargraph attempts and fails to initialize the language server. The stated reason is that it can't access my photo library, which seems like an awfully strange reason for a _language server_ to not work. The given error code is -32603.

![Image 8-16-20 at 12 17 PM](https://user-images.githubusercontent.com/2860738/90343675-abadc700-dfc7-11ea-8f19-05453b0d8f5c.JPG)

**Comment by castwide** [comment]
Are you opening a folder in VS Code? Solargraph will typically try to map the entire folder's contents. This is fine is you're opening a specific project folder, but less desirable if you're opening your entire home directory or something.

If that's the case, there's a couple things you can try:

1. Go to File -> Close Folder, then go to File -> Open File to open the Ruby script without an active folder.

2. If you'd rather have the entire directory available in VS Code's Explorer, you can tell Solargraph not to map the directory with a `.solargraph.yml` file. Example steps:
- `cd ~`
- `solargraph config` # This will create a default .solargraph.yml file
- The config's default `include` section looks something like this:
    ```
    include:
    - **/*.rb
    ```
- Change it to this:
    ```
    include: []
    ```

That configuration will only map individual Ruby files when you open them in an editor.
