### ISSUE TITLE
In-Memory Database

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#36]
Move the ApiMap's data store to an in-memory Sequel database to improve memory usage and query performance.

I've developed a rough version that passes 90% of the specs and resolves some garbage collection problems.

**Comment by castwide** [comment]
The latest changes may preclude the need for Sequel. Refactoring the ApiMap, in particular, brought significant speed and performance improvements. At this point, the cost of a database dependency may outweigh its benefits.

**Comment by douglascamata** [comment]
Can't it be just a in-memory normal hash? SQL is a bit overkill, imho.

**Comment by castwide** [comment]
@douglascamata I added an email address to my GitHub profile. If you want to contact me there, we should be able to work something out.

**Comment by castwide** [comment]
While improvements to maps and indexing are an ongoing concern, the current plan is to implement them using core features instead of adding a Sequel dependency.
