### ISSUE TITLE
Solargraph no longer gives autocomplete on initialization blocks

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#360]
Lets say we have a `Paket` model and this model has members like `id`, `name`, `password` etc..

Let's declare a block:

```ruby
Paket.new do |pk|
  pk. # < I expect autocomplete for the member sof Paket here. Instead none given.
end
```

However, If I explicitly give param yard doc, then all works:

```ruby
# @param [Paket]
Paket.new do |pk|
  pk.na # < name is given as autocomplete suggestion.
end
```

**Comment by castwide** [comment]
The autocomplete suggestions will only be available with a `@param` tag on the call or a `@yieldparam` tag on the `initialize` function. Example:

```ruby
class Paket
  # @yieldparam [self]
  def initialize; end
end

Paket.new do |p|
  p. # < recognized as a Paket
end
```

I assume, in your example, `Paket` is a subclass of `ActiveRecord::Base`. A more practical solution would be to add an `@!override ActiveRecord::Base#initialize` to supply the `@yieldparam`. Unfortunately, `@!override` doesn't work correctly with `initialize` methods. I'll work on a fix for it.

**Comment by gencer** [comment]
Few versions back, this was working. I could get autocomplete without explicitly giving `param` or `yieldparam`. I believe something changed since than.

This is actually Sequel model. I am generating Sequel model and their methods / fields by rake task so that Solargraph can parse what is in it.

**Comment by gencer** [comment]
Fred, you were right. It is how you said was.

I checked two different projects. It seems I've added `yieldparam` as you said for the initialize. That's why it is not working on current project because this project seems have older rake task I wrote recent year.

Sorry for the confusion. I will leave this issue open as you said about `override` issue. Please feel free to close if you think you can track this down on your own.

Gencer.

**Comment by castwide** [comment]
The minor bug with `@!override` tags on `#initialize` methods is fixed in the master branch.
