### ISSUE TITLE
How do I change the logging level?

### ISSUE THREAD

**Issue by iftheshoefritz** [castwide/solargraph#365]
Once I get the answer to this I'm happy to do a PR to add to the docs.

I can see that the host has a a logLevel option which is set by default to WARN, and it looks like the only way to update it is to call `host.configure`.

The only code that I can see which does that is in `lib/solargraph/language_server/message/initialize.rb`, `LanguageServer::Message::Initialize` calls `host.configure` with `params['initializationOptions']`, which can include `logLevel`. The trail goes dead for me there.

Is the _client_ responsible for setting the log level? Or is there something I set when the server starts?

**Comment by castwide** [comment]
Yes, the client sends it in the `initialize` request params, e.g.:

```
{
  "initializationOptions": {
    "logLevel": "debug"
  }
}
```

The `initialize` request specification: https://microsoft.github.io/language-server-protocol/specification#initialize

**Comment by iftheshoefritz** [comment]
Thanks for the quick answer 👍
