### ISSUE TITLE
How does this align with Ruby 3.0?

### ISSUE THREAD

**Issue by wagenet** [castwide/solargraph#369]
https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/

**Comment by castwide** [comment]
I haven't tested with Ruby 3 yet, but here are a few considerations for the future:

* RBS support is on the roadmap. The specifics are still up for debate. More information: https://github.com/castwide/solargraph/issues/194#issuecomment-671910723
* Parallel execution is liable to be extremely beneficial to performance. One example: when the server is loading a workspace, parsing each individual file is an orthogonal operation. Spreading those processes across multiple cores should make initialization significantly faster. It looks like this will be possible in Ruby 3 with Ractors (which seem to have replaced the previous proposal of Guilds).
* Some of the language changes will require explicit support, but from what I've seen, many of the new features will be limited to changes in how `Solargraph::Parser` handles ASTs.

**Comment by castwide** [comment]
Small update: I confirmed that Solargraph passes smoke tests under Ruby 3.0.0-preview1. The specs succeed and the language server worked as expected in a short test with VS Code.

**Comment by castwide** [comment]
Ruby 3 is now passing on Travis CI as well. Please feel free to open a new issue if a specific problem arises.

**Comment by ddoherty03** [comment]
I tried `solargraph available-cores`.  Any chance 3.0.0 will be added?  Related: would having this result in faster startup?  Is that the idea.  Totally new to lsp-mode.  Thanks.

**Comment by olistik** [comment]
@castwide as @ddoherty03 pointed out, should we expect to see 3.0.x as a result of `solargraph available-cores`?
I don't want to pressure you on this, just asking if 3.0.x support requires some configurations or if it's still in the works (I'm new to this project).

```
λ solargraph download-core 3.0.1
Downloading docs for 3.0.1...
ERROR: Version 3.0.1 is not available from https://solargraph.org/download
Run `solargraph available-cores` for a list.
```

Also, the link https://solargraph.org/download returns a 404 and I'm not sure if there's such a link in the web site and if there's a better place to notify this issue (I'll gladly apply this tiny fix if possible 😃).

**Comment by castwide** [comment]
Starting with 3.0, the documentation in the Ruby source has become less complete, so generating yardocs from it is no longer reliable. The plan going forward is to generate core documentation from RBS instead. (One happy side effect of this change: downloading cores should no longer be necessary.)

In the meantime, the most recent core documentation available, 2.7.2, should work with 3.0.x. I'll post a new issue to track progress on RBS integration.

**Comment by olistik** [comment]
@castwide 

> Starting with 3.0, the documentation in the Ruby source has become less complete [..]

That's interesting, I didn't know that. 🎩 

>  I'll post a new issue to track progress on RBS integration.

Do you feel like the current documentation (both in the command line and in the website) could benefit from an update? I suppose other people like me could end up being a little confused. 🙂

**Comment by castwide** [comment]
It couldn't hurt. There's already a notification if you run `solargraph download-core` without an argument. It tells you there's no documentation available for the current version and what version it's going to use instead. I'll add a similar message if a specified version isn't available.
