### ISSUE TITLE
YARD's List type doesn't appear to be recognized

### ISSUE THREAD

**Issue by wagenet** [castwide/solargraph#370]
```
List(String, Symbol, #to_s)
```
https://yardoc.org/types#see_results

**Comment by wagenet** [comment]
It's possible this is a false alarm and there's another confounding factor.

**Comment by castwide** [comment]
Solargraph parses the type, but expects it to refer to a concrete `List` class.

Order-dependent lists have limited support right now. Their parameters are mostly ignored in mapping and inference, e.g., `Array(String, Symbol, #to_s)` will simply be treated as a generic Array. More info: #362

**Comment by wagenet** [comment]
Feel free to close this as a duplicate
