### ISSUE TITLE
What options exist for creating metadata with references to source in different files?

### ISSUE THREAD

**Issue by iftheshoefritz** [castwide/solargraph#373]
I have YARD files outside of my source to document attributes that are created at runtime by some metaprogramming. This is great for autocomplete, but go-to-definition takes me to the YARD file instead of to the actual code. 

I have some half-baked ideas and I'm not sure if they would work / which if any has the most merit:

- a lens would give a clickable action that could take me to the source, but that's not going to be linked to the normal go-to-definition flow of clients (I'd be sad if this was the best option)
- a custom YARD directive that can take a reference location in another file
- or is there some existing YARD thing that can accomplish this?
- a solargraph plugin

Which of these seems like a good match for what I'm trying to achieve? If there's a clear winner, any hints about what to read up on next would be appreciated.

**Comment by castwide** [comment]
The best option is probably to add a custom `Convention` through a plugin. I'm currently working on a similar solution to improve Rails support.

The bad news is that proper convention support won't be released until version 0.40.0. The good news is that it's available in the `master` branch, and I hope to release 0.40.0 sometime next week.

Here's a simple example of a convention that adds a `Foo` class to the API map:

```ruby
require 'solargraph'

class MyConvention < Solargraph::Convention::Base
  def global yard_map
    Solargraph::Environ.new(pins: parse_pins)
  end

  private

  def parse_pins
    Solargraph::SourceMap.load_string(%(
      class Foo; end
    )).pins
  end
end

Solargraph::Convention.register MyConvention
```

The `Foo` pin is generated without a filename, so it doesn't get included in go-to-definition results. That fixes half the problem. The other half is resolving a "virtual" method to a concrete class/module definition. For example, if you have `Foo` defined in your code and `Foo#bar` defined in a convention, you probably want `Foo#bar`'s go-to-defintion to find `Foo`. I'm not sure of the best way to handle it. If you have any thoughts, please let me know.

You can find more examples of conventions in the `lib/solargraph/convention` directory.

**Comment by iftheshoefritz** [comment]
> I'm currently working on a similar solution to improve Rails support.

That is my exact use case, the YARD I'm generating is based on ActiveModel attributes, and slowly working on an annotate style gem that updates Solargraph's knowledge every time `rake db:migrate` runs.

Will give the second part of the problem some thought!

**Comment by iftheshoefritz** [comment]
@castwide (since I assume the pains returned from `parse_pins` are stored in a global source map) would it be terrible if `Solargraph::Location` was mutable? Then we could update the location of each pin generated for a class?

**Comment by iftheshoefritz** [comment]
@castwide what about something like this:

```
class MyConvention < Solargraph::Convention::Base
  def global yard_map
    puts "*"*100
    puts yard_map.class
    Solargraph::Environ.new(pins: parse_pins)
  end

  private

  def parse_pins
    klasses = [MyBook] # use ActiveRecord::Base.descendants to find the real list
    klasses.each do |klass|
      source = Solargraph::Source.load(Rails.root.join('app', 'models', "#{klass.name.underscore}.rb").to_s)
      map = Solargraph::SourceMap.map(source)
      class_location = map.first_pin(klass.name).location

      klass.columns.map do |col|
        Solargraph::Pin::Method.new(name: col.name, comments: type_translation[col.type], location: class_location)
      end
    end
  end

  def type_translation
    {
      decimal: 'Decimal',
      integer: 'Int',
      date: 'Date',
      datetime: 'DateTime',
      string: 'String',
      boolean: 'Bool'
    }
  end
end
```

**Comment by iftheshoefritz** [comment]
I'm now thinking that it's going to be easier to parse annotate than to try load all of activerecord and establish a DB connection in a plugin. This looks pretty easy since annotate is essentially just outputting `column.type` or `column.sql_type`. And it's pretty popular in rails projects.

**Comment by iftheshoefritz** [comment]
Update: I have autocomplete and go-to-definition working for simple cases from a plugin that parses annotate. Soon to be released as `solargraph_rails`.
