### ISSUE TITLE
Unresolved type HTTP::Error for variable eTypecheck

### ISSUE THREAD

**Issue by kadru** [castwide/solargraph#375]
Hi, I'm getting `Unresolved type HTTP::Error for variable e` error when using typecheck reporter with the default level. This a example code:

```ruby
def post(data)
  http.post("url", form: { data: data } )
rescue HTTP::Error => e # <= Type check error occurr here
  # my rescue code
end
```

I believe that is a bug and not intended behavior.

**Comment by castwide** [comment]
Can you confirm where HTTP::Error is defined? That doesn't look like anything from the stdlib, unless it's supposed to be `Net::HTTPError`. I don't see it defined in common web libraries like Rails and Sinatra, either.

**Comment by kadru** [comment]
`HTTP:Error` is defined from the gem `http` version: 4.4.1

**Comment by castwide** [comment]
This code passes strict typechecking for me:

```ruby
require 'http'
def foo
rescue HTTP::Error => e
  puts e.message
end
```

One possibility is missing documentation, which you should be able to install with either `yard gems` or `solargraph bundle`, depending on your setup.

**Comment by kadru** [comment]
`yard gems` resolves the issue.

Thanks!
