### ISSUE TITLE
Unresolved type undefined for param when using literal values

### ISSUE THREAD

**Issue by opiation** [castwide/solargraph#377]
It appears that literals are not currently supported by the type checker.  [Yard does seem to support literal values in documenting types][0] and so does [RBS][1].  Granted the Yard examples don't show string or symbol literals, it does mention _constant_ values with an example using `true`.

This error is reproducible as follows

```ruby
class Feature
  # @param ["open", "close"] state
  # @return ["finished"]
  def my_example(state)
    "finished"
  end
end
```

```
Unresolved type undefined for state param on Feature#my_example
Unresolved return type "finished" for Feature#my_example
```

Or with symbol literals

```ruby
class Feature
  # @param [:open, :close] state
  # @return [:finished]
  def my_symbol_example(state)
    :finished
  end
end
```

```
Unresolved type undefined for state param on Feature#my_example
Unresolved return type :finished for Feature#my_example
```

I haven't found any solargraph documentation explicitly stating this is expected to work so I would guess this qualifies as a feature request.  Let me know if more information is needed.

[0]: https://rubydoc.info/gems/yard/file/docs/GettingStarted.md#declaring-types
[1]: https://github.com/ruby/rbs/blob/master/docs/syntax.md#literal-type

**Comment by castwide** [comment]
This is fixed as of v0.40.3. See also #398
