### ISSUE TITLE
Rubocop 1.0 is Out

### ISSUE THREAD

**Issue by jherdman** [castwide/solargraph#380]
The gemspec currently specifies `~> 0.52`. It probably ought to be a lot more permissive than that.

**Comment by rmehner** [comment]
Ran into this as well, as [standard](https://github.com/testdouble/standard) depends on Rubocop 1.0 and if I do an update, Solargraph is automatically downgraded to 0.13.2.

Thank you!

**Comment by ghedamat** [comment]
@castwide would you be ok with a pr with this change? https://github.com/zaratan/solargraph/commit/2b481162ced4ec4792486cbfda68e5925b98fa41
