### ISSUE TITLE
solargraph bundle does not work for local gems

### ISSUE THREAD

**Issue by baelter** [castwide/solargraph#384]
Git gem with local path config in bundler does not work with solargraph bundle

Eg.

MyProject/Gemfile
```
...
gem 'my_gem', git: 'https://github.com/my_gem/my_gem.git', branch: 'master'
...
```

```
 $ bundle config
...
local.my_gem
Set for the current user (/Users/me/.bundle/config): "/Users/me/code/my_gem"
```

```
MyProject $ solargraph bundle
Documenting my_gem 0.1.0
my_gem 0.1.0 YARD documentation failed
1 gem could not be documented. You might need to run `bundle install`.
```

**Comment by castwide** [comment]
Does this work with `bundle exec solargraph bundle`?

**Comment by baelter** [comment]
Yes it does. Have not been adding solargraph to Gemfiles up until now. But might have to start doing that then? Or could this be sorted anyway?

**Comment by castwide** [comment]
It might be necessary here because `my_gem` gets installed as a local gem. In projects where the Bundler installs the gems at the system level, you can usually get away with excluding Solargraph from the Gemfile.
