### ISSUE TITLE
"Unable to load the EventMachine C extension" message when trying to run Solargraph 0.18.3 gem

### ISSUE THREAD

**Issue by WToorenburghEasyMarkit** [castwide/solargraph#39]
OS: Windows 10 Pro 1709 16299.334
Solargraph gem version: 0.18.3
Ruby version: 2.4.4
VS Code version: 1.22.2
VS Code Solargraph extension version: 0.15.0

Hey there,

I've been using Solargraph through the VS Code extension for a while now. A few days ago, the extension was saying that version 18 was available (moving up from 17, I believe), but would fail to update for unknown reasons. I also noticed that the gem wasn't actually running. So, I tried uninstalling and re-installing the gem, and the install failed because it couldn't find 'make'. I then uninstalled Ruby and the RIDK tools, and reinstalled them using the combined Ruby and RIDK installer from the Ruby for Windows installer (Using the `Ruby+Devkit 2.4.4-1(x64)` link from [here](https://rubyinstaller.org/downloads/)). The install succeeded, so I ran `gem install solargraph`, which succeeded after about 5 minutes. now, when I run `solargraph` from the command line, I get this output:

<details>
 <summary>Output:</summary>
<p>

```ps
PS C:\Users\user> solargraph
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solargraph-0.18.3/lib/solargraph/shell.rb:6:in `<top (required)>'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Tools/Ruby24-x64/lib/ruby/gems/2.4.0/gems/solargraph-0.18.3/bin/solargraph:5:in `<top (required)>'
        from C:/Tools/Ruby24-x64/bin/solargraph:23:in `load'
        from C:/Tools/Ruby24-x64/bin/solargraph:23:in `<main>'
```

</p>
</details>

Apologies if this is a simple issue; I'm not the most well versed in Ruby.

**Comment by castwide** [comment]
It looks like EventMachine has a known problem with Ruby 2.4+ on Windows. They have an [open issue and a possible workaround](https://github.com/eventmachine/eventmachine/issues/820#issuecomment-368267506).

Other than that, I can confirm that EventMachine works on Windows 10 with Ruby+DevKit 2.3.3.

**Comment by WToorenburghEasyMarkit** [comment]
Beautiful! That did the trick. Thank you kindly!
