### ISSUE TITLE
Missing BigDecimal info

### ISSUE THREAD

**Issue by iftheshoefritz** [castwide/solargraph#393]
It seems like Solargraph doesn't know about BigDecimal. I expected at least the same info I get with `BigDecimal.new("40").public_methods(false)`, but there's nothing found by Solargraph.

I understand that `BigDecimal` isn't required by default, but it's pretty fundamental (I suppose especially to Rails where every decimal is loaded as BigDecimal. 

Does this belong in a plugin, or in project-specific config? Or is it something that Solargraph should do?

Example:

When I try autocomplete for `BigDecimal("40").`:

```
[Trace - 07:14:39 AM] Sending request 'textDocument/completion - (23)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/fritzmeissner/devprojects/school-api/app/controllers/v1/season_classes_controller.rb"
  },
  "position": {
    "line": 7,
    "character": 23
  },
  "context": {
    "triggerCharacter": ".",
    "triggerKind": 2
  }
}


[Trace - 07:14:40 AM] Received response 'textDocument/completion - (23)' in 333ms.
Result: {
  "items": [],
  "isIncomplete": null
}
```

I also tried `BigDecimal.new("40")` in case it's the type casting syntax that breaks things, same result.

**Comment by castwide** [comment]
`BigDecimal` will work if you `require 'bigdecimal'` somewhere in your code. Since Rails requires it internally, it might make sense to add it automatically in the solargraph-rails plugin.

**Comment by iftheshoefritz** [comment]
Ah awesome.

**Comment by castwide** [comment]
This should be resolved, or at least resolvable. Any related problems, please let me know.

**Comment by iftheshoefritz** [comment]
I actually didn't manage to make this work by adding it to the plugin, but I'll re-open if I have more thoughts on the issue

**Comment by castwide** [comment]
There are definitions for both the `BigDecimal` class and a `Kernel#BigDecimal` method, so the documentation you see might depend on which one is being referenced.

![image](https://user-images.githubusercontent.com/3704922/153531791-ad46764a-ca7b-4a08-869c-4f88b9c9c9aa.png)

![image](https://user-images.githubusercontent.com/3704922/153531828-bb3fdbcb-e542-40c4-b4c6-64c20750fd1d.png)
