### ISSUE TITLE
Require Ruby >= 2.4

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#394]
From what I can tell, less than 1% of users are still running Ruby < 2.4. The burden of supporting earlier versions is no longer worth the effort. Updating also comes with important benefits:
- It fixes outstanding issues with RuboCop 1.0 (#391)
- It enables use of kramdown instead of maruku

This change will be released in version 0.40.0.

**Comment by Nitrodist** [comment]
Do it, you're the best 🙏
