### ISSUE TITLE
Temp directory formatting breaks rubocop configuration

### ISSUE THREAD

**Issue by colinux** [castwide/solargraph#401]
Last patch release 0.40.1 ignores `.rubocop.yml` files, because rubocop sees filepath of a temporary file, which is not in the directory of the `.rubocop.yml` workspace, so hierarchical config is not applied.

The diagnosis are not affected, because code is passed as stdin. v0.40.0 is ok.

**Comment by castwide** [comment]
Confirmed. This is a nasty conundrum: autocorrect only works on a physical file (not stdin), and the -c argument for specifying the config doesn't work with autocorrect. That's how it appears for now, anyway. This issue's on the roadmap.

**Comment by jimeh** [comment]
@colinux PR #403 should fix this issue. If you want to test the PR I'd be happy to try and resolve any issues you might run into.

**Comment by colinux** [comment]
I can confirm PR #403 works very well. Thanks a lot !
