### ISSUE TITLE
Solargraph is correctly diagnosing rubocop errors; however, it is "fixing" them incorrectly (formatting)

### ISSUE THREAD

**Issue by thornomad** [castwide/solargraph#406]
Hello — I use solargraph with coc-nvim and coc-solargraph.  I originally [opened the issue at coc-solargraph](https://github.com/neoclide/coc-solargraph/issues/54) there but it was suggested the issue may with the solagraph language server itself.  

#### Problem

When applying auto-correct _formatting_ to a file, solargraph is **not** sourcing my project folder's`.rubocop.yml` file (it does use my `$HOME/.rubocop.yml` setting).

This only is an issue with solargraph applying rubocop _formatting_ autocorrect; it _does_ source the correct file when displaying linting errors in vim.

#### Work around

If I copy the `.rubocop.yml` file from my project directory into my `$HOME` directory, this fixes the problem.  But my rubocop settings for auto-correct are no longer project based and my projects have different settings.  Gack.

Do you think this is an issue with the solargraph Gem itself ?  I am not sure how to test the language server without relying on the coc-nvim implementation but would be willing to with instruction.  More details and some debug logs are [at the original issue](https://github.com/neoclide/coc-solargraph/issues/54)

Thanks in advance for any help.

**Comment by KevinBerthier** [comment]
Same issue since version `0.40.1` for me on VSCode with vscode-solargraph

**Comment by castwide** [comment]
This is a known issue that will be resolved in 0.41.0. See #403

**Comment by castwide** [comment]
Fix released in v0.40.3.

**Comment by ThomasF34** [comment]
Same here ! I have the issue while using v0.40.4

**Comment by mario-amazing** [comment]
Same in 0.45.0
