### ISSUE TITLE
Not finding gems in file

### ISSUE THREAD

**Issue by npearson72** [castwide/solargraph#407]
I keep getting the warning: [RequireNotFound] [W] Required path (gem) could not be resolved.

<img width="731" alt="Screen Shot 2021-01-21 at 11 26 26 AM" src="https://user-images.githubusercontent.com/1323414/105330990-9aeb2800-5bdb-11eb-8b9c-1dcfa6ada2ba.png">

I have the following in my solagraph file:

```
---
include:
  - '**/*.rb'
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - '.bundle/**/*'
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
plugins: []
max_files: 5000
```

I've tried removing `require_not_found` reporter, but nothing fixes the issue.

Any ideas?

**Comment by castwide** [comment]
That error usually means that the gem is either not installed or Solargraph can't find it among the expected load paths. In the latter case, one cause is running a system-wide installation of Solargraph while the gem in bundled inside the project, e.g., in a `.bundle` directory.

Removing the `require_not_found` reporter should work, but you might need to restart the editor.

**Comment by npearson72** [comment]
The gem is definitely installed:

```
➜ gem list | grep solargraph
solargraph (0.40.2, 0.40.1, 0.40.0)
```

```
➜ solargraph --version
0.40.2
```

I'm using the `coc-solargraph` extension for neovim, which bundles the language server with it:

<img width="726" alt="Screen Shot 2021-01-22 at 6 22 57 PM" src="https://user-images.githubusercontent.com/1323414/105516782-f3efb480-5cde-11eb-9d79-d09e44fa9103.png">

Have tried removing `require_not_found` and restarting the server. Nothing works.

Any other ideas?

**Comment by castwide** [comment]
Sorry, I meant the `css_parser` gem. If it's installed, try running `yard gems` to generate the documentation.

**Comment by npearson72** [comment]
Yeah, running `yard gems` did the trick. Thanks.
