### ISSUE TITLE
Variables aren't appearing in dropdown

### ISSUE THREAD

**Issue by garyking** [castwide/solargraph#41]
Not sure why, but for some of my large Ruby projects, variables don't appear in auto-complete dropdowns.

There aren't any hints in the output about this, either.

**Comment by castwide** [comment]
One known limitation is that variables will not appear in completion lists unless they have an explicit assignment. Examples of instance variables with and without assignments:

![image](https://user-images.githubusercontent.com/3704922/38775152-2f087594-4049-11e8-8dc5-41a45db4297e.png)

![image](https://user-images.githubusercontent.com/3704922/38775154-3618b7fe-4049-11e8-9ae7-e571fd8d75ed.png)

Variables in completions will also be limited to those that are determined to be visible within the current context. Examples of variables inside and outside of context:

![image](https://user-images.githubusercontent.com/3704922/38775169-a4790618-4049-11e8-9ee2-9fbd2eaaeb19.png)

![image](https://user-images.githubusercontent.com/3704922/38775175-b8bc5346-4049-11e8-9eed-e11e6749fc36.png)

If you have an example of a variable that ought to be visible but isn't, please let me know.

**Comment by garyking** [comment]
I think the problem I had fixed itself when I closed and re-opened the Ruby workspace. Otherwise, the variable dropdowns do seem to follow the rules you mentioned.
