### ISSUE TITLE
Lost Rails (basic) autocompletion after `0.39.0+`

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#410]
I stopped getting some autocompletion on gems. Especially on Rails. I know Rails integration is never been easy and complete. I am not talking about total completion of Database (ActiveRecord) or Controller or ActiveSupport. But some basic autocompletion like `Rails.root` or `Rails.env` or even `Rails.# anything..`

With <s>0.40.0</s> 0.39.0 it get worse. I was able to get many methods and classes before 0.39 but not anymore. See the difference yourself:

## v0.38.0 Behavior

`Rails.env` documentation:

![image](https://user-images.githubusercontent.com/1711576/106371317-1c794d80-6374-11eb-9ff5-86db630b6cbc.png)

Rails Autocompletion:

![0 38 0 gif](https://user-images.githubusercontent.com/1711576/106371358-88f44c80-6374-11eb-9b0e-21e3ee666b3b.gif)

## v0.39.0+ Behavior

No autocomplete (no documentation):

![0 40 0 gif](https://user-images.githubusercontent.com/1711576/106371359-8abe1000-6374-11eb-88b0-457ab7e2bc8a.gif)

**Comment by castwide** [comment]
This should be fixed in the current release (0.42.3). If it's still an issue, please feel free to reopen.

**Comment by gencer** [comment]
Hey @castwide, If I do this:

```bash
$ solargraph bundle
```

Then restart Solargraph, I still have this problem. However, After cleaning cache via:


```bash
$ solargraph clear
```

And restart, Everything works as expected. So, I believe we should avoid `bundle`?
