### ISSUE TITLE
Already initialized constant BenchMark::*

### ISSUE THREAD

**Issue by stufro** [castwide/solargraph#412]
When running rake in my rails project I get the below warnings:

```
/home/dev/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:124: warning: already initialized constant Benchmark::BENCHMARK_VERSION
/home/dev/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/benchmark-0.1.1/lib/benchmark.rb:124: warning: previous definition of BENCHMARK_VERSION was here
/home/dev/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:395: warning: already initialized constant Benchmark::Tms::CAPTION
/home/dev/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/benchmark-0.1.1/lib/benchmark.rb:395: warning: previous definition of CAPTION was here
/home/dev/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:398: warning: already initialized constant Benchmark::Tms::FORMAT
/home/dev/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/benchmark-0.1.1/lib/benchmark.rb:398: warning: previous definition of FORMAT was here
/home/dev/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:561: warning: already initialized constant Benchmark::CAPTION
/home/dev/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/benchmark-0.1.1/lib/benchmark.rb:561: warning: previous definition of CAPTION was here
/home/dev/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:564: warning: already initialized constant Benchmark::FORMAT
/home/dev/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/benchmark-0.1.1/lib/benchmark.rb:564: warning: previous definition of FORMAT was here
```

I believe this is because the benchmark gem is part of core ruby, but is also being required by solargraph as per this commit f3a448345861310fba4e33dcde5f7b4a8dd3b962. Being required twice is causing the constants to be defined again. Does the benchmark gem need to be explicitly required when it is already part of core ruby?

When I remove solargraph gem from my Gemfile, the warnings disappear.

**Environment**
Ruby: 2.7.2
Rails: 5.2.4.4
Rake: 13.0.3
Solargraph: 0.40.3

**Comment by castwide** [comment]
Even though `benchmark` is in the stdlib, it still needs to be required because it's not loaded as part of the Ruby core.

I suspect this problem arises because something is requiring `benchmark` before Bundler reconfigures the load paths. Before `Bundler.setup`, it loads the stdlib version. Afterwards, `benchmark` points to the gem version, so it gets reloaded.
