### ISSUE TITLE
Feature request: support for "standard" linter

### ISSUE THREAD

**Issue by JosephLing** [castwide/solargraph#422]
Awesome project!

Would it be possible in the future to get support for https://github.com/testdouble/standard ? Or guidance in how to implement the feature please?

It is described as a wrapper around Rubocop and exposes nearly all the same CLI and has been used in the past to plugin into an editor: https://github.com/testdouble/SublimeLinter-contrib-standardrb. So hopefully a lot of the same code will be able to be used.

**Comment by castwide** [comment]
There's a plugin for it: https://github.com/bekicot/solargraph-standardrb
