### ISSUE TITLE
Unable to install gem on macOS 10.15.7

### ISSUE THREAD

**Issue by siegel** [castwide/solargraph#427]
I'm developing a new LSP client, and I'd like to test Ruby support using Solargraph.

However, attempting to install Solargraph fails, with the following Terminal transcript:

```
gem install --user solargraph
Successfully installed yard-0.9.26
Successfully installed tilt-2.0.10
Successfully installed thor-1.1.0
Successfully installed unicode-display_width-2.0.0
Successfully installed ruby-progressbar-1.11.0
Successfully installed ast-2.4.2
Successfully installed parser-3.0.1.0
Successfully installed rubocop-ast-1.4.1
Successfully installed regexp_parser-2.1.1
Successfully installed rainbow-3.0.0
Successfully installed parallel-1.20.1
Successfully installed rubocop-1.12.1
Successfully installed reverse_markdown-2.0.0
Successfully installed kramdown-2.3.1
Successfully installed kramdown-parser-gfm-1.1.0
Building native extensions. This could take a while...
ERROR:  Error installing solargraph:
	ERROR: Failed to build gem native extension.

    current directory: /Users/siegel/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20210407-46546-1p9tvoz.rb extconf.rb
creating Makefile

current directory: /Users/siegel/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
make DESTDIR\= clean

current directory: /Users/siegel/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
make DESTDIR\=
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19/ruby/config.h', needed by `adj_matrix.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Users/siegel/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4 for inspection.
Results logged to /Users/siegel/.gem/ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4/gem_make.out
```

I did consult the [Troubleshooting Solargraph](https://solargraph.org/guides/troubleshooting) instructions, but they appear to be inoperative — there's no longer a separate installer package for the headers in the command line tools; and in any case I already have Xcode 12 installed as well as the command line tools — using `sudo xcode-select -s` to select the command-line tools install does not alter the outcome.

Using `brew install ruby` to install Ruby 3.0.1 does not appear to have any effect; Homebrew specifically states that it will not symlink the newer Ruby into `/usr/local/bin/` to avoid conflicts.

What *does* seem to have succeeded is to manually run Homebrew's installed Ruby out of `/usr/local/opt/ruby/bin/`: 

```
sudo /usr/local/opt/ruby/bin/gem install solargraph
```

Thereafter, as long as my `PATH` is set up appropriately, I am able to run `solargraph stdio` on the command line and the server appears to start. So, this may be more of a documentation issue.

**Comment by sandstrom** [comment]
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) or [Github Discussions](https://docs.github.com/en/discussions) (if one is setup for this repo) is better than Github.

If it isn't a confirmed issue, maybe this could be closed?

**Comment by castwide** [comment]
Closing as outside the scope of Solargraph. I've worked on similar issues on MacOS, and it almost always boils down to something that changed in XCode. It's not specific to Solargraph; it applies to any gem or library that uses native extensions.

Like @CKolkey said, using a version manager like `rbenv` or `rvm` is probably the best way to go.
