### ISSUE TITLE
CompletionItem::Resolve JSON response contains duplicated keys

### ISSUE THREAD

**Issue by anryoshi** [castwide/solargraph#432]
Using [vim-lsp](https://github.com/prabirshrestha/vim-lsp) I found that feature related to showing hover for autocompletion items I completely broken, because Vim cannot parse resulting JSON with error:
```
Vim(let):E938: Duplicate key in JSON: "label"
```

After some debugging I found that [method](https://github.com/castwide/solargraph/blob/master/lib/solargraph/language_server/message/completion_item/resolve.rb#L19) preparing result in CompletionItem::Resolve merges hashes with symbols as keys and hashes with strings as keys, it is after serialised to JSON with duplicated keys
```ruby 
def merge pins
  ...
  result = params
    .merge(pins.first.resolve_completion_item)
    .merge(documentation: markup_content(join_docs(docs)))
  ...
end
```

As quick solution I changed this code to
```ruby 
def merge pins
  ...
  sym_params = params.transform_keys(&:to_sym)
  result = sym_params
    .merge(pins.first.resolve_completion_item)
    .merge(documentation: markup_content(join_docs(docs)))
  ...
end
```

Everything started working for me after that

**Comment by castwide** [comment]
Thanks for the suggestion. The fix has been included in v0.41.0.
