### ISSUE TITLE
Solargraph Does Not autocomplete libraries from require

### ISSUE THREAD

**Issue by jmburges** [castwide/solargraph#437]
Hello!

Thank you for making solargraph. I'm trying to get solargraph to work with neovim. I've tried both `LanguageClient-neovim` and `coc.vim` and am having the same issue. with both. Solargraph doesn't seem to recognize when I `require` anything. I open a generic `test.rb` file and type the following

```ruby
require 'csv'
CSV.p
```

and then wait for `parse` to get autocompleted and nothing. I'm using nvim 0.4.4 and solargraph 0.40.4. I've tried to turn on DEBUG level logging but can't figure out where the logging goes?

**Comment by jmburges** [comment]
I also tried this with the rails gem and did

```
require 'rails'
[].p
```

and hoped 'presence' would show up and it doesn't.

**Comment by castwide** [comment]
You might need to run `yard gems` and/or `solargraph bundle` to make external gem documentation available.

More tips for troubleshooting gem support: https://solargraph.org/guides/troubleshooting
Some Rails-specific tips: https://solargraph.org/guides/rails
