### ISSUE TITLE
could dependence as little as possible on third parties？

### ISSUE THREAD

**Issue by jingyuexing** [castwide/solargraph#439]
I thought this project is a pure `ruby language project`,BUT!,BUT!,BUT!,this project dependence on `jaro_winkler`,that project has `C code`,C CODE!,then there are a bunch of errors.f\*\*k jaro_winkler! f\*\*k C code,
f\*\*k thrid party!

A bit emotional, sorry

**Comment by castwide** [comment]
I try to limit dependencies on C extensions, but it takes a back seat to features and performance are concerned. Solargraph also uses Nokogiri, which also uses C extensions, but in my experience is the best HTML parser currently available for Ruby.
