### ISSUE TITLE
Searching for symbols in workspace isn't using fuzzy matching like searching for symbols in current file

### ISSUE THREAD

**Issue by garyking** [castwide/solargraph#44]
If I search for a symbol in the current file, then searching for `foobar` matches `foo_bar`, but searching for symbols across a workspace for `foobar` doesn't match `foo_bar` in another file, yet `foo_b` matches `foo_bar`.

Please enable fuzzy searching for symbols across workspaces too.

**Comment by castwide** [comment]
Workspace symbol queries use fuzzy matching in gem v0.31.0.
