### ISSUE TITLE
ActiveRecord::Assocations::CollectionProxy<MyType> as return type 

### ISSUE THREAD

**Issue by iftheshoefritz** [castwide/solargraph#447]
I'm implementing associations in solargraph-rails. When I make the the association reader return Array<String>, everything behaves nicely:

```
 Solargraph::Pin::Method.new(
      name: "my_types",
      comments: "@return [Array<MyType>]",
      ...
)
```

i.e. I get responses from Solargraph about Array methods like `my_types.first` and it knows that the return value of `.first` is a `MyType`.

But this doesn't:

```
Solargraph::Pin::Method.new(
      name: "my_types",
      comments: "@return [ActiveRecord::Assocations::CollectionProxy<MyType>]",
      ...
)
```

I get none of the methods described by [CollectionProxy](https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html)

... does solargraph bundle not document things deep inside ActiveRecord, or am I missing something else? It doesn't seem to be as simple as requiring activerecord inside the gem.

I have similar problems with the return values of date columns, where I decorate pins with `@return [ActiveSupport::TimeWithZone]` .

**Comment by castwide** [comment]
This appears to be an issue with how Solargraph adds implicit gems to the map. In projects that automatically import bundled gems (e.g., a typical Rails app), it shouldn't be necessary to `require` them explicitly, but I couldn't access the `ActiveRecord` namespace until I did so:

![image](https://user-images.githubusercontent.com/3704922/121750274-13467d00-cada-11eb-85ef-2dcd722963d9.png)

I'll dig further and see if I can figure out why the implicit import isn't happening.

**Comment by castwide** [comment]
Version 0.42.2 fixes automatic gem imports.

**Comment by iftheshoefritz** [comment]
Thanks for the quick update. Here's where I am now:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1541595/121861294-9f7ebd00-ccf1-11eb-8526-2787154cb59a.png">

solargraph-rails tells the server that there is a method on `Author` instances named `books` with return type `@return [ActiveRecord::Associations::CollectionProxy<Book>]`. The method is found by autocomplete, but autocomplete on the `books` method doesn't return anything:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1541595/121862664-f0db7c00-ccf2-11eb-851f-0c651269bcf2.png">

Am I doing the markup correctly: `@return [ActiveRecord::Associations::CollectionProxy<Book>]`?

**Comment by iftheshoefritz** [comment]
I didn't realise, but it seems like there's some miscommunication here. It wasn't just that I was trying to find the constant, it's that solargraph seems to know nothing about the methods on CollectionProxy:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1541595/122583397-15b45400-d051-11eb-9f77-e562a2be4f70.png">

(everything here is inherited from Object)

I get the same with ActiveRecord::Relation:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1541595/122583550-485e4c80-d051-11eb-9776-b7cb4d2b09bc.png">

I'm expecting to see all the methods documented here: https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html

**Comment by iftheshoefritz** [comment]
Closing this in favour of #473
