### ISSUE TITLE
Support for JRuby and Java types?

### ISSUE THREAD

**Issue by AlBundy33** [castwide/solargraph#462]
I have seen that it is possible to define types of variables with `# @type [Array]` which is really cool.

Is solargraph also able to work with JRuby and java-types?

For example in JRuby all(?) objects have a method to_java
And a really cool feature would be something like this

```
# @type [java.math.BigDecimal]
result = calc()
```
or
```
# @type [com.company.product.tools.MyFancyTool]
$tool
```

**Comment by castwide** [comment]
Unfortunately, there are no plans to support JRuby/Java-specific types at this time. The core maps are based on the MRI source.

**Comment by AlBundy33** [comment]
OK - then I'll try to generate ruby-classes from our java-classes.

**Comment by AlBundy33** [comment]
btw: is it possible to define the type of array elements
I know that I can define something like this
```
# @type [Array]
list = foobar()
list.each do |e|
end
```
Is it possible to define the type of the elements (e) in the first definition?

Current workaround
```
# @type [Array]
list = foobar()
list.each do |e|
  # @type [String]
  e = e
end
```

**Comment by castwide** [comment]
Yes. YARD types can be paramterized, and the core maps understand Array parameters:

```ruby
# @type [Array<String>]
list = foobar()
list.each do |e|
  e # <- recognized as String
end
```

**Comment by AlBundy33** [comment]
perfect - then I'll try to generate dummy-ruby-files to get codecompletion!

Thanks for your help.
