### ISSUE TITLE
Is there a forum - or failing that - how do I change eclipse editor behaviours?

### ISSUE THREAD

**Issue by myshkin-uk** [castwide/solargraph#469]
Complete newb question - for which I apologise.

Is there a forum for 'dumb questions support' - I googled but failed to find any pointer to one.
Github doesn't sound like the right place for that.

Failing that - here's the actual dumb question:
--------------------------------------------------------------------------------------------------
I have installed solargraph with my eclipse IDE SOLELY TO GET A SYNTAX-HIGHLIGHT EDITOR. I used to have one but it evaporated on an eclipse upgrade.

I have no clue what a language server is, or what else solargraph could do for me, and I probably don't care.

I have some simple issues
-  I HATE the colours in the syntax highlighting ( comments are unreadable on my monitor ) and haven't a clue how to alter them.
- The string-auto-complete after I type "don't" in a comment is driving me mad

For Java I can just drill down to 

- a syntax-colours page and set them.
- an behaviour page and turn off auto-suggest.

Can't see anything like that for solargraph in the eclipse drop-down pages..

So where do I start?

**Comment by castwide** [comment]
Asking questions in GitHub issues is fine. There's no official discussion forum at the moment.

Solargraph itself doesn't provide syntax highlighting. It looks like the [eclipse-solargraph plugin](https://github.com/PyvesB/eclipse-solargraph) adds highlighting on top of Solargraph features, so you might want to ask there.

**Comment by myshkin-uk** [comment]
Thank you - will do.
