### ISSUE TITLE
Neovim LSP STDERR

### ISSUE THREAD

**Issue by jonathan-raines** [castwide/solargraph#470]
Hello,

I am having a couple of issues with Solargraph using Neovim 0.5. I lose diagnostics and linting when I utilize a `.rubocop.yml` file that tries to include `rubocop-rails` or `rubocop-rspec`. 

[lsp.log including require rubocop-rspec](https://github.com/castwide/solargraph/files/6931706/lsp.log)
[lsp.log excluding require rubocop-rspec](https://github.com/castwide/solargraph/files/6931730/lsp.log)

It looks like there's a common error "STDERR - `fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n` but lsp diagnostics and linting stop working when I try to require `rubocop-rspec` and/or `rubocop-rails`. Both gems are in the gem file and have been installed via `bundle install`. I have verified with `bundle info`.

If I run `rubocop --require rubocop-rspec` from the command line, the config file works properly. Any help would be greatly appreciated. I can't really alter the config file because it's a work project but the linting and diagnostics is extremley helpful.

It there's anything else I can offer, please let me know.

**Comment by JuPlutonic** [comment]
#402 had rubocop-performance and rubocop-rails in his cwd's .rubocop.yml file
