### ISSUE TITLE
Interaction with other extensions, shell/terminal setup

### ISSUE THREAD

**Issue by sandstrom** [castwide/solargraph#471]
I'm trying to get the solargraph VS Code extension to work with direnv, which I'm using to load gems dynamically (I'm using a dedicated direnv VS Code extension that works at least with the VS Code terminal, https://marketplace.visualstudio.com/items?itemName=cab404.vscode-direnv).

VS Code terminal loads direnv properly:

![image](https://user-images.githubusercontent.com/122287/128710861-c88e83bc-9907-47c0-a762-bfcde65aaad9.png)

But I still get an error about how it can't load the gem:

![image](https://user-images.githubusercontent.com/122287/128710912-ad18c388-5afd-46d2-88ae-5e6b75aae009.png)

And I think this is because solargraph is trying to use the system ruby (it should find `~/.rubies/ruby-2.6.6/bin/ruby`, but doesn't) and so I'm assuming that's because it hasn't caught on to the PATH modifications made by direnv.

So my question is, does VS Code has some type of application-wide hook for shell setup, that extensions can opt into? My guess is that either my direnv extension doesn't do that properly, or that solaragraph extension isn't "considering" the PATH stuff that is setup.

I've also looked at activation order, but it seems like the direnv extension should activate first:

https://github.com/cab404/vscode-direnv/blob/master/package.json#L42
https://github.com/castwide/vscode-solargraph/blob/master/package.json#L37

*Sorry if this issue is messy, couldn't figure out an easier way of explaining. Not sure this is a fault with this extension, could also be a problem with VS Code in general or with the other extension (direnv extension).*

***

Somewhat related, I found this comment which may be of relevance:
https://github.com/microsoft/vscode/issues/46696#issuecomment-617257419

**Comment by cab404** [comment]
I think it belongs to VSCode extension bug tracker: https://github.com/castwide/vscode-solargraph/

**Comment by sandstrom** [comment]
@cab404 Finally got it working.

Reason for all my problems was that I had direnv script setup in `~/.zshrc` (runs only for non-interactive shells) instead of `~/.zprofile` (called by interactive and non-interactive shells; VS Code starts a non-interactive shell).

I agree this is the wrong repo, but would it be helpful with some general documentation on this (same for rbenv and others) in the https://github.com/castwide/vscode-solargraph repo?
