### ISSUE TITLE
Is it possible to define the type of a variable without assignment?

### ISSUE THREAD

**Issue by AlBundy33** [castwide/solargraph#475]
Something like this
```
# @type [MyModule::MyFancyTool]
$tool
```

my current workaround is this
```
# @type [MyModule::MyFancyTool]
$tool = $tool
```

It works as expected but I the first one looks much nicer in my oppinion.

**Comment by castwide** [comment]
Unfortunately, no. The `@type` tag needs to precede an assignment. I'm working on a more robust alternative, but no ETA yet.

Another option is to use the `@!parse` tag:

```ruby
# @!parse $tool = MyModule::MyFancyTool.new
```

Still not pretty, but it's a one-liner that doesn't introduce executable code.

**Comment by AlBundy33** [comment]
It seems that this doesn't work as expected (only tested in eclipse) - so I'll stick with $tool = $tool :-)

**Comment by castwide** [comment]
I'm glad you have a workaround, but I'll keep this on the radar and continue working on a better solution :-)
