### ISSUE TITLE
Is the doc folder needed?

### ISSUE THREAD

**Issue by giovdk21** [castwide/solargraph#5]
Hello,
I just checked it quickly and I think it's the YARD gem that's generating the doc folder, correct?

Is this then used by the solargraph server to provide auto-completion? Would it be possible not to have it or to specify a different path for it?

Thanks

**Comment by castwide** [comment]
Correct. YARD generates two folders by default: .yardoc, which contains the raw data; and doc, which contains static HTML. Solargraph does not require the doc folder. Even the .yardoc is optional, but using it significantly improves performance and quality of documentation.

You can configure YARD's behavior by putting a .yardopts file in the project's root folder. Add this line to stop generating the doc folder:

    -n

More information: https://rubydoc.tenderapp.com/kb/getting-started-with-rubydocinfo/setting-up-a-yardopts-file

**Comment by giovdk21** [comment]
Thanks @castwide 
I think going forward this could still be an option for the gem or the editor extension as maybe you still want to use yard but without having the gem generating the documentation automatically. And you won't have to manually create the config file for each project. But certainly not a priority, for now using the `.yardopts` should work fine in most cases.
