### ISSUE TITLE
Use different Ruby versions for Solargraph and project

### ISSUE THREAD

**Issue by eruizc-dev** [castwide/solargraph#502]
I'm currently maintaining a Ruby on Rails project that uses Rails version 2.4, the problem I run into is a version conflict.

I need ruby 2.6 or higher to run solargraph and ruby 2.4 to run my project and I don't know how to make it work. I'm using rvm to handle ruby installations.

### Repro steps

 1. Install solargraph with `gem install solargraph` (will be installed with default ruby version 3.0)
 2. Cd into project repo (rvm reads `.ruby-version` and changes to 2.4)
 3. Solargraph is no longer in path
 4. Trying to install `gem install solargraph` fails due to Ruby version
 5. Trying to launch Solargraph with full path fails because it cannot find dependencies
 6. Changing ruby version with `rvm use 2.6` allows me to install and launch Solargraph but then my project fails because of legacy libraries that only work with ruby 2.4

Is there any way I can run Solargraph with Ruby 2.6 (or even better, 3.0) and still work with Ruby 2.4 in my project? I've tried running Solargraph inside a Docker container but it still needs access to the project and its dependencies so I end up in the same situation installing 2 Ruby versions in a container if I want to have autocompletion for dependencies.

**Comment by castwide** [comment]
I'm not sure why installing Solargraph with Ruby 2.4 would fail, because the current release still supports it.

* Can you tell me what error message you get running `gem install solargraph` with 2.4?
* What editor are you using? (VS Code specifically supports rvm, but other editors might require additional setup.)

**Comment by eruizc-dev** [comment]
The following error is from a clean environment created with docker (`docker container run -it ruby:2.4 /bin/bash`):
```log
ERROR:  Error installing solargraph:
	The last version of racc (~> 1.4) to support your Ruby & RubyGems was 1.5.2. Try installing it with `gem install racc -v 1.5.2` and then running the current command again
	racc requires Ruby version >= 2.5. The current ruby version is 2.4.10.364.
```

I'm using neovim, which simply calls a background process with `solargraph stdio` and then interacts with it. Basically when I go to my project, rvm sets 2.4 as default and solargraph is no longer in path. Trying to install it causes that error and attempting to run it with absolute path causes the following:

```
$ /home/eruizc/.rvm/gems/ruby-3.0.0/bin/solargraph stdio
/home/eruizc/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)
	from /home/eruizc/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems.rb:300:in `activate_bin_path'
	from /home/eruizc/.rvm/gems/ruby-3.0.0/bin/solargraph:23:in `<main>'
```

**Comment by castwide** [comment]
Did you try `gem install racc -v 1.5.2` before `gem install solargraph`? 1.5.2 is the last version of racc that's compatible with Ruby 2.4.

**Comment by eruizc-dev** [comment]
I managed to get it working for 2.4 with
```
ERROR:  Error installing solargraph:
	The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.10.10. Try installing it with `gem install nokogiri -v 1.10.10` and then running the current command again
	nokogiri requires Ruby version >= 2.5, < 3.1.dev. The current ruby version is 2.4.10.364.

**Comment by castwide** [comment]
* Solargraph currently requires Ruby 2.4+.
* It involves some duplication, but the same is true of any gem that's required in multiple rvm environments. Trying to use Solargraph on a workspace that's configured for a different version of Ruby is liable to introduce more bugs than it fixes. (It might work in trivial cases, but as soon as a project involves RubyGems and Bundler, things get messy quick.)

**Comment by eruizc-dev** [comment]
It's a shame to have such limitations, but it seems there's nothing to be done. I'm going to close this issue, thank you for your help!
