### ISSUE TITLE
Consider skipping development_dependencies for gems

### ISSUE THREAD

**Issue by alisnic** [castwide/solargraph#510]
In https://github.com/castwide/solargraph/blob/949fa3c3be83de437f84c6acf8b9503347083471/lib/solargraph/yard_map.rb#L265 solargraph loads development dependencies of gems, which is not desirable in my opinion. Consuming gems is not the same as developing them, and this leads to the fact of MiniTest completions being available in my project (because it is a development dependency of other gems), although I do not require them anywhere:

<img width="951" alt="Screenshot 2021-11-29 at 18 37 59" src="https://user-images.githubusercontent.com/1770351/143907168-e351eeff-03a9-422e-b187-c301253eb935.png">

**Comment by castwide** [comment]
That line should already be excluding development dependencies from external gems. Is there a call to `require` minitest somewhere in your project, or in a file you currently have open? If you're using a development branch, does the problem still occur using 0.44.2?

**Comment by alisnic** [comment]
I don't have minitest required anywhere in my app. The only place where it is mentioned, is in `Gemfile.lock`, where it is listed as dependency of activesupport 😭 https://github.com/rails/rails/blob/5-2-stable/activesupport/activesupport.gemspec#L32

Is this why minitest is present in completions?

**Comment by castwide** [comment]
Yep, that would do it 😄

**Comment by alisnic** [comment]
Sorry for confusion then :D it wasn't immediately obvious from source code that solargraph handles this properly
