### ISSUE TITLE
ActiveSupport::Concern#included flags as not enough arguments

### ISSUE THREAD

**Issue by swalke16** [castwide/solargraph#513]
I have a Rails app with several modules that make use of ActiveSupport::Concern.  For simple example:

```
module Test
  extend ActiveSupport::Concern

  included do
    attr_accessor :user
  end
end
```

Any of the modules that uses the `inlcuded` method will flag an error in type checking:
```
 Not enough arguments to Module#included
```

I've tried several combinations of using the extended definitions file to override / overload the documentation to eliminate these but so far no luck.  Is there a way I can eliminate these in one swoop without needing to add some kind of comment into every file using ActiveSupport::Concern?

**Comment by grncdr** [comment]
I was able to solve this by adding the following to `config/definitions.rb`:

```rb
# @!parse
#   module ActiveSupport::Concern
#     def included; end
#   end
```

Side note: It's also important to make sure that `config/definitions.rb` is parsed by Solargraph if your `.solargraph.yml` defines the `include:` setting.

**Comment by swalke16** [comment]
@grncdr  Thanks, I **swear** I tried this and every other combination before submitting this issue but it does appear to be working now. Not sure if it was my error or an update to the tooling that fixed it.  

I got past this issue and now have a similar one that I'm struggling with that hopefully is also an easy answer.  I made a [test repository](https://github.com/swalke16/solar-test) for reproduction.  It's just a `Rails.new` with about three files added and one additional gem included. 

If you run `solargraph typecheck` in this project you should get:

```
/solar-test/app/models/concerns/admin_permissions.rb:3 - Not enough arguments to ApplicationPolicy.new
```

This seems to be happening because the `pundit` gem includes a template file for `application_policy.rb` used as part of a generator that has an initializer with definition of:

```
def initialize(user, record); end
```

Our project overrides / overloads this in `app/policies/application_policy.rb` with a new initializer defined as:

```
def initialize(user, record = nil); end
```

No matter what I attempt to put in my `config/solargraph_definitions.rb` for overload / override I can't seem to eliminate that typecheck error. 

Thanks in advance for any suggestions!

**Comment by grncdr** [comment]
I think that's a different enough problem that it should be it's own issue, I was under the impression that Solargraph will only parse files that are in a `require` or autoload statement, but it could be that it has to treat Gems differently.

**Comment by swalke16** [comment]
Thanks, I'll open a new issue and close this one.
