### ISSUE TITLE
Incomplete handling for @param reference tags

### ISSUE THREAD

**Issue by TeeSeal** [castwide/solargraph#515]
### TLDR
@param reference tags are ignored if the there are regular @param tags defined beside them.

### Problem statement
While  there is support for standalone param reference tags, those don't work correctly if there is a mix of both explicit and reference tags define in the YARD docs of the method. See below a failing test case. This is the test at https://github.com/castwide/solargraph/blob/master/spec/pin/parameter_spec.rb#L150 which I modified by adding the `qux` parameter before the reference.
```ruby
  it 'infers return types from method reference tags' do
    source = Solargraph::Source.load_string(%(
      class Foo
        # @param bla [String]
        def bar(bla)
        end
        # @param qux [Integer]
        # @param (see Foo#bar)
        def baz(qux, bla)
          bla._
        end
      end
    ), 'test.rb')
    api_map = Solargraph::ApiMap.new
    api_map.map source
    clip = api_map.clip_at('test.rb', [8, 14])
    paths = clip.complete.pins.map(&:path)
    expect(paths).to include('String#upcase')
  end
```

**Comment by castwide** [comment]
Released in v0.44.3.
