### ISSUE TITLE
Static type checking in unit tests

### ISSUE THREAD

**Issue by castwide** [castwide/solargraph#52]
The `tracer` branch includes an experimental feature for static type checking during unit tests. The specs demonstrate how to enable it in spec_helper:

```
require 'solargraph'
Solargraph.trace
```

When you run the specs, Solargraph generates a logfile (`solargraph.log` by default) that reports two types of errors:

1. A method in the workspace returned a value that doesn't match the type specified in its `@return` tag.
2. A method in the workspace received a parameter that doesn't match the type specified in its `@param` tag.

It can also issue warnings about undeclared return or param types with the `level` parameter:

```
Solargraph.trace level: :warning
```

**Comment by castwide** [comment]
I've only tried it with RSpec, but theoretically it should work with any test framework. Much like SimpleCov, it shouldn't care how or where it was attached to the process.

`Solargraph.trace` should be the only call you need.

The log gets written to `solargraph.log` in the pwd. You can change it with the `logfile` parameter:

```
Solargraph.trace logfile: '/path/to/my.log'
```

**Comment by castwide** [comment]
Solargraph.trace may be superceded (or at least massively altered) by the new static type checker (#192).

**Comment by thomthom** [comment]
Did you see the static analysis tool for Ruby that Stripe just announced? https://sorbet.org/

**Comment by castwide** [comment]
Yep. There's some discussion about it in #194

**Comment by castwide** [comment]
Combining this issue with #192
