### ISSUE TITLE
Please update the documentation 

### ISSUE THREAD

**Issue by eranif** [castwide/solargraph#525]
Hi,
I tried to build `solargraph` on Ubuntu `18.04`
Seems that the README.md is missing this line:

```
sudo apt install ruby-dev
```

**Comment by castwide** [comment]
The `ruby-dev` requirement isn't inherent to Solargraph, but to Ruby itself. Any gem that uses native extensions needs the Ruby development headers to be installed on the system. (Solargraph doesn't have any native extensions, but a couple of its dependencies do.)

**Comment by eranif** [comment]
As a newcomer to Ruby, I already had Ruby installed on my laptop and I wanted to try something with Solargraph.
I followed the instructions as they appear here and I got an error...
After installed `ruby-dev` the problem went away. You are probably right with your argument, but the fact is: 
I followed the instructions here and they are not enough

I don't see any harm in adding the above the documentation, unless your audience is only users with previous Ruby experience (unlike me)

Thanks

**Comment by castwide** [comment]
I definitely want Solargraph to be accessible to as many people as possible, but I'm a little concerned about the snowball effect of maintaining documentation for platform-specific instructions for installing Ruby itself. One example of my concern is ongoing issues with the [default system package for Ruby on MacOS](https://github.com/castwide/vscode-solargraph/issues/78). New versions of MacOS and/or XCode would change details without notice, so proper documentation of the installation process became a moving target.

A more practical alternative might be to provide links to third-party Ruby installation guides. That could help newcomers get started more quickly without putting the onus of maintaining the documentation on this project. The [official documentation](https://www.ruby-lang.org/en/documentation/installation/) is a good place to start. For Ubuntu, it suggests `sudo apt-get install ruby-full`, which includes `ruby-dev` as a dependency.
