### ISSUE TITLE
Determining if core docs are up-to-date via script

### ISSUE THREAD

**Issue by keithlayne** [castwide/solargraph#528]
I have a setup script that setups up solargraph among other things. I'm trying to make this as reliable (read: idiot-proof) on one hand and as painless as possible on the other. I have something along the lines of:

```sh
gem install solargraph
solargraph download-core
solargraph bundle
```

AFAICT, all of these steps seem to run pretty fast, i.e. not do unnecessary work when run repeatedly, except for `download-core`. It seems to re-download the docs regardless. In my case, it's "reverting to closest match...", but I don't know if that matters.

Is there a way to check and only run this step conditionally? I'd like to make this something I can have my teammates run all the time without annoyance, even maybe a dummy-proof "set up and run the app in dev mode" script. It might not even be noticable for lots of people, but my internet sucks enough that I don't wanna be wasting even a few MBs all the time. Any ideas?

**Comment by alisnic** [comment]
you can check whether a core is downloaded using `solargraph list-core`. After that, it's just a matter of checking the command output and running `download-core` if necessary

**Comment by keithlayne** [comment]
That doesn't actually sound sufficient to determine if it's up-to-date.

**Comment by castwide** [comment]
I'm afraid there's no simple solution for this case, but one workaround is to run `solargraph list-cores` to see what's installed and `solargraph available-cores` to see if there's a closer match available for download.

**Comment by keithlayne** [comment]
Thats fine, thanks for following up!
