### ISSUE TITLE
The workspace is too large to index

### ISSUE THREAD

**Issue by jtaekema** [castwide/solargraph#54]
I'm using the latest plugin from VSCode but 5000 seems like a low limit, is there a way to change this limit in a configuration?

<img width="448" alt="screen shot 2018-04-30 at 1 01 35 pm" src="https://user-images.githubusercontent.com/2491622/39447857-f88acf9a-4c77-11e8-8b83-41ccb2a5ef56.png">

**Comment by castwide** [comment]
Raising the limit or allowing it to be configurable are possibilities. The primary reason for the limit is to serve as a sanity check, e.g., if someone opens their entire home directory as a workspace. When that error occurs, the server will still index open files, but will not generate project-wide API maps.

You might also be able to resolve the issue by adding a .solargraph.yml file to your project. The current default behavior is to index all .rb files except for `test` and `spec` directories. If your project has a `vendor` directory, you might want to exclude that as well. Example configuration:

```
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
reporters: []
domains: []
required: []
plugins: []
```

Note that excluded files will still be mapped while you're actively editing them, but their symbols won't be included in other files.

The next version of the gem will exclude the vendor directory by default. The preferred method for mapping vendor code is through its YARD documentation.

**Comment by jtaekema** [comment]
Thanks for the reply!

I've already excluded tests/vendor/etc to bring my project from ~40k to 22k files, there isn't anything more I can do on this front. I also regularly work on projects that are roughly this size so this doesn't seem unusually large to me.

I believe that indexing and code completion is *more* important in larger projects as the amount of code is harder to keep all in your head so anything that can be done to support a higher limit would be appreciated.

**Comment by castwide** [comment]
Fair point. I certainly don't want force large projects to work with reduced functionality.

I'll add some sort of mechanism to version 0.21.0, which I hope to release next week. Most likely it'll be an option in .solargraph.yml that allows you to set or remove the workspace size limit. That seems like a decent compromise between users who open a directory that shouldn't get mapped and users who know how big their project is.

**Comment by castwide** [comment]
The master branch includes a `max_files` setting in .solargraph.yml. The default is 5000. Setting it to 0 removes hard limits on the workspace size.

Version 0.21.0 should be published by May 7.

**Comment by douglascamata** [comment]
@jtaekema you should also exclude the `.bundle` folder, if you don't find it a problem. Usually what slows down `solargraph` is indexing all the dependencies of the project.

**Comment by ccarse** [comment]
Is this something that can be configured in the vs code extension or does this require a .solargraph.yml file? If not, is this something that could be added to the extension? Thanks.

**Comment by Nowaker** [comment]
Ping on this. How do I set `max_files` to a value of my choosing via VS Code settings?

**Comment by castwide** [comment]
You need to do it in your project's `.solargraph.yml` file. Documentation: https://solargraph.org/guides/configuration

**Comment by imjared** [comment]
Is there a straightforward way to see how many files are being indexed after modifying the configuration? I'd like to modify my config by adding ignores then see what effect the modification has on the indexed file count.

**Comment by castwide** [comment]
Try `solargraph list` or `solargraph list --count` from the command line.
