### ISSUE TITLE
textDocument/hover responses are blank and not plaintext

### ISSUE THREAD

**Issue by mattmassicotte** [castwide/solargraph#543]
Hello! Running 0.44.3.

My client is registered for hover with `contentType` = `plaintext`. But, the server is seems to always reply with `kind` = `markdown`. Not a huge deal, but thought I'd report it.

I'm also noticing that it seems to be very frequently blank, with an empty string for `value`. Is that how Solargraph communicate that it has no data?

**Comment by castwide** [comment]
Confirmed. I should be able to make the server return `plaintext` when configured to do so, although the text is likely to contain markdown/rdoc/whatever annotation exists in the original documentation.

An empty string for hover content typically means that there's no documentation available.

**Comment by mattmassicotte** [comment]
Ok this makes sense, thank you!

Other servers seem to return "null" for Hover when they have no information, which is allowed by the spec. I think that may be worth considering.

Not knowing the format is a tricky one. But, don't think the server should misrepresent the content. If you cannot guarantee plaintext, I think the current behavior may be best.

**Comment by castwide** [comment]
The next release will return `null` instead of an empty string for blank hovers.

**Comment by mattmassicotte** [comment]
That's great, thank you!

**Comment by castwide** [comment]
Released in version 0.46.0.

**Comment by castwide** [comment]
Version 0.47.0 will make one more related change. Instead of a null `Hover.contents.value` property, the `textDocument/Hover` message will return a null `Hover` object. See #583
