### ISSUE TITLE
Provide previews in the results of "textDocument/references" call

### ISSUE THREAD

**Issue by ralfthewise** [castwide/solargraph#545]
I currently use cscope in vim to list references but I would like to switch to solargraph.  However, it would be nice if solargraph could somehow return a preview of each reference location in the results of the `textDocument/references` call.  Here's what it looks like with cscope (when showing references to the `determine_project_dir` method):
![image](https://user-images.githubusercontent.com/697803/159602780-4fe1d5aa-4fe1-4e69-8606-ef03a4421008.png)

**Comment by castwide** [comment]
I suspect this is a limitation of the language server client, not Solargraph itself. This is what VS Code displays in response to a `textDocument/references` request:

![image](https://user-images.githubusercontent.com/3704922/159673993-21fb6078-8989-4c08-b6f1-bceb90e2cfa8.png)

**Comment by ralfthewise** [comment]
I don't think so, unless I have solargraph configured incorrectly somehow.  Here is the raw response I get back from solargraph when I do a `textDocument/references` request:
```
{
  "jsonrpc": "2.0",
  "id": 5,
  "result": [
    {
      "uri": "file:///home/tim/dev/vimconfig/bundle/juggler/autoload/juggler/completer.rb",
      "range": {
        "start": {
          "line": 35,
          "character": 22
        },
        "end": {
          "line": 35,
          "character": 43
        }
      }
    },
    {
      "uri": "file:///home/tim/dev/vimconfig/bundle/juggler/autoload/juggler/completer.rb",
      "range": {
        "start": {
          "line": 227,
          "character": 8
        },
        "end": {
          "line": 227,
          "character": 29
        }
      }
    }
  ]
}
```

Maybe VSCode is doing some sort of enrichment after it gets results from solargraph?

**Comment by ralfthewise** [comment]
Huh, looking at the LSP spec maybe there's nothing that can be done, the results returned needs to be a `Location[]` which doesn't have any fields that allow previewing - https://microsoft.github.io/language-server-protocol/specifications/specification-current/#range

**Comment by ralfthewise** [comment]
Yeah, no way to return previews based on the LSP spec. Seems like a bit of an oversight to not at least optionally include it.

Sorry, @castwide, I misunderstood your comment thinking you were suggesting vim just wasn't displaying what solargraph was providing, but I see now you were saying that this needs to be done by the LSP client.  Thanks!
