### ISSUE TITLE
Strict type check not reporting undefined method calls with defined roots

### ISSUE THREAD

**Issue by felipeccastro** [castwide/solargraph#553]
Related to this test: https://github.com/castwide/solargraph/blob/master/spec/type_checker/levels/strict_spec.rb#L22 

If I use `String.new.not_a_method` I get an error, but if I store the string in a variable before calling the method I don't see an error. Same applies for any class, if I store an object in a variable I can call any non existing methods without reports.

<img width="199" alt="Screen Shot 2022-04-26 at 6 55 51 PM" src="https://user-images.githubusercontent.com/3835098/165399025-1088e3ec-fc22-4a5f-9597-00e0d76e85ad.png">

Ruby Version: 2.7.0
Solargraph Version: 0.43.0

**Comment by castwide** [comment]
Confirmed. I'm looking into a fix.

**Comment by felipeccastro** [comment]
Thank you so much for implementing this! After trying Sorbet and Steep, and even considering switching away from ruby, Solargraph seems to have the best cost x benefit solution for type checking in ruby!
