### ISSUE TITLE
Documentation - be more explicit on how to keep so  documentation up to date with gems used

### ISSUE THREAD

**Issue by misner** [castwide/solargraph#572]
In the docs it's clearly written on starting using solargraph that you should:

> Run bundle install and use bundle exec yard gems to generate the documentation.

But I don't understand if running `yarn gems` is something that is done automatically each time I run `bundle install` or if I should run it regulary like every month to keep solargraph underlying documentation up-to-date with potentially new gems installed.

Here's my set up on VS Code

    "solargraph.commandPath": "/usr/local/bundle/bin/solargraph",
    "solargraph.bundlerPath": "/usr/local/bin/bundle",
    "solargraph.useBundler": true,
    "solargraph.formatting": true,//enable use of Rubocop for linting via solargraph
    "solargraph.diagnostics": true,
    "solargraph.autoformat": true,

I have on VS Code a postCreateCommand that runs every time I rebuild the container

`"postCreateCommand": "yarn install && bundle install && rake db:setup",
`
Now I wonder if, as stated above, bundle install actually includes the update of the solargraph documentation and if not if I should add in the postCreateCommand above `yarn gems' so it becomes:

`"postCreateCommand": "yarn install && bundle install && yarn gems && rake db:setup"`

Based on this, while the documentation is clear when you first start using solargraph, would it be a good thing to be more explicit about the fact we have to either automate or not forget to **regularly update** with yard gems to get the most out of Solargraph ?

**Comment by castwide** [comment]
It doesn't hurt to run `yard gems` occasionally to make sure. It won't regenerate existing documentation, just the new stuff.

This command will configure YARD to generate documentation automatically when a new gem is installed: `yard config --gem-install-yri`

More information: https://solargraph.org/guides/yard
