### ISSUE TITLE
Seems to break on Ruby 3.1 style hashes

### ISSUE THREAD

**Issue by ygt-mikekchar** [castwide/solargraph#574]
If you have a hash of the form `{param:}` instead of `{param: param}`, Solargraph seems to break.  I couldn't see any error messages, but any files that contained hashes of that form didn't show up in `solargraph scan -v`.

I haven't checked to see if there are cases where this doesn't happen, so if it turns out not to be obvious, please ping me and I'll make a minimal replication scenario.  As far as I can tell it always seems to happen in my code base.

**Comment by castwide** [comment]
Can you tell me how it breaks? This code seems to behave as expected for me with Solargraph 0.45.0:

```
a = 1
b = 2
c = {a:, b:} # <= c is recognized as a hash, while a and b are recognized as integers
```

**Comment by ygt-mikekchar** [comment]
The code that was breaking for me was in parameters:

```
def foo(bar:, baz:)
  puts(bar)
  puts(baz)
end

bar = 27
baz = 32

foo(bar:, baz:)
```

I'm not sure that *this* snippet will actually break because I don't know how to investigate it.  It's more that when I have files with code of that form, it doesn't end up in the `solargraph scan -v` list.  I'd be happy to give you a better reproduction scenario.  Can you point me to how to debug this a bit better?

**Comment by castwide** [comment]
Thanks for the example. I'm not surprised that `foo(bar:, baz:)` doesn't show up in a scan, because `solargraph scan` mostly checks return values on methods and variables, not arguments to method calls. It should only try to infer return types on the `foo` method definition and the `bar` and `baz` variable assignments.

Also worth noting: `scan` is mostly valuable for detecting errors in Solargraph itself, not for detecting problems in your code. I'd recommend using `typecheck` for verifying type safety. In the current version, the `typed` level of `typecheck` is mostly solid; the `strict` level works, but has a lot more false negatives.

**Comment by ygt-mikekchar** [comment]
Sorry, I think there is a bit of confusion here :-)  What I meant was that if you have any statement of the form `foo(bar:, baz:)` Solargraph does not seem to process anything in that file at all  -- even things it would normally process.  It seems as if it just gives up/crashes/something.   Changing it to `foo(bar: bar, baz: baz)` causes the entire file to be processed normally.  I think I really do need to come up with an easily testable scenario.  I'm using `scan` because there seems to be a problem in Solargraph :-)  However, I can't seem to get any details on what's going wrong.  It just doesn't produce any output for that file.

**Comment by ygt-mikekchar** [comment]
Create a file called foo.rb and add this code:

```
# frozen_string_literal: true

# This is Foo
class Foo
  def initialize
    @good = 'good'
  end

  def foo(bar:, baz:)
    puts(bar)
    puts(baz)
  end
end

f = Foo.new
bar = 'bar'
baz = 'baz'

f.foo(bar: bar, baz: baz)
```

Install the Solargraph gem (0.45.0) under Ruby 3.1.2.  Run `solargraph scan -v`.  The end of the output will include:

```
 |  (/home/someuser/work/foo/foo.rb 0)
Foo (/home/someuser/work/foo/foo.rb 3)
Foo.new (/home/someuser/work/foo/foo.rb 4)
Foo#initialize (/home/someuser/work/foo/foo.rb 4)
Foo#initialize | @good (/home/someuser/work/foo/foo.rb 5)
Foo#foo (/home/someuser/work/foo/foo.rb 8)
 | :bar (/home/someuser/work/foo/foo.rb 18)
 | :baz (/home/someuser/work/foo/foo.rb 18)
```

Now change the last line to `f.foo(bar:, baz:)` and rerun `solargraph scan -v`.  It now has:

```
 |  (/home/mikekchar/work/foo/foo.rb 0)
```

Only.

**Comment by castwide** [comment]
Based on your output, it definitely seems like the parser is treating that line as a syntax error. Unfortunately, I haven't been able to reproduce the problem using Solargraph 0.45.0 and Ruby 3.1.2.

**Comment by ygt-mikekchar** [comment]
Well, that seems like good news.  It must be a problem in my setup.  I'll play around with it some more.  Thanks!

**Comment by castwide** [comment]
Closing as stale. If this is still a problem, please feel free to reply or reopen.
