### ISSUE TITLE
Solargraph 0.46.0 breaks hover compatibility with Eglot

### ISSUE THREAD

**Issue by acdlbs** [castwide/solargraph#583]
One of the changes in the Solargraph v0.46.0 release was:

> Return nil value for empty hover contents

Eglot (version: 1.8) seems to be expecting a non-nil value (see issue 1019 - https://github.com/joaotavora/eglot/issues/1019) on hover and is throwing errors every-time the cursor is on an empty line.

**Comment by castwide** [comment]
It looks like I misunderstood the spec. The `textDocument/hover` response can be `null`, but if it contains a `Hover` object, its contents should not be `null`. I'll fix it in a patch release.

**Comment by castwide** [comment]
Released in v0.47.0.
