### ISSUE TITLE
Perhaps add donation url?

### ISSUE THREAD

**Issue by tdegrunt** [castwide/solargraph#59]
See GitLens repo for how they did it:
https://github.com/eamodio/vscode-gitlens#show-your-support-

**Comment by castwide** [comment]
Thanks for the thought. I'm looking into options for funding development. Donations and patronage are both possibilities.

**Comment by castwide** [comment]
The [README](https://github.com/castwide/solargraph/blob/master/README.md) now includes links to sponsor via [Patreon](https://www.patreon.com/castwide) and contribute one-time donations via [PayPal](https://www.paypal.me/castwide).

Related: #138
