### ISSUE TITLE
Ruby parser version is included on each diagnostic message.

### ISSUE THREAD

**Issue by WayneNoschang** [castwide/solargraph#597]
I get a message under each diagnostic about the ruby version parser. I honestly find this message distracting and would like to get rid of it. 
Error occurs while using neovim in iTerm2 on MacOS. Neovim plugins and configuration includes [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#solargraph) with default settings. Here are two examples showing the recurring message _"(Using Ruby 3.0 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)"_
<img width="1440" alt="Screen Shot 2022-09-13 at 12 46 26 PM" src="https://user-images.githubusercontent.com/43730526/189960705-36572249-2c56-48e6-9de8-0fbe852e35fc.png">
<img width="1440" alt="Screen Shot 2022-09-13 at 12 51 03 PM" src="https://user-images.githubusercontent.com/43730526/189960859-58160019-3c35-43d5-9439-af3867912b47.png">
However, formatting messages do NOT have this issue...
<img width="1440" alt="Screen Shot 2022-09-13 at 12 54 55 PM" src="https://user-images.githubusercontent.com/43730526/189961527-b4a4305c-eab6-4c34-bc43-88f47463bfef.png">
<img width="1440" alt="Screen Shot 2022-09-13 at 12 55 26 PM" src="https://user-images.githubusercontent.com/43730526/189961561-ef7eebca-2990-4e6d-bdcc-c14c5f9a8e0b.png">
I already tried to set the ruby version with a .rubocop.yml file and also made a .solargraph.yml config with [default settings](https://solargraph.org/guides/configuration) however nothing changed.
<img width="1440" alt="Screen Shot 2022-09-13 at 1 15 54 PM" src="https://user-images.githubusercontent.com/43730526/189965427-442f8963-68c3-40c6-8eeb-ca72570aed41.png">
Any help on this would be appreciated, thanks.

**Comment by grncdr** [comment]
This message comes from the Rubocop syntax lint and not Solargraph, you should probably open an issue there. https://github.com/rubocop/rubocop/blob/00e7ac78fb83383ef537e9e08ecf2301a1427578/lib/rubocop/cop/lint/syntax.rb#L19-L24

**Comment by WayneNoschang** [comment]
OK thank you 👍
