### ISSUE TITLE
Fails to start with `ruby exited with status code 1` on Sublime Text 4 with Sublime LSP

### ISSUE THREAD

**Issue by kevinfiol** [castwide/solargraph#598]
OS: Linux Mint 20.3 (Ubuntu-based)
Sublime Text Version 4126
Ruby 3.0.1

I am using `chruby` to manage Ruby versions. I took this into account when configuring Sublime LSP, and use absolute paths to solargraph and ruby.

Screenshot:
![image](https://user-images.githubusercontent.com/4752973/190030069-4448b729-f89f-441c-8750-484f4a8940ff.png)

LSP Config:
```json
    "clients": {
        "ruby": {
            "enabled": true,
            "command": [
                "/home/kevin/.rubies/ruby-3.0.1/bin/ruby",
                "/home/kevin/.gem/ruby/3.0.1/bin/solargraph",
                "stdio"
            ],
            "selector": "source.ruby | text.html.ruby",
            "initializationOptions": {
                "logLevel": "debug",
                "diagnostics": true,
            },
        },
    }
```

Unfortunately, I am not able to get any useful logs from the Sublime console:
```
plugins loaded
LSP: enabled configs: LSP-bash, LSP-dockerfile, LSP-yaml
LSP: disabled configs: Deno, LSP-typescript, clangd, erlang-ls, gopls, ocaml, polymer-ide, ruby, rust-analyzer, sorbet
LSP: applying .sublime-project override for ruby
LSP: starting ['/home/kevin/.rubies/ruby-3.0.1/bin/ruby', '/home/kevin/.gem/ruby/3.0.1/bin/solargraph', 'stdio'] in /home/kevin/me/dev/cms/rails-test
Package Control: Skipping automatic upgrade, last run at 2022-09-13 19:54:39, next run at 2022-09-13 20:54:39 or after
LSP: applying .sublime-project override for ruby
```

**Comment by grncdr** [comment]
As a sanity check, what does the following command show if you run it in a terminal?

```sh
/home/kevin/.rubies/ruby-3.0.1/bin/ruby /home/kevin/.gem/ruby/3.0.1/bin/solargraph version
```

**Comment by kevinfiol** [comment]
@grncdr Thanks for asking. Here is the output:
```
kevin@hp ~> /home/kevin/.rubies/ruby-3.0.1/bin/ruby /home/kevin/.gem/ruby/3.0.1/bin/solargraph version
0.46.0
```

**Comment by castwide** [comment]
You might also want to try running `solargraph scan -v` on your workspace to see if you get an error. (If you do, it probably indicates a bug in Solargraph, not your code. More info: https://solargraph.org/guides/scanning-workspaces)

**Comment by grncdr** [comment]
@kevinfiol I'm not super familiar with chruby but from skimming the README it appears to rely on setting multiple environment variables. There's a good chance that the environment Sublime uses to spawn LSP processes is not compatible enough to just copy executable paths around.

Maybe give this a try:

```json
"command": [
  "/bin/sh",
  "-c",
  "source /usr/local/share/chruby/chruby.sh && chruby ruby-3.0.1 && exec solargraph stdio"
]
```

If that doesn't work, you can use `/bin/sh` to start a shell session without your usual profile and figure out what commands need to be run before `solargraph stdio`.

**Comment by kevinfiol** [comment]
> @kevinfiol I'm not super familiar with chruby but from skimming the README it appears to rely on setting multiple environment variables. There's a good chance that the environment Sublime uses to spawn LSP processes is not compatible enough to just copy executable paths around.
> 
> Maybe give this a try:
> 
> ```json
> "command": [
>   "/bin/sh",
>   "-c",
>   "source /usr/local/share/chruby/chruby.sh && chruby ruby-3.0.1 && exec solargraph stdio"
> ]
> ```
> 
> If that doesn't work, you can use `/bin/sh` to start a shell session without your usual profile and figure out what commands need to be run before `solargraph stdio`.

Thank you! This seemed to do the trick. I also remembered in doing this that I had installed `chruby` using Linuxbrew, so the command ended up looking like this:
```json
"command": [
  "/bin/sh",
  "-c",
  "source /home/linuxbrew/.linuxbrew/share/chruby/chruby.sh && chruby ruby-3.0.1 && exec solargraph stdio"
]
```
