### ISSUE TITLE
add Convention for rake files

### ISSUE THREAD

**Issue by dleavitt** [castwide/solargraph#613]
Would you been open to a PR that adds a Convention for Rake files to go alongside the other ones here https://github.com/castwide/solargraph/tree/master/lib/solargraph/convention?

Seems like a natural fit:
- ✅  Top-level DSL
- ✅  Easily identified by filename `Rakefile` or `.rake`
- ✅  Pretty ubiquitous in rubyland

**Comment by castwide** [comment]
Yes, I would. I'm gradually moving toward plugins for gem-related conventions, but Rake is ubiquitous enough that it makes sense to support it natively, much like `Gemfile` and `.gemspec`.
