### ISSUE TITLE
Is the .rubocop.yml local config picked up?

### ISSUE THREAD

**Issue by patilarpith** [castwide/solargraph#62]
Looking at the rubocop command here, it does not seem like --config file path is specified. 
https://github.com/castwide/solargraph/blob/f66aa8493417183327f2a7c1951c666cd6d37fdc/lib/solargraph/diagnostics/rubocop.rb#L24

I'm guessing the command should also contain ```--config {rootUri}/.rubocop.yml```  param where rootUri is the workspace root passed via initializeParams.

**Comment by castwide** [comment]
It's been working for me because I always start the server using the workspace as the cwd, so rubocop picks it up automatically. I suppose it wouldn't hurt to specify the path for language clients that don't do the same.

**Comment by castwide** [comment]
Fixed in the master branch. It'll be in version 0.22.0, which I expect to release tomorrow.

**Comment by castwide** [comment]
Released version 0.22.0.
