### ISSUE TITLE
Document Type Detection for =^ Types

### ISSUE THREAD

**Issue by gwillcox-r7** [castwide/solargraph#626]
In VSCode sometimes I get information that the type was inferred via `=^`. Looking at https://solargraph.org/guides/type-detection I don't see any definitions for this, only for `=>` which is for tagged types, and `=~` for inferred types. It would be good to update https://solargraph.org/guides/type-detection to denote what `=^` is meant to be as far as type information goes. Is this meant to be inheritance type information? I see that one is listed as possible way to detect things yet its symbol isn't listed on the website.

![image](https://user-images.githubusercontent.com/63261883/210941643-813bb7e0-451e-4c5d-8fc2-829b70222ce6.png)

**Comment by castwide** [comment]
You're correct, `=^` indicates that the return type was inherited. I'll update the documentation.

**Comment by castwide** [comment]
Updated: https://solargraph.org/guides/type-detection
