### ISSUE TITLE
CMD + Click on a definition should take you to the code, not the definition

### ISSUE THREAD

**Issue by davidalejandroaguilar** [castwide/solargraph#643]
## Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 3.1.2
- Ruby version manager (if any): asdf
- VS Code version: 1.76.2
- Operating System: Mac OS Monterrey 12.6
- Using language server? (eg `useLanguageServer` is true in your configuration?) Yes (rubyLocate)

## Expected behavior

CMD + Click on a definition should take you to the code.

## Actual behavior

CMD + Click on a definition takes you to the literal definition.

## Example

https://user-images.githubusercontent.com/15317732/229072512-6e295255-c5bf-4c1e-bfe5-b8b21f9ad014.mov

---

Not familiar with the codebase but let me know how I can help.

**Comment by castwide** [comment]
You're using CMD+click on the hover, not the name in the file. The hover links to the documentation.

**Comment by davidalejandroaguilar** [comment]
Tested again and this is working correctly, thanks!
