### ISSUE TITLE
Work over stdio?

### ISSUE THREAD

**Issue by ThisGuyCodes** [castwide/solargraph#65]
Hey! This is awesome! I'm using https://github.com/onivim/oni and would love to use this with it, but Oni only supports stdio for language servers at the moment: could you make solargraph work over stdio as well as it's current TCP setup? My naive self tells me this should be relatively trivial to impliment.

**Comment by megalithic** [comment]
this would be grand! thanks @castwide

**Comment by zxiest** [comment]
I have just submitted an [issue](https://github.com/onivim/oni/issues/2350) to Oni for TCP support ; I had been looking for something like Oni for years - I just found out about it yesterday! Having it work with Solargarph would be amazing!

**Comment by castwide** [comment]
The `stdio` branch includes a working implementation of the stdio transport. Run `solargraph stdio` to start the server. The performance issues I encountered in my earlier experiments appear to be largely resolved here. I haven't benchmarked it, but its performance "feels" very close to the socket server.

I encourage client developers to clone/fork it and give it a try. Barring major bugs, I expect to publish it in gem version 0.23 or 0.24.

**Comment by castwide** [comment]
The `stdio` branch is merged into `master`.

**Comment by megalithic** [comment]
thanks @castwide will the gemspec be updated and the update get published to rubygems in the next couple days?

**Comment by castwide** [comment]
@megalithic I expect to publish it by Monday (July 2) at the latest.

**Comment by castwide** [comment]
Published gem v0.23.0. Clients using stdio should run `solargraph stdio`.

**Comment by zxiest** [comment]
Guys, has anyone been able to get suggestions? Oni shows that Ruby has connected to language server; hovering over a class name shows me data. However, when I do `[1,2,3].` , I do not get any suggestions.

**Comment by devinalvaro** [comment]
@zxiest Yes, I've got suggestions using [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) with this setting:

```
let g:LanguageClient_serverCommands = {
            \ 'c': [ 'clangd' ],
            \ 'cpp': [ 'clangd' ],
            \ 'javascript': [ 'javascript-typescript-stdio' ],
            \ 'python': [ 'pyls' ],
            \ 'ruby': [ 'solargraph',  'stdio' ],
            \ }
```

I don't use Oni though, so can't help you there, sorry.

**Comment by bbtdev** [comment]
@devinalvaro Can you post a full vimrc/init.vim? I can't get it to work in multiple async complete plugins.

**Comment by devinalvaro** [comment]
@bbtdev  Sure, here it is https://pastebin.com/kUj551nv.

**Comment by castwide** [comment]
Gem version 0.24.0 fixes a bug that affected some clients using the stdio transport. More information: https://github.com/castwide/solargraph/issues/79

**Comment by castwide** [comment]
If anyone has any problems using the stdio transport, please open a new issue.
