### ISSUE TITLE
Error installing 0.49.0 on macOS

### ISSUE THREAD

**Issue by mrblrrd** [castwide/solargraph#653]
Hello! I wish to try solargraph with neovim but can't install it. Installation fails on jaro_winkler native extension which I've reported here https://github.com/tonytonyjan/jaro_winkler/issues/51.
I understand that it's not directly related to solargraph, just trying to get any hint how I can fix this.

**Comment by danillos** [comment]
I'm having the same issue.

**Comment by mrblrrd** [comment]
Solved in https://github.com/tonytonyjan/jaro_winkler/issues/51.
