### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by Goniff** [castwide/solargraph#658]
Hello, I am running the following command.
`solargraph available-cores`

It comes back with the following error. 
SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)

I can download other ruby gems without issue. I also followed all the steps listed at: https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html

I was not sure if this was an issue I should list here or at rubygems (https://github.com/rubygems/rubygems/issues).

**Comment by castwide** [comment]
Downloading cores is no longer necessary in the current version, but this should be working in older versions for the time being.
