### ISSUE TITLE
(vim-lsc) Not able to find class definition in other files.

### ISSUE THREAD

**Issue by GCorbel** [castwide/solargraph#66]
I created two files `blabla.rb` and `test.rb`

In blabla.rb I have : 

```
class Blabla
  def self.blabla

  end
end
```

If I type `Blabla` in this file and I try to find references, with `vim-lsc` and the function `:LSClientFindReferences` it works. Now, when I go on file `test.rb` and I try to do the same it find nothing. I tried to generate the documentation with `yard` but it's the same.

Is there something to do?

**Comment by castwide** [comment]
Did you set the workspace to the files' root folder? i.e., the `rootUri` parameter in the `initialize` method.

**Comment by GCorbel** [comment]
Sorry but I don't understand what you mean. Where should I add the parameter?

I only have the default `.solargraph.yml` file.

**Comment by castwide** [comment]
It's a function of the language client. The first message it sends to the server is `initialize`, which contains the `rootUri` parameter. VS Code, for example, sets it to whatever folder is opened as a workspace.

I'm not familiar with vim-lsc, so I'm afraid I can't be more specific. I did notice that its documentation references the `initialize` method in an example around line 300: https://github.com/natebosch/vim-lsc/blob/master/doc/lsc.txt

**Comment by GCorbel** [comment]
I have to check. Thanks.

Is there a way to have some log from solargraph? It can be useful for debugging.

**Comment by castwide** [comment]
You can check the server responses for error messages. The server's process also emits some information via stderr.

**Comment by GCorbel** [comment]
I updated my .vimrc file with : 

```
let g:lsc_server_commands = {
     \ 'ruby': {
     \    'command': 'localhost:7658',
     \    'message_hooks': {
     \        'initialize': {
     \            'rootUri': {method, params ->
     \                          lsc#uri#documentUri('/workspace/my_project')},
     \        },
     \    },
     \  },
     \}
```

And I still have the same problem. I have no trace on the server side. When I am on the file where the class is, everything works and I'm able to find the definition of a method.

Do I have to generate the doc with yard?

**Comment by castwide** [comment]
You shouldn't need to generate the YARD documentation for source code in the workspace itself. That's mostly necessary for external gems.

I'll try some tests with vim-lsc on a CentOS box later, or maybe someone else with vim-lsc experience can offer assistance.

**Comment by GCorbel** [comment]
I tried with LanguageClient-neovim and it seems to work so the problem comes from vim-lsc. Feel free to close this issue if you want.
