### ISSUE TITLE
Ambiguous documentation on severity level about uninferred methods

### ISSUE THREAD

**Issue by justaskz** [castwide/solargraph#671]
Hello, [documentation](https://solargraph.org/guides/type-checking) on Type checking states:
```
Strict checks require all methods to have either a tagged type or an inferred type. If an untagged method’s type cannot be inferred, the type checker issues a warning.
```

In reality checker issues `error`. Is this correct behaviour?

**Comment by castwide** [comment]
Can you provide an example? You should only get errors when either the type can't be inferred or it doesn't match the tagged type.

**Comment by justaskz** [comment]
I actually dont remember the context, therefore cant reproduce. Lets close the issue
