### ISSUE TITLE
Feature request: provide request to get the current synced buffer content

### ISSUE THREAD

**Issue by chemzqm** [castwide/solargraph#69]
It looks like I have wrong synced buffer that makes solargraph not works after some content changes, so I need to know what's the current buffer content in solargraph after text edits applied.

**Comment by castwide** [comment]
This would be a non-standard request. Since the language server's buffer should typically not be the authority for the document version, it might be better to expose that data in a log message or some kind of debug output. Either way, I'm open to discussing solutions that assist in troubleshooting.

One possible issue is the `TextDocumentSyncKind`. What language client are you using? Right now Solargraph uses incremental document sync. If your client requires full document sync, we can look into adding that feature as well.

**Comment by chemzqm** [comment]
@castwide I'm using incremental document sync actually, but sometimes I would send full content to make sure content synced well, the TextDocumentContentChangeEvent interface:
```
/**
 * An event describing a change to a text document. If range and rangeLength are omitted
 * the new text is considered to be the full content of the document.
 */
export interface TextDocumentContentChangeEvent {
    /**
     * The range of the document that changed.
     */
    range?: Range;
    /**
     * The length of the range that got replaced.
     */
    rangeLength?: number;
    /**
     * The new text of the document.
     */
    text: string;
}
```
I would send `text` with full content without range and rangeLength, it's probably that solargraph not working as expected with this situation.

**Comment by castwide** [comment]
I'm not sure if there's a test for that particular use case, but it should definitely work. I'll try to confirm in the specs.

Are you using versioned text documents?

**Comment by chemzqm** [comment]
Sure, I have the version of textDocument increased by 1 after each change have made.
I don't have problem if I disable the full content sync request.

**Comment by castwide** [comment]
Okay, thanks. I'll check if there's a problem with how the server handles document changes.

If an error is occurring, you might be able to get more information from the stderr of the server process.

Also, in the absence of a server method, you could attach a debugger or add your own debug output if you run the server from source. Quick and dirty example of sending the document buffer to stderr after a [textDocument/didChange](https://github.com/castwide/solargraph/blob/master/lib/solargraph/language_server/message/text_document/did_change.rb) request:

```
class DidChange < Base
  def process
    host.change params
    STDERR.puts host.read_text(params['textDocument']['uri'])
  end
end

**Comment by castwide** [comment]
Gem version 0.27.0 fixes a threading bug that might have been the reason you experienced out-of-sync buffers. I'm also working on improved logging/debugging to help troubleshooting.

**Comment by chemzqm** [comment]
I'm not having that issue any more after I pass `rangeLength`
