### ISSUE TITLE
No completion when a part of a method name is already typed

### ISSUE THREAD

**Issue by dgutov** [castwide/solargraph#7]
Try this out in the demo:

1. Erase everything and type `[].`, press `Ctrl-Space`. See `each` as one of the completions (good).

2. Type `[].ea`, press `Ctrl-Space`. See no completions (and in the network console, the call returns `[]` in the suggestions field.

**Comment by castwide** [comment]
Confirmed. The problem appears to be specific to literal values. If you assign an array to a variable and enter Ctrl-space for a partial method name, the suggestions work. Example:

    x = [1,2,3]
    x.ea         # <- Ctrl-space returns suggestions

I'll fix literal value detection for the upcoming minor version update.

**Comment by castwide** [comment]
Fixed in version 0.11.2 and updated in the demo.

**Comment by dgutov** [comment]
This looks fixed, thanks!

**Comment by dgutov** [comment]
Here's a probably related problem, though: no completion after number literals.

```rb
123.| <- press Alt-Space here
```

**Comment by castwide** [comment]
Yep, got it. The fix will be included in 0.11.3.
