### ISSUE TITLE
Rails autoloading

### ISSUE THREAD

**Issue by SGbo** [castwide/solargraph#70]
Intellisense does not work at all when I use rails autoloading. Is it possible to use solargraph when using rails autoloading instead of require statements?

http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths-and-eager-load-paths

**Comment by castwide** [comment]
By default, Solargraph should map all the Ruby code in your workspace except for a few exceptions like the `test` and `vendor` directories. If you have a class `Foo` defined in `lib/foo.rb`, you should be able to see it from a file in the `app` directory.

If you're autoloading external directories or gems, you probably won't be able to see them. I'm not sure what the best solution is.

Even with incomplete maps, you should still get intellisense for the Ruby core and symbols/definitions in the document you're editing. Do those not work, either? If not, are you getting any error messages?

**Comment by SGbo** [comment]
Sorry for my late response, I figured out that the problem was that solargraph does not support multi-root workspaces yet. With a single workspace it works!
