### ISSUE TITLE
`Solargraph: -32603: [OptionParser::InvalidOption] invalid option: --autocorrect` 

### ISSUE THREAD

**Issue by DennisTheMenace780** [castwide/solargraph#707]
I am using Neovim with the Solargraph plugin, and for the life of me, I have no idea why my editor is constantly telling me I have this error. I don't have an `--autocorrect` flag enabled, and even if I do enable it, I still seem to get the problem. Has anyone else experienced this? I haven't been able to search much on this error.

**Comment by castwide** [comment]
It sounds like you're using RuboCop < 1.3.0. #665 should resolve this issue and will be included in the next release.

**Comment by DennisTheMenace780** [comment]
Can confirm we're using RuboCop `1.23.0`, so I will close this and keep an eye out for othe next release. Thanks for getting back!
