### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by bradleybeddoes** [castwide/solargraph#708]
Hi Folks - Thanks for the awesome gem and hard work on maintaining it.

Just a quick FYI that the main website seems to be having an SSL related issue, ERR_SSL_VERSION_OR_CIPHER_MISMATCH, which is denying all connections and in our case causing trouble in builds.

I'd really appreciate it if someone with relevant admin rights could take a look when you get a chance.

**Comment by castwide** [comment]
Thanks for bringing this to my attention. I'm working with the registrar to resolve the error.

**Comment by castwide** [comment]
Resolved.
