### ISSUE TITLE
Diagnostics always disabled

### ISSUE THREAD

**Issue by hlidotbe** [castwide/solargraph#74]
Hi,

After disabling _didSave_ handling (#73) diagnostics where still not working. After poking in the code I noticed that the default configuration for the LSP host is to have diagnostics disabled but I couldn't find a way to enable it.

That may be an issue with LanguageClient-neovim or my understanding of the LS protocol but when I change the default config then everything works as expected.

Did I miss something?

**Comment by castwide** [comment]
You should be able to set `diagnostics` to `true` in the `initialize` method's `initializationOptions`:

```
{
  "initializationOptions": {
    "diagnostics": true
  }
}
```

If you set it in the `workspace/didChangeConfiguration` method, it needs to be sent as `solargraph.diagnostics`:

```
{
  "settings": {
    "solargraph": {
      "diagnostics": true
    }
  }
}
```
