### ISSUE TITLE
Workspace Root Issues

### ISSUE THREAD

**Issue by bowmanmike** [castwide/solargraph#78]
I've got a large directory (single git repo) that contains a few related rails projects. 
```
root-dir
├── project-a
├── project-b
├── project-c
├── project-d
...
```
I tend to work mostly in a TMUX session based in the root directory, since sometime tasks require bouncing between multiple projects. When I open a neovim session in the root directory, solargraph takes a long time to index the workspace, and uses 4+ GB of RAM. I've tried to resolve this by opening neovim sessions from inside a specific project directory, but solargraph still uses the root directory as the workspace root. I've tried using separate `.solargraph.yml` files for each project, but that doesn't seem to work.

My workaround thus far is to keep the indexing limit at 5000, so that the entire workspace doesn't get indexed, and just let it index whatever file is currently open. This is manageable, and better than nothing, but it'd be awesome to be able to have solargraph treat each subdirectory as it's own workspace.

Any suggestions?

**Comment by castwide** [comment]
I've been considering the possibility of supporting .solargraph.yml files in workspace subdirectories. In this case, if each project subdirectory has its own, Solargraph would treat them as separate workspaces and defer mapping the corresponding files until one of them is opened in an editor.

**Comment by bowmanmike** [comment]
That sounds like it would resolve my issue! How is the root determined at the moment? Shouldn't opening a file in a subdirectory treat that directory as the root?

**Comment by castwide** [comment]
Right now it uses whatever directory the language client passes into the `rootPath` parameter of the `initialize` method.

**Comment by castwide** [comment]
Related issue: #114

**Comment by castwide** [comment]
Gem version 0.31 now includes support for multi-root workspaces. In the original example, each project folder can be added as a workspace folder and the server would map them separately.

Please feel free to open a new issue if there are any further questions or concerns.
