### ISSUE TITLE
Invoking function signature shows 2 identical declarations.

### ISSUE THREAD

**Issue by hifall** [castwide/solargraph#90]
First of all, awesome project!

I am having an issue when using this language server. Please take a look at the following screenshot:

<img width="467" alt="screen shot 2018-09-25 at 9 05 11 pm" src="https://user-images.githubusercontent.com/5734293/46016228-d312f680-c106-11e8-9fc7-52f7adbdee30.png">

As you can see, in the above snippet, `sum1` is defined, and I am trying to display `sum1`'s signature. However, there are 2 identical signatures for `sum1`.

The response from the language server looks like this:

`{"jsonrpc":"2.0","id":1,"result":{"signatures":[{"label":"sum1(a, b)","documentation":""},{"label":"sum1(a, b)","documentation":""}]}}`

So, it looks to me that somehow the server returns 2 identical signatures for the function.

Any idea how I can fix it?

Thanks!

**Comment by castwide** [comment]
Thanks!

That duplication issue appears to happen only for method definitions in the root namespace. It works as expected inside a class:

![image](https://user-images.githubusercontent.com/3704922/46036385-5e729480-c0d3-11e8-8aee-dc62f418e509.png)

Root methods get treated a little differently for a few reasons. I'll look further into it and try to have a fix in an upcoming gem.

**Comment by castwide** [comment]
Fixed in version 0.28.2.

**Comment by hifall** [comment]
How cool is that!

If I do `gem install solargraph`, will I pick up your latest fix?

**Comment by hifall** [comment]
Confirmed working. Very cool. Thanks!
